### ISSUE TITLE
Postfix in declaration

### ISSUE THREAD

**Issue by gwhitney** [DanielXMoore/Civet#1002]
I'd like to do
```
stuff := n*2 for n of [0..9]
```
(or with a newline after the const assignment if need be) but I can't seem to get anything like this to work. Am I missing anything?

**Comment by bbrk24** [comment]
You need one more set of brackets:

```civet
stuff := [n * 2 for n of [0..9]]
```

**Comment by gwhitney** [comment]
Ah, I see, thanks. (The square brackets do embed the result in an extra layer of array, as expected.) I sort of get why the parentheses are desirable in the one-liner I wrote, as otherwise it looks like maybe I am trying to declare `stuff` ten times, but I don't really see why they should be necessary with a newline, e.g.
```
stuff :=
   n*2 for n of [0..9]
```

**Comment by edemaine** [comment]
I think we could/should allow postfix loops/conditions in the right-hand side of a declaration (but not assignment), as we don't expect multiple declarations.
