### ISSUE TITLE
Braced literals with `await`

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#1012]
We can do like this (from [the reference](https://civet.dev/reference#braced-literals)):
```js
another := {person.name, obj?.c?.x}
computed := {foo(), bar()}
named := {lookup[x+y]}
```
But not this:
```js
asyncComputed := {await asyncFoo()}
```
We can only explicitly write like this:
```js
asyncComputed := {asyncFoo: await asyncFoo()}
```
Which is not cool.

It would be great to be able to use asynchronous functions and properties along with synchronous ones.

**Comment by edemaine** [comment]
Maybe we can more generally allow arbitrary unary operators before the CallExpression? So also `{!!person}` → `{person: !!person}`.
