### ISSUE TITLE
Add `as tuple`

### ISSUE THREAD

**Issue by Jacob-Lockwood** [DanielXMoore/Civet#1037]
`as const` makes tuple types `readonly`:

```typescript
const arr = [1, 2, 3] as const;
//    ^? const arr: readonly [1, 2, 3]
```

There’s a hack to solve this using `satisfies`:

```typescript
const arr = [1, 2, 3] satisfies [unknown, ...unknown[]];
//    ^? const arr: [1, 2, 3]
```

Maybe Civet could have `as tuple` as shorthand for `satisfies [unknown, ...unknown[]]`?

This solves issue #1004

**Comment by STRd6** [comment]
`as tuple` as shorthand for `satisfies [unknown, ...unknown[]]` sounds good to me.

**Comment by edemaine** [comment]
Would anyone like to take a crack at implementing this? It should be roughly two lines of code, so if you're interested in trying your hand at parser dev, it's a good first issue.

If not, I can do it. But wanted to offer first. :slightly_smiling_face:

**Comment by Jacob-Lockwood** [comment]
I could take this, I’m making a programming language myself so working with the internals of Civet could be nice. I can do it this week

**Comment by Jacob-Lockwood** [comment]
Sorry I took a look and couldn't figure it out and don't feel that committed to this so dropping this
