### ISSUE TITLE
Layout inconsistency in if/else expressions

### ISSUE THREAD

**Issue by gwhitney** [DanielXMoore/Civet#1040]
Once upon a time I wrote
```
check :=
   if 2+2 is 7 then 'yes'
   else 'no'
```
and got `'no'` and all was happy. Then I realized I had more to check, and changed it to
```
checks :=
   for j of [0..7]
      if 2+2 is j then 'yes'
      else 'no'
```
and Civet generated code that is a JavaScript syntax error, namely
```
const checks =
   (()=>{const results=[];for (let i = 0; i <= 5; ++i) {
      const j = i;
      if (2+2 === j) results.push('yes');;
      else results.push('no')
   }return results})()
```
(that double semicolon seems to be the killer; if I paste into a JavaScript playground and remove one, all seems well).
Removing `then` and putting `'yes'` on its own line restores the functionality, but still there seems to be an inconsistency here.

**Comment by STRd6** [comment]
Thanks for the report, definitely a bug!
