### ISSUE TITLE
Tooltip error with `if const`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1053]
Minimum reproducer: https://github.com/bbrk24/Civet-LSP-Tooltip-Bug

```civet
if signal := signals.get funcName
```

If I mouse over the first three characters of `signals`, I get the tooltip for the generated ref. If I mouse over the right half is `signals`, or over `get` or `funcName`, I get no tooltip at all.

**Comment by STRd6** [comment]
Should be fixed in LSP 0.3.13

**Comment by bbrk24** [comment]
Just updated my vs code extension, and now I'm not getting any tooltips on that line, not even `signal` (which was working before).

**Comment by STRd6** [comment]
![image](https://github.com/DanielXMoore/Civet/assets/18894/b8b99d8e-6f47-48d4-9092-7cca4e8ec3c7)

It worked for me on this minimal repro, does it work for you with this code?

**Comment by bbrk24** [comment]
Weird, it does work in my MWE repo, but not in context in my full code. I'll try to isolate the problem and file another issue if need be.
