### ISSUE TITLE
`async for` and `for await` don't compose

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1058]
This code attempts to call a function named `async`:
```civet
x :=
  async for await el of arr
    await el.thing()
```

**Comment by bbrk24** [comment]
Actually, it looks like even `async do` is broken:
![image](https://github.com/DanielXMoore/Civet/assets/25109429/e052286a-4c8c-4a8f-bf41-f85d51217882)

**Comment by STRd6** [comment]
Thanks for raising this. We hadn't considered `async for/do/...` but it does seem natural for the `async` to cancel out the implicit `await` when assigning to the result.

**Comment by bbrk24** [comment]
That `async do` screenshot I posted is from the reference on the website. The documentation says it should work, and then immediately demonstrates that it doesn't.

**Comment by STRd6** [comment]
Hmm, then maybe it used to work but just wasn't in our unit tests and got broken at some point. It might be easy to fix, I'll take a look.

**Comment by edemaine** [comment]
Curious. The second example in https://civet.dev/reference#async-do-blocks seems to be working correctly.
