### ISSUE TITLE
Inconsistency of pipe assignment with unspaced prefix word operator and optional-chained method

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1065]
Apologies for the long title, it's the best way I could think to describe this.

This compiles as expected:
```js
foo.bar |>= not?.baz()
// vvv
foo.bar = !foo.bar?.baz()
```
This is a ParseError:
```js
foo.bar |>= await?.baz()
```
And these invent new identifiers:
```js
foo.bar |>= void?.baz()
// vvv
foo.bar = voidfoo.bar?.baz()
```
```js
foo.bar |>= typeof?.baz()
// vvv
foo.bar = typeoffoo.bar?.baz()
```

(Of the four, `await` is the only one that does not generate the expected compilation when a space is inserted before the `?`.)

**Comment by edemaine** [comment]
Another bad example is

```coffee
void&
↓↓↓
$ => void$
```

We need to add a space after unary prefix operators if there isn't one (or forbid some of these).

**Comment by STRd6** [comment]
I think always ensuring a space after the non-symbol unary prefix operators should fix this and is probably pretty easy.
