### ISSUE TITLE
Saving file causes LSP to shit the bed

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1094]
![image](https://github.com/DanielXMoore/Civet/assets/25109429/29566ab9-c0aa-4dc9-b18f-f3143032e7e1)

![image](https://github.com/DanielXMoore/Civet/assets/25109429/40cf9318-34a2-4e6f-b313-c64677ff9b4b)

![image](https://github.com/DanielXMoore/Civet/assets/25109429/da699c0c-551a-4caf-8790-30a5a922a402)

I have no idea where to begin with this one. Restarting the LSP only fixes it until I save again.

**Comment by edemaine** [comment]
Can you post a repo where this happens consistently?

**Comment by bbrk24** [comment]
This also causes a more severe version of #825 -- `document.que` autocompletes to `document.this.querySelector`.

**Comment by bbrk24** [comment]
In the past, DOM APIs would still have the correct types and tooltips (or, as correct as they could be without arrays). However, today I got this:
![image](https://github.com/DanielXMoore/Civet/assets/25109429/e75cd3bd-82ca-4a83-9009-60762435e660)

**Comment by bbrk24** [comment]
Saving a file isn't the only trigger. If "jump to definition" opens one of the built-in lib.\*.d.ts files, that can also trigger this.

**Comment by bbrk24** [comment]
Simply having a lib.\*.d.ts file open in another tab and performing an edit can trigger this. This is ridiculous.

**Comment by bbrk24** [comment]
Here's the Language Server output, if that helps. It doesn't seem to suggest anything out of the ordinary:
<details>
<summary>Civet LSP Output</summary>
<pre>Init /home/bbrk24/workspace/NewSolitaire/
open file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
Spawning language server for project path:  file:///home/bbrk24/workspace/NewSolitaire/
CIVET VSCODE PLUGIN 0.3.15
TYPESCRIPT 5.2.2
PARSED TSCONFIG
 {
  options: {
    lib: [ 'lib.dom.d.ts', 'lib.es2022.d.ts' ],
    target: 9,
    strict: true,
    configFilePath: '/home/bbrk24/workspace/NewSolitaire/tsconfig.json',
    rootDir: '/home/bbrk24/workspace/NewSolitaire/',
    allowNonTsExtensions: true,
    allowJs: true,
    jsx: 1
  },
  watchOptions: undefined,
  fileNames: [
    '/home/bbrk24/workspace/NewSolitaire/dist/Card.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/Engine.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/GameBoard.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/WeakArray.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/fisherYatesShuffle.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/index.js',
    '/home/bbrk24/workspace/NewSolitaire/dist/interfaces.js'
  ],
  projectReferences: undefined,
  typeAcquisition: { enable: false, include: [], exclude: [] },
  raw: {
    compilerOptions: { lib: [Array], target: 'ES2022', strict: true },
    compileOnSave: false
  },
  errors: [],
  wildcardDirectories: { '/home/bbrk24/workspace/NewSolitaire': 1 },
  compileOnSave: false
} 


LOADED PROJECT CIVET 0.7.8: file:/home/bbrk24/workspace/NewSolitaire/@danielx/civet 


executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics  810.32ms
  service.getSemanticDiagnostics  196.20ms
service.getSuggestionDiagnostics    2.65ms
No Civet config found
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics  118.26ms
  service.getSemanticDiagnostics  186.51ms
service.getSuggestionDiagnostics    3.68ms
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics   10.77ms
  service.getSemanticDiagnostics  121.41ms
service.getSuggestionDiagnostics    1.43ms
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics    9.53ms
  service.getSemanticDiagnostics  128.81ms
service.getSuggestionDiagnostics    1.74ms
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics    7.43ms
  service.getSemanticDiagnostics   73.03ms
service.getSuggestionDiagnostics    2.26ms
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics    8.98ms
  service.getSemanticDiagnostics  111.10ms
service.getSuggestionDiagnostics    3.22ms
onDidChangeContent file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics   11.34ms
  service.getSemanticDiagnostics   77.82ms
service.getSuggestionDiagnostics   10.13ms
open file:///home/bbrk24/.vscode-server/extensions/danielx.civet-0.3.15/dist/lib/lib.dom.d.ts
onDidChangeContent file:///home/bbrk24/.vscode-server/extensions/danielx.civet-0.3.15/dist/lib/lib.dom.d.ts
close file:///home/bbrk24/.vscode-server/extensions/danielx.civet-0.3.15/dist/lib/lib.dom.d.ts
executeQueue 1
Updating diagnostics for doc: file:///home/bbrk24/.vscode-server/extensions/danielx.civet-0.3.15/dist/lib/lib.dom.d.ts
 service.getSyntacticDiagnostics  303.10ms
  service.getSemanticDiagnostics  664.54ms
service.getSuggestionDiagnostics   54.14ms
Updating diagnostics for doc: file:///home/bbrk24/workspace/NewSolitaire/src/index.civet
 service.getSyntacticDiagnostics    0.38ms
  service.getSemanticDiagnostics   79.50ms
service.getSuggestionDiagnostics    1.48ms</pre>
</details>

No idea why it says TS 5.2.2, given that my package.json has
```json
  "dependencies": {
    "@danielx/civet": "~0.7.8",
    "typescript": "~5.4.5"
  }
```
`npm ls` confirms I have 5.4:
```
$ npm ls typescript
NewSolitaire@ /home/bbrk24/workspace/NewSolitaire
├─┬ @danielx/civet@0.7.8
│ └── typescript@5.4.5 deduped
└── typescript@5.4.5
```

**Comment by bbrk24** [comment]
I'm now experiencing a limited form of this that only complains about new properties:
![image](https://github.com/user-attachments/assets/c2ef43e5-8418-432c-834b-a810fdcfc21e)
![image](https://github.com/user-attachments/assets/399abf31-c9c9-4675-8f45-827f64e5cfad)

This project's tsconfig, for reference:
```json
{
    "compilerOptions": {
        "strict": true,
        "lib": ["ES2023", "ESNext.Regexp"],
        "target": "ESNext",
        "module": "ES2022"
    }
}
```

**Comment by bbrk24** [comment]
Some more information I realized this morning: Even though it usually only affects core JS types like `Array` and `Error`, not DOM APIs, this only ever happens to its fullest extent in projects where I have `"lib": ["DOM", ...]` in my tsconfig. Node-only projects, like the one I mentioned in the previous comment, only ever complain about things that were added in relatively newer versions of JavaScript.

**Comment by bbrk24** [comment]
As best as I can tell, this is no longer an issue in extension version 0.3.21.
