### ISSUE TITLE
Playground is not working in Safari

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#11]
**Safari 16.0**
**macOS 12.6**

It works in Chrome on the same computer.

There's an error in the console, it may be related.
`SyntaxError: Invalid regular expression: invalid group specifier name`

<img width="1082" alt="playground" src="https://user-images.githubusercontent.com/11703903/201488315-af30336b-91c3-4adf-b7c1-c764948c6990.png">

**Comment by STRd6** [comment]
I think it has to do with Safari not supporting lookbehind assertions. I've published a possible fix, let me know how it goes!

**Comment by zolomatok** [comment]
Works purr-fectly, super quick response, thank you for your work!
