### ISSUE TITLE
`x.-1` on left-hand side

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#1102]
`x.-1 = 5` compiles to invalid `x.at(-1) = 5`. We probably want to compile to `x[x.length-1] = 5` (with appropriate ref if needed).

**Comment by STRd6** [comment]
Would always compiling to `x[x.length-1]` be a reasonable approach?

**Comment by edemaine** [comment]
Hmm, maybe that would be better overall, yeah. I think there are several interfaces (e.g. querySelectorAll) that have length but not at, so this would be an improvement. 

(I assume you also mean to add ref when necessary.)
