### ISSUE TITLE
no break for switch

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#1118]
I would expect a `break` in this code at the end of the `when 0` block

```coffee
fn := (x : number) =>
  switch x
    when 0
      num := 10
      switch num
        <? "number"
          return 0
    when 1
      return 1
```

but it's [not there](https://civet.dev/playground?code=Zm4gOj0gKHggOiBudW1iZXIpID0%2BCiAgc3dpdGNoIHgKICAgIHdoZW4gMAogICAgICBudW0gOj0gMTAKICAgICAgc3dpdGNoIG51bQogICAgICAgIDw%2FICJudW1iZXIiCiAgICAgICAgICByZXR1cm4gMAogICAgd2hlbiAxCiAgICAgIHJldHVybiAx) in the output.

It's different when the same thing is not inside the function

```coffee
x := 1

switch x
  when 0
    num := 10
    switch num
      <? "number"
        return 0
  when 1
    return 1
```

Now the [break is included](https://civet.dev/playground?code=eCA6PSAxCgpzd2l0Y2ggeAogIHdoZW4gMAogICAgbnVtIDo9IDEwCiAgICBzd2l0Y2ggbnVtCiAgICAgIDw%2FICJudW1iZXIiCiAgICAgICAgcmV0dXJuIDAKICB3aGVuIDEKICAgIHJldHVybiAxCg%3D%3D) (of course this code is not valid because of the top level `return` but yeah..)

Currently using [noFallthroughCasesInSwitch](https://www.typescriptlang.org/tsconfig#noFallthroughCasesInSwitch) in tsconfig.json to spot these errors.

**Comment by bbrk24** [comment]
It's omitting the `break` because it's the last statement of the function. If I add a call to an imaginary function `g()`:
```
fn := (x : number) =>
  switch x
    when 0
      num := 10
      switch num
        <? "number"
          return 0
    when 1
      return 1
  g()
```
suddenly the `break` is there. Heck, the following statement doesn't even have to be substantial -- if I replace `g()` with `;` in the above code it still emits the `break`.

**Comment by edemaine** [comment]
Right, it's clearly a bug in our code to detect whether a break is necessary (which we added to make eslint happier, IIRC).

**Comment by bbrk24** [comment]
No, surprisingly -- if you add an `else` block that doesn't return, it still doesn't `break`.
