### ISSUE TITLE
Cannot use `@#` for `this.length` in `while` condition

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1125]
```civet
while @#
  yield @draw()
```
becomes:
```js
while (this) {
  this.length(yield this.draw());
}
```
Every attempted workaround that doesn't respell `@#` to `@length` creates a ParseError.

**Comment by edemaine** [comment]
The correct notation for this for now is:
```coffee
while @.#
  yield @draw()
```
or
```coffee
while #
  yield @draw()
```

Meanwhile, I believe your example is parsing like this:
```coffee
while @
  #
    yield @draw()
```

It would probably be more intuitive to require some whitespace between the `while` condition and body... at least in some cases like when the condition doesn't end with a `)`.

Also, perhaps it's time to add support for `array#` (without dot) → `array.length` and `@#` (without dot) → `this.length`. The latter in particular is more consistent with `@prop` = `@.prop`.
