### ISSUE TITLE
try...else

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#1134]
Python allows an `else` block for `try`, which is convenient; see [one recent example](https://github.com/DanielXMoore/Civet/blob/8dd331d0cd4347c405d71893aefaf5e10590ffa2/source/cli.civet#L330-L335). I propose:

```js
try
  ...
catch e
  ...
else
  ...
↓↓↓
let caught: true | undefined
try {
  ...
} catch (e) {
  ...
  caught = true
}
if (!caught) {
  ...
}
```

Special case with missing `catch` block:

```js
try
  ...
else
  ...
↓↓↓
let caught: true | undefined
try {
  ...
} catch (e) {
  caught = true
}
if (!caught) {
  ...
}
```

**Comment by STRd6** [comment]
How does it interact with `finally`?

**Comment by edemaine** [comment]
Good question! For semantics, I think it's natural for `finally` to happen last, given the name. I think this needs to be transpiled into two `try`s:

```coffee
try
  ...
catch e
  ...
else
  ...
finally
  ...
↓↓↓
let caught: true | undefined
try {
  try {
    ...
  } catch (e) {
    caught = true
    ...
  }
  if (!caught) {
    ...
  }
} finally {
  ...
}
```

We could also try to support either semantics depending on the order of the `else` or `finally` block. Not sure whether this is useful:

```coffee
try
  ...
catch e
  ...
finally
  ...
else
  ...
↓↓↓
let caught: true | undefined
try {
  ...
} catch (e) {
  caught = true
  ...
} finally {
  ...
}
if (!caught) {
  ...
}
```

**Comment by bbrk24** [comment]
I fail to see a meaningful difference between

```
try
  foo()
catch
  bar()
else
  baz()
```

and

```
try
  foo()
  baz()
catch
  bar()
```

Why is try-catch-else needed?

**Comment by edemaine** [comment]
As mentioned in #1133, there's a key difference: `baz()` doesn't get wrapped in a `try...catch` in the `else` case. In the [callback-driven code I linked](https://github.com/DanielXMoore/Civet/blob/8dd331d0cd4347c405d71893aefaf5e10590ffa2/source/cli.civet#L330-L335), it's crucial that we don't wrap the callback code (which is plausibly the rest of the repl) in a `try`. More generally, I think it's useful to know that either `bar()` or `baz()` will execute (as in `catch/else`), and never part of `baz()` followed by `bar()` (as in your proposed replacemenmt).

**Comment by STRd6** [comment]
I think the `else` code should go inside the `finally` wrapped with a `try/catch` so that it executes before the other finally code and can rethrow any exception from the else if the finally code hasn't thrown.

**Comment by edemaine** [comment]
Personally I'd rather avoid rethrowing exceptions if we can. It can make debugging more difficult. Are you worried about the overhead of two `try` wrappers? I admit I don't know how large that is.

**Comment by STRd6** [comment]
Mainly to keep it consistent with the existing `catch` and `finally` behavior. If an exception is thrown in a `catch` `finally` executes and that exception continues to be thrown. If `finally` additionally raises an exception then the newly raised exception is thrown.

```
try
  // try block
catch e
  // catch block
else
  // else block
finally
  // finally block
↓↓↓
let caught: true | undefined
try {
  // try block
} catch {
  // catch block
  caught = true // Set caught at bottom so if catch block throws else is not entered
} finally {
  let thrown;
  if (!caught) {
    try {
      // else block
    } catch (e) {
      thrown = e
    }
  }
  // finally block
  if (thrown) throw thrown
}
```

**Comment by bbrk24** [comment]
> `if (thrown) throw thrown`

Unfortunately, `throw undefined` is perfectly valid and well-behaved JavaScript. There's a reason caught errors are `unknown` and not `Error` in TS.

**Comment by STRd6** [comment]
> > `if (thrown) throw thrown`
> 
> Unfortunately, `throw undefined` is perfectly valid and well-behaved JavaScript. There's a reason caught errors are `unknown` and not `Error` in TS.

Good catch!

**Comment by edemaine** [comment]
Won't the first proposed compilation in <https://github.com/DanielXMoore/Civet/issues/1134#issuecomment-2030593169> (with two `try` wrappers) behave the same? The outer wrapping `finally` block will always run, and if the `else` block throws something, it will be thrown (after fithe `finally` block executes).

**Comment by STRd6** [comment]
> Won't the first proposed compilation in [#1134 (comment)](https://github.com/DanielXMoore/Civet/issues/1134#issuecomment-2030593169) (with two `try` wrappers) have the desired semantics? The outer wrapping `finally` block will always run, and if the `else` block throws something, it will be thrown (after fithe `finally` block executes).

Yes, on further inspection they appear to be equivalent and your version is even simpler. I now prefer https://github.com/DanielXMoore/Civet/issues/1134#issuecomment-2030593169 as well.
