### ISSUE TITLE
ts-expect-error before assignment from for expression

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1135]
In this code, it's impossible to place the `@ts-expect-error` directive correctly:

```
declare let t: [number, number, number]

// @ts-expect-error I can't prove this has three elements but it does
t = for i of [1..3]
  Math.sqrt i
```

The current spelling complains about the type mismatch *and* about an unused expect-error directive, as it compiles to

```ts
declare let t: [number, number, number]

// @ts-expect-error I can't prove this has three elements but it does
const results=[];for (let i1 = 1; i1 <= 3; ++i1) {
  const i = i1;
  results.push(Math.sqrt(i))
};t = results
```

Current workaround:

```
t = (for i of [1..3]
  Math.sqrt i
) as any
```

**Comment by edemaine** [comment]
This seems like the same issue as #1113. Could you move your example to there?

**Comment by bbrk24** [comment]
I think it's different. That issue can plausibly be fixed by removing a newline from the generated code, and emitting `for (const key in obj){const value = obj[key];`. This issue requires transposing the comment across the entire body of the for loop, which may be arbitrarily long and isn't necessarily collapsible (e.g. if it contains line comments or a multi-line template string).

**Comment by edemaine** [comment]
Ah, right, sorry.

**Comment by edemaine** [comment]
Do you have a proposal for how to fix this? I don't think we can use `t` in place of `results` here because `t` might change in the loop and then semantics change.

One better workaround I think:
```js
sqrts := for i of [1..3]
  Math.sqrt i
// @ts-expect-error I can't prove this has three elements but it does
t = sqrts
```

It would be nice if this worked, but `|>` currently can't follow a loop like this:
```js
t = for i of [1..3]
  Math.sqrt i
|> as [number, number, number]
```

Or perhaps this would be even cleaner, but also doesn't parse as intended:
```js
t = for i of [1..3]
  Math.sqrt i
as [number, number, number]
```

Back to comments, one thing I would find somewhat natural to write is
```js
t = // @ts-expect-error
  for i of [1..3]
    Math.sqrt i
```
Unfortunately `@ts-expect-error` must come on the line before, which seems hard to guarantee...

**Comment by bbrk24** [comment]
> It would be nice if this worked, but `|>` currently can't follow a loop like this:
> 
> ```js
> t = for i of [1..3]
>   Math.sqrt i
> |> as [number, number, number
> ```

@edemaine I think this should be considered a bug, given that it works fine if you add an extra newline:
```ts
t =
for i of [1..3]
  Math.sqrt i
|> as [number, number, number]
// vvv
t = (() => {
  const results = [];
  for (let i1 = 1; i1 <= 3; ++i1) {
    const i = i1;
    results.push(Math.sqrt(i));
  }
  return results;
})() as [number, number, number];
```

**Comment by edemaine** [comment]
Now that the following works, perhaps we can consider this issue done?

```js
t = for i of [1..3]
  Math.sqrt i
|> as [number, number, number]
```

`as` type casting seems better than `//ts-ignore`

We could also try to support the version without `|>`

**Comment by bbrk24** [comment]
I agree. If it really can't be done with a simple `as`, you can always use `as!` or `as any`.
