### ISSUE TITLE
Anonymous class bug

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#114]
Parses:

```coffee
class
  static a = 5
```

Doesn't parse:

```coffee
class
  @a = 5
```

```coffee
class
  constructor(x);
```

These examples work if the class has a name, as in `class X`.

**Comment by STRd6** [comment]
The second example doesn't have a constructor body. But the first example is definitely a bug.

**Comment by edemaine** [comment]
```coffee
class X
  constructor(x);
```

gets treated as an empty body, so it's specific to the class being anonymous.

Separately, I think constructors (and ideally all class methods) shouldn't need bodies, but that's another issue.
