### ISSUE TITLE
`::#` doesn't work in type position

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1160]
With coffeePrototype, `T::#` works as an expression but not a type.

**Comment by edemaine** [comment]
Does `T.prototype.length` actually make sense? `T.foo` is a namespace dereference, so I don't think there's any sense of prototype chain.

**Comment by bbrk24** [comment]
In type position, `T::length` currently compiles to `T["length"]`.

**Comment by edemaine** [comment]
Oops, right, I see.
