### ISSUE TITLE
`for own` doesn't work inside `comptime`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1185]
Minimal reproducer:
```civet
console.log comptime
  for own x in { foo: 1 }
    ;
```

**Comment by edemaine** [comment]
Ah, good catch. This is a general issue with all "helpers" in generated code. I think we could fix this before solving the general "copy things out of scope into comptime block" problem: we can look for refs that match refs in the `helpers` block and copy them.
