### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#12]
More of a question than an issue.
What's the import situation going to be (is?) with Civet?
Will we be able to import other .civet files as ES6 modules like in typescript?
Or is it going to be like in Coffee where you can import other .coffee files as Node modules, but not as ES6 modules?

**Comment by STRd6** [comment]
Currently you can import Civet files as commonjs or ESModules. Civet itself does nothing to rewrite imports or exports and leaves that to other tools.

If your project is using ESM you can use `node --loader @danielx/civet/esm` and civet files will work fine. If you're using commonjs then `node --require @danielx/civet/register` should work for loading civet files as commonjs.

There's probably some way to configure ts-node or babel to mix and match but I haven't gone too far into that. Generally a single project will use a singe format and when publishing will use esbuild or another tool to convert to the appropriate distribution formats.

For my own development I've been doing something like this: https://github.com/DanielXMoore/Civet#testing using Civet files as ESM.

Let me know if you run into any issues!

**Comment by edemaine** [comment]
@STRd6 Perhaps you'd like to enable the Discussions GitHub feature for questions like this? Up to you of course!

**Comment by zolomatok** [comment]
@STRd6 awesome, thank you so much!
@edemaine yeah I felt bad for opening so many "issues", I looked around maybe I can tag them as questions, but I don't seem to be able to assign labels myself. Maybe only contributors can?

**Comment by STRd6** [comment]
Discussions is up: https://github.com/DanielXMoore/Civet/discussions/13

Go nuts!
