### ISSUE TITLE
`guard`-`else`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1215]
Now that we have `isExit` for other reasons, Swift-style `guard` seems implementable. At first glance, it seems identical to `unless`:
```js
guard CONDITION else {
  STATEMENTS
}
// vvv
if (!CONDITION) {
  STATEMENTS
}
```
However, there are two key differences:
1. If the condition creates any bindings (such as `guard x? := getX() else { ... }`), the bindings are only available *outside* the `else` block.
2. `STATEMENTS` must be an "exit" of some sort, in order for `1` to be possible.

The primary use case is to prevent "pyramids of doom" when there are many bindings to be done:
```
if x? := getX()
  if y? := getY()
    if z? := getZ()
      setPoint x, y, z
// vvv
guard x? := getX() else return
guard y? := getY() else return
guard z? := getZ() else return
setPoint x, y, z
```

**Comment by bbrk24** [comment]
Supersedes #756 I suppose

**Comment by STRd6** [comment]
A couple thoughts:

I'm reluctant to add any more reserved words like `guard`. Would `unless x? := getX() else return` be an acceptable spelling of this feature?

Maybe upgrading pipes to better handle piping to `return`/`throw` and allowing something similar to declaration conditions could help with this. https://github.com/DanielXMoore/Civet/issues/897#issuecomment-2002531328

```
x := getX() !> return
---
let ref = getX(); if(!ref) return ref; const x = ref;
```

Possible conditional pipe options: `?>`, `!>`, `?|>`, `!|>` maybe something else?

**Comment by bbrk24** [comment]
unless-else reads like a double-negative, but otherwise I'd be fine with it.
