### ISSUE TITLE
Ampersand bugs

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#1231]
## if/then

```js
e.children = e.children.map
  if & is e.block then block else &
// ↓↓↓
e.children = e.children.map(($) =>
  $ === e.block ? block : ($1) => $1
);
```

I expected this to be a single function, but each `&` gets treated as its own function wrapper. By contrast, `?:` works fine:

```js
e.children = e.children.map(($) =>
  $ === e.block ? block : $
);
```

## Assignment

The [docs](https://civet.dev/reference#single-argument-function-shorthand) say that we don't lift beyond an assignment, but I find this not to be the case:

```js
f = & + 1
// ↓↓↓
($) => (f = $ + 1);
```

**Comment by bbrk24** [comment]
I ran into the first one the other day, but in a slightly different way so I didn't file an issue about it:

```civet
arr.map
  if &.x
    foo
  else if &.y
    bar
  else
    baz
```
```js
arr.map(($) =>
  $.x
    ? foo
    : ($1) => {
        if ($1.y) {
          return bar;
        } else {
          return baz;
        }
      }
);
```
