### ISSUE TITLE
`.#x` shorthand for private properties

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1234]
This is a compile error:
```civet
foo ||> .#x = 1
```
The `.` is interpreted as the partial placeholder rather than member access.
Without the dot, it is not interpreted in the intended way:
```js
foo ||> #x = 1
// vvv
(this.#x = 1)(foo), foo
```

**Comment by edemaine** [comment]
It looks like `.#x` just generally doesn't work as a private member access helper. Should be an easy fix.
