### ISSUE TITLE
Attempted pattern matching ternary

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1236]
```civet
undo := => engine = Engine.fromJSON json if json? := history.pop()
```
```js
const undo = () =>(const json? = history.pop()? engine = Engine.fromJSON(json):void 0)
```
Workaround: put the function body on the next line
```civet
undo := =>
  engine = Engine.fromJSON json if json? := history.pop()
```

**Comment by edemaine** [comment]
A workaround for now:

```coffee
undo := =>
  engine = Engine.fromJSON json if json? := history.pop()
```

So this is probably specific to the "don't wrap fat arrow in braces if it's a one-line expression" rule.

**Comment by STRd6** [comment]
Looks like this works now with the recent changes: https://civet.dev/playground?code=dW5kbyA6PSA9PiBlbmdpbmUgPSBFbmdpbmUuZnJvbUpTT04ganNvbiBpZiBqc29uPyA6PSBoaXN0b3J5LnBvcCgpCg%3D%3D

**Comment by edemaine** [comment]
Indeed! Probably this commit: https://github.com/DanielXMoore/Civet/pull/1441/commits/bc49fe964b2c8cca4a35e909c7e5a8a0ae2c3e84 which makes fat arrows treat postfix `if` like an expressionized statement.
