### ISSUE TITLE
import extension gets rewritten but wrong

### ISSUE THREAD

**Issue by iacore** [DanielXMoore/Civet#1290]
`civet -h` says

> By default, .civet imports get rewritten to use the output extension.

i don't see this happening.

```
❯ civet -c -o .ts init.civet
❯ head init.civet
import './gopher.ts'
❯ head init.ts
import './gopher.js'
```

**Comment by edemaine** [comment]
Your example is a .ts import, not a .civet import. That's getting rewritten by a different rule; see https://civet.dev/config#import-options
