### ISSUE TITLE
Nested type annotation fails to parse

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#1322]
When adding a nested type annotation the parser fails to pick it up:

```civet
function f(v: T):
  O
```

This is useful in cases where there are more complex types and having the additional newline makes it easier to see what's going on.

```civet
function O<T>(v: T):
  T extends boolean ? ObservableBoolean<T> :
  T extends number ? ObservableNumber<T> :
  ObservableValue<T>
```

**Comment by edemaine** [comment]
How do you imagine distinguishing the indented type from the indented body of the function? I believe this is ambiguous in general...

As a workaround, you can [use parentheses around the type](https://civet.dev/playground?code=ZnVuY3Rpb24gTzxUPih2OiBUKTogKAogIFQgZXh0ZW5kcyBib29sZWFuID8gT2JzZXJ2YWJsZUJvb2xlYW48VD4gOgogIFQgZXh0ZW5kcyBudW1iZXIgPyBPYnNlcnZhYmxlTnVtYmVyPFQ%2BIDoKICBPYnNlcnZhYmxlVmFsdWU8VD4KKQ%3D%3D) for now.

Here's another fun way to write it (but still requires parens):

```ts
function O<T>(v: T): (
  if T extends boolean
    ObservableBoolean<T>
  else if T extends number
    ObservableNumber<T>
  else
    ObservableValue<T>
)
```

**Comment by STRd6** [comment]
The colon makes this mostly unambiguous. Here's something that works already:

```civet
function O<T>(v: T): T extends boolean ? ObservableBoolean<T> :
  T extends number ? ObservableNumber<T> :
  ObservableValue<T>

  v

```

https://civet.dev/playground?code=ZnVuY3Rpb24gTzxUPih2OiBUKTogVCBleHRlbmRzIGJvb2xlYW4gPyBPYnNlcnZhYmxlQm9vbGVhbjxUPiA6CiAgVCBleHRlbmRzIG51bWJlciA%2FIE9ic2VydmFibGVOdW1iZXI8VD4gOgogIE9ic2VydmFibGVWYWx1ZTxUPgoKICB2Cgo%3D
