### ISSUE TITLE
VSCode Intellisense not working

### ISSUE THREAD

**Issue by RReivax** [DanielXMoore/Civet#1325]
I love the project but I can't get it to work correctly in VSCode.

Civet extension installed : v0.3.17
VSCode: 1.91.1 (almost fresh install)

```civet
type Toto = 
    name: string,
    age: number

const toto: Toto =
    name: 'tutu'
    age: 42

toto.
```

Expecting `name` and `age` to appear in the auto-completion list, but nothing happens.
When writing `toto.age`, it does recognize it is a number.

**Comment by edemaine** [comment]
I believe autocomplete works after you enter a character after the `.`. With just the dot, it's a parse error, so intellisense doesn't work. It's on our to-do list to fix this, but it's tricky.

**Comment by RReivax** [comment]
You're right! Thank you. Closing this
