### ISSUE TITLE
Double inlay hints for .ts files

### ISSUE THREAD

**Issue by ricardobeat** [DanielXMoore/Civet#1326]
Type: <b>Bug</b>

Edit a normal .ts file with the extension enabled, all issues and type hints are shown duplicated (once with 'ts' source, once with 'typescript')

Extension version: 0.3.17
VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by STRd6** [comment]
Is the builtin TS plugin disabled? We recommend disabling it.
