### ISSUE TITLE
Optional `@?x` fails to parse

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#1327]
```civet
@?trigger "changed"
```

Currently fails with a parse error but should parse as

```
this?.trigger("changed")
```

In strict mode this can be null or undefined.

**Comment by edemaine** [comment]
Oddly, CoffeeScript [treats `@?trigger "changed"` like `@? trigger "changed"`](https://coffeescript.org/#try:%40%3Ftrigger%20%22changed%22%0A%40%3F%20trigger%20%22changed%22), i.e., as two function calls.  This is pretty weird though.

This is related to a question I asked a while back on Discord: should `x?y` be shorthand for `x?.y`, just like how `x?(y)` is shorthand for `x?.(y)` and `x?[y]` is shorthand for `x?.[y]`?  I think making `@?x` shorthand for `this?.x` is less controversial, though, because `@x` is already shorthand for `this.x` which includes the dot.

**Comment by vendethiel** [comment]
> Oddly, CoffeeScript [treats `@?trigger "changed"` like `@? trigger "changed"`](https://coffeescript.org/#try:%40%3Ftrigger%20%22changed%22%0A%40%3F%20trigger%20%22changed%22), i.e., as two function calls. This is pretty weird though.

It's self-consistent. `@?foo` is `this?.(foo)` in CoffeeScript, not `this?.foo()` (just like `a?b` is `a?(b)`, not `a?.b`). [Coffee considers `@` to be callable](https://github.com/jashkenas/coffeescript/blob/817c39a13065a900725943c33a79252a69d779e2/src/lexer.coffee#L1452) (which, well, is fair enough.)

**Comment by STRd6** [comment]
Hmm, we may want to go for consistency with CoffeeScript then, or at least note it and have a compat flag.

**Comment by vendethiel** [comment]
I'd say CoffeeScript is not consistent with itself here: the only call introducers are supposed to be whitespace and `(`.

Coco and LiveScript did change this (`a?b` is `a?.b`), though I'm not 100% sure it was meant to change the meaning of `a?b` then (Coco 0.4.2: "Enabled ADI on `?.`", but [the commit adds a test without removing or changing another one]
(https://github.com/satyr/coco/commit/d1aaa99f1600b9190b278003c326e80103c508ab))

**Comment by edemaine** [comment]
TIL CoffeeScript [treats `f?g` like `f? g`](https://coffeescript.org/#try:f%3Fg%0Af%3F%20g) also. So I agree it's somewhat consistent on this point, but it doesn't match my own intuitive definition of implicit calls which would have matched @vendethiel's:

> the only call introducers are supposed to be whitespace and `(`.

However, CoffeeScript's [actual definition](https://coffeescript.org/#language) is vague:

> You don’t need to use parentheses to invoke a function if you’re passing arguments. The implicit call wraps forward to the end of the line or block expression.

I don't see [any CoffeeScript tests about this](https://github.com/jashkenas/coffeescript/blob/main/test/function_invocation.coffee), nor could I find an issue.

But when we define a meaning for `@?foo` and/or `foo?bar`, I agree we should probably add a `coffeeCompat` flag, even though [I couldn't find any real-world usage](https://github.com/search?q=lang%3ACoffeeScript+%2F%5C%3F%5Cw%2F&type=code).
