### ISSUE TITLE
ternary requires space

### ISSUE THREAD

**Issue by JayXon** [DanielXMoore/Civet#1335]
`1?2:3` is valid js, but does not parse as civet, I don't see this mentioned in https://civet.dev/comparison, so assuming this is a bug
https://civet.dev/playground?code=MT8yOjM%3D

**Comment by edemaine** [comment]
This is either a documentation bug or a compiler bug. 🙂 

We have been discussing recently whether to make `a?b` shorthand for `a?.b` (an extension of #1327). In fact, I was inclined to implement this very soon. But it would mean that `a?b:c` wouldn't be a valid ternary. Which do we want?

**Comment by edemaine** [comment]
Ah, fair, I think it's reasonable to require no spaces around the colon when there's no spaces around the question mark in a ternary, and this could probably be supported together with `a?b`.

**Comment by edemaine** [comment]
I've gone ahead and documented the current behavior. Supporting tight ternary `x?y:z` is still interesting, but I found it difficult to add in my first attempt (given the current parser, which wants to greedily match an expression before looking for ternary suffix `?...:...`).
