### ISSUE TITLE
Fat pipe (`||>`) does not play nice with typescript-eslint v8

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1339]
Evidence: bbrk24/Trilangle#142

> ```error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions```

**Comment by edemaine** [comment]
Hopefully this can be fixed upstream: https://github.com/eslint/eslint/issues/18758

**Comment by bbrk24** [comment]
None of the pipelines that are triggering this end up being used as expressions. They're all of the form
```civet
f()
  ||> .foo = 1
  ||> .bar = 2
  |> x.baz
```
where the pipeline is used as a statement and the last one is `|>` rather than `||>`. Would it be reasonable to special-case pipeline *statements* and emit `;` rather than `,`? I believe that would circumvent this issue.

**Comment by edemaine** [comment]
Maybe we can use `blockContainingStatement` 

> Would it be reasonable to special-case pipeline _statements_ and emit `;` rather than `,`? I believe that would circumvent this issue.

Yes. Maybe we can use `blockContainingStatement` to detect this situation.
