### ISSUE TITLE
I made Civet icons

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [DanielXMoore/Civet#1410]
I needed a Civet icon for my game engine, so I made one. Actually, I made two. You can use them however you like, if you want.

[civet.svg](https://github.com/user-attachments/assets/f93603b2-c5a4-4e18-b358-8a4cb3fa4242)
[civet-no-mane.svg](https://github.com/user-attachments/assets/24a0c63b-abb4-4aa0-920a-fe11c9dec17e)

![изображение](https://github.com/user-attachments/assets/7460b4f0-1eb4-438b-be44-b8c31708b1c2)

![изображение](https://github.com/user-attachments/assets/275e8fac-d569-442e-ae2d-92ffdc16ff6f)

**Comment by edemaine** [comment]
Thanks!! Perhaps we should use one of these for the VSCode file icon, instead of the cat?
