### ISSUE TITLE
Feature request: define globals in the compile function for to avoid autoVar-ing them

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [DanielXMoore/Civet#1411]
**Proposal:** Allow developers to add an array of global variable names called `globals` to `CompileOptions` and make `autoVar`, `autoLet` and `autoConst` not shadow the names listed there.

**Use cases:**

* Users write a function body in a game engine and cannot modify the function's descriptor. The function's body is then compiled on game export — function's arguments are lost due to `autoVar`.
  ```coffee
  # Wrapper: function (options?: Sausage)
    if not options
      options = getDefaultSausage() # `options` gets shadowed
  ```
* Civet code may reference and write global variables. For example, written to `window` or coming from a 3rd-party framework. In my engine, people oftentimes define games' global variables in separate top-level scripts so they are visible to all game entities' events.
  ```coffee
  # in a top-level script
  var sausageNumber = 0
  window.debugMode = true
  ```
  ```coffee
  # in a separately compiled script
  function resetAll
    sausageNumber = 0 # `sausageNumber` gets shadowed
    debugMode = false # `debugMode` is shadowed, too
  resetAll()
  ```

**Possible workarounds:**

* Using `window.`
* Compiling functions as whole and stripping away unneeded code
* Compiling whole projects as one big file (not possible in my case, plus goodbye incremental builds and caching)

**Comment by edemaine** [comment]
This seems reasonable to me; I can see lots of circumstances where we don't want to auto-declare certain variables, and `declare` would be annoying (and doesn't even work, as reported in #1412).

My only question is what the interface should be. `CompileOptions` is indeed one natural place. But should it be a `ParseOptions`, so that it's next to `autoVar`? Related, should it be possible to specify it via a `"civet"` directive? For example:

```js
"civet globals=sausageNumber,debugMode"
```

My guess is that the answer to both questions is "yes", but it would be helpful to have some confirmation.

**Comment by CosmoMyzrailGorynych** [comment]
Civet directive: most definitely yes. Also, globals should ideally be definable through CLI, too.

Putting `globals` in `ParseOptions` may be handy but aren't globals semantically about _emitting_ code, instead of _parsing_ it? 🥴

**Comment by bbrk24** [comment]
> Civet directive: most definitely yes. Also, globals should ideally be definable through CLI, too.

I believe civet directives can be defined with CLI flags, so the former implies the latter.

**Comment by edemaine** [comment]
> Putting `globals` in `ParseOptions` may be handy but aren't globals semantically about _emitting_ code, instead of _parsing_ it? 🥴

I think anything that affects the semantics of the program is fair game for `ParseOptions`.  `ParseOptions` are exactly what is specifiable with `"civet"` directives, so the choice seems clear now. Thanks for the input!
