### ISSUE TITLE
How about two way transpiling?

### ISSUE THREAD

**Issue by icetbr** [DanielXMoore/Civet#1452]
Even if for just a few features, like no open/close brackets. Then each developer could have a local configuration. 

Add a local linter configuration and this would end all styles wars once and for all. Maybe we could do a "lint with X" on file open, "lint with Y" on close automation. Or automate lint staged push/pull to have a mirror source folder with other styles.

**Comment by icetbr** [comment]
Wait, I just saw a ts2civet.

https://github.com/esthedebeste/ts2civet

**Comment by edemaine** [comment]
We've discussed round-tripping through Civet just for local development, especially just as a visual thing in the editor. It's going to be difficult to not change anything during that round trip, so may not be practical. But definitely an interesting direction...

ts2civet is in its infancy. I'm sure it could use more work if you're interested in working on it.
