### ISSUE TITLE
Pipe operator changes function call precedence

### ISSUE THREAD

**Issue by lukegustafson** [DanielXMoore/Civet#1457]
As of 0.8.0, 
```
[].map f(1|>g)
//becomes
[].map(f)(g(1));
```
I would expect it to be `[].map f(g(1));`
The pipe operator seems to be playing a role here, as `[].map f(g(1))` does what I'd expect.

**Comment by edemaine** [comment]
Thanks for the report! This should be fixed in 0.8.1. Let us know if you bump into any other bugs.
