### ISSUE TITLE
`&` lifting above function call when it's part of the function

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1458]
```ts
`a${&}b` c
// vvv
($) => `a${$}b`(c);
```

**Comment by edemaine** [comment]
The fundamental question here is whether `&` should lift above a function call when it's part of the function. Currently it does:
```js
& x -> $ => $(x)

**Comment by STRd6** [comment]
I think this is the correct behavior. Another example to illustrate:

```civet
items.forEach .add 1
// items.forEach(($) => $.add(1));
```
