### ISSUE TITLE
One-line `if` doesn't allow declarations

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#1464]
`if (x) y := 5` is [currently invalid](https://civet.dev/playground?code=aWYgKHgpIHkgOj0gNQ%3D%3D), along with other declarations like `if (x) const y = 5`, but I'm guessing it should be? It seems slightly useful in the context of implicit return from a function, e.g. `=> if (x) y := 5`.

For comparison, `if (x) function f() 5` is valid, though `function` is valid in both statement and expression contexts. But other statement-only things like `if (x) break` are valid.

**Comment by STRd6** [comment]
Yes, it probably should be valid there.

**Comment by edemaine** [comment]
Added a fix to #1466 (because without the other changes there, this would be buggy in terms of braces).
