### ISSUE TITLE
Assignment to symbols is allowed

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1510]
Why does this compile outside of a class body?
```civet
:foo = bar
```

**Comment by bbrk24** [comment]
Oh, I guess this makes a nonzero amount of sense for well-known symbols, like `:asyncIterator ??= Symbol 'Symbol.asyncIterator'` in a polyfill. But for the ones like this that compile to `Symbol.for` it's always an error so it shouldn't be allowed.

**Comment by edemaine** [comment]
I could be wrong, but I think Civet emits invalid JavaScript in a variety of contexts where the input is invalid. So I'm not sure we need to detect this at the transpilation level; we can leave it for detection downstream (by TypeScript, eslint, Node, etc.). Unless you think we should try to catch all JS errors ourselves?

**Comment by bbrk24** [comment]
Huh, I guess you're right ([example](https://civet.dev/playground?code=eCh5KSA9IHo%3D)). I hadn't noticed that before.
