### ISSUE TITLE
Unwrap the `Promise` wrapper in this case when typing `ret`

### ISSUE THREAD

**Issue by NWYLZW** [DanielXMoore/Civet#1515]
![image](https://github.com/user-attachments/assets/5085451d-edc4-43df-8fa4-52274fa20e02)

![image](https://github.com/user-attachments/assets/967d4c83-18a9-4b09-b3a3-afa69c23f1ab)

[`return.value`](https://civet.dev/reference#return-value)
![image](https://github.com/user-attachments/assets/34a6970b-3bd6-4dee-ac96-ec5b0dc03243)

[discord](https://discord.com/channels/933472021310996512/1051152886043775116/1299790848443158621)

**Comment by edemaine** [comment]
To fix the parse error, I think you want `result := return = await connection.sendRequest`. But the type for `ret` is still wrong (it's a `Promise` here).
