### ISSUE TITLE
Load-bearing semicolon after `|> await.all`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1525]
This compiles as expected:
```ts
await.all
    . async do
        f()
            |> await.all;
    . build
// vvv
await Promise.all([
  (async () => {
    {
      await Promise.all(f());
    }
  })(),
  build,
]);
```
Remove the semicolon, though, and the `await.all` starts grabbing arguments *even though it's in a pipeline*:
```ts
await.all
    . async do
        f()
            |> await.all
    . build
// vvv
(await Promise.all([build]))(
  await Promise.all([
    (async () => {
      {
        return f();
      }
    })(),
  ]),
);
```
If I split it up into `|> Promise.all` + `|> await` on separate lines, it behaves similarly:
```ts
await.all
    . async do
        f()
            |> Promise.all 
            |> await
    . build
// vvv
[await build](
  await Promise.all([
    (async () => {
      {
        return Promise.all(f());
      }
    })(),
  ]),
);
```
but if I put them on the same line, as in the following code snippet, it completely fails to parse:
```
await.all
    . async do
        f()
            |> Promise.all |> await
    . build
```
The ParseError points at EOF.

**Comment by edemaine** [comment]
I'm guessing this is a `__` that needs to be `NotDedented`, maybe in unary operators including `await`. Probably introduced in #1523.
