### ISSUE TITLE
Missing whitespace in `for`-reduce over `&`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1527]
```
for sum _ of&
```
Generates invalid JS:
```js
$ => { let results=0;for (const _ of$) {results += _}return results}
```
Note that adding a space between `of` and `&` allows it to generate perfectly valid JS.

**Comment by edemaine** [comment]
Looks like this is quite long-standing: `for _ of$` fails too (even with body, which has probably been around since the first version of CIvet)
