### ISSUE TITLE
reverse slice of string doesn't support unicode

### ISSUE THREAD

**Issue by JayXon** [DanielXMoore/Civet#1549]
`'😀'[..>=]` should be `'😀'`, but the utf 16 surrogate pairs are reversed too, which broke the emoji

I suggest to first convert the string to array using `[...a]` which properly support unicode

**Comment by edemaine** [comment]
Isn't this consistent with how regular slices work? For example, `'😀'.slice(1)` doesn't behave well.

My feeling is that, if you want to do something more Unicode-aware with strings, you should use `[...a].reverse()`. I think it would be weird for reverse slices to be smarter than slices. 😀

**Comment by JayXon** [comment]
You are right, consistent with regular slices is more important.
