### ISSUE TITLE
Immutability by default

### ISSUE THREAD

**Issue by marcus-sa** [DanielXMoore/Civet#1551]
One of the things I hate the most about TypeScript is that everything is mutable by default.
I wish there was an option that made everything immutable by default at compile time.
It'd be great if it something similar could be implemented in Civet.

**Comment by edemaine** [comment]
Do you have a specific proposal? Mutable is such a deep aspect of the runtime that I doubt this is really doable in something like Civet. But if you have specific ideas (freezing everything all of the time?), happy to discuss.
