### ISSUE TITLE
TypeScript `declare`

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#156]
* [x] `declare let $: JQuery` doesn't parse
* [x] `declare global {}`, `declare module "hot-new-module";` and `declare module "path" {}` parse as function calls
* [x] `declare class`

**Comment by GoToLoop** [comment]
I'm also trying `declare class`. Not working! Civet needs to recognize `declare` is a TS keyword.

**Comment by edemaine** [comment]
@GoToLoop Should be fixed in 0.5.73. Sorry for the delay!
