### ISSUE TITLE
Type of `key` in `for key in object` loops

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#1562]
While doing iterations on objects, the VSC extension gives an incorrect type for the `value`

```
let o =
    hello: 24

for value in Object.values o
    console.log value // value is "string"

for key, value in o
    console.log key, value // value is "any"
```

https://github.com/user-attachments/assets/4f63f57a-6f62-49f4-bd77-694375c9b232

Extension version **0.3.25**

**Comment by bbrk24** [comment]
While the fact that `value` is `any` in the second loop is annoying, the first loop isn't wrong -- that iterates over keys, not values.

**Comment by STRd6** [comment]
We could compile to `const value = o[key as keyof typeof o];`

**Comment by zolomatok** [comment]
> While the fact that `value` is `any` in the second loop is annoying, the first loop isn't wrong -- that iterates over keys, not values.

Oh, right, yeah

**Comment by edemaine** [comment]
This is a famous issue in the TypeScript world; see [this FAQ entry](https://github.com/microsoft/typescript/wiki/faq#indirect-excess-properties-are-ok) and https://github.com/microsoft/TypeScript/issues/12314

The argument is that, just because `o` is of type `{hello: number}`, doesn't mean that `o` doesn't have other keys. So you don't know exactly what you'll get out of a `for..in` loop or `Object.keys`.

Civet recently gained the ability to type `key` in the loop:

```js
for key: keyof typeof o, value in o
    console.log key, value
```

Unfortunately, it currently [compiles to](https://civet.dev/playground?code=Zm9yIGtleToga2V5b2YgdHlwZW9mIG8sIHZhbHVlIGluIG8KICAgIGNvbnNvbGUubG9nIGtleSwgdmFsdWU%3D)

```js
for (const key1 in o) {
  const key: keyof typeof o = key1;
  const value = o[key1];
  console.log(key, value);
}
```

Notably, `value` gets set to `o[key1]` (where `key1` has type `string`) instead of `o[key]` (where `key` has the desired `keyof` type). We can easily fix this though.

I don't think we want to change the behavior of `for (key in o)` loops, for TypeScript compatibility. But maybe we can make it easier, like a single keyword that implies `: keyof typeof o`? (I'm not sure what... `for k keyof o`? `for key k in o`?)

And maybe we should always cast when setting `value` in `for key, value in object` loops, as @STRd6 suggested above, because it's always a type error otherwise? But I'm not sure... the error is kind of intentional.

**Comment by STRd6** [comment]
Hmm.. we probably shouldn't do that compilation. After seeing this TS issue I recall that's why we didn't in the first place. It would, in general, be unsound, even for TS's standards.

**Comment by zolomatok** [comment]
@edemaine 
Thanks for the thorough reply!

> This is a famous issue in the TypeScript world

Regarding keys, my first example `for value in Object.values o` was a mistake, I was logging the indices.

It's the value in the second example I was wishing to have the type I was expecting.

> Notably, value gets set to o[key1] (where key1 has type string) instead of o[key] (where key has the desired keyof type). We can easily fix this though.

Hmmm. How does that result in `value` having type `any` 🤔

---

I just tried this and this does work
```
for const [key, value] of Object.entries(o)
    console.log key, value
```

<img width="418" alt="hover" src="https://github.com/user-attachments/assets/8ea96364-60cd-4cff-9755-6622c26c8451">


I wonder about the behind-the-scenes difference between `for key, value in o` and `for const [key, value] of Object.entries(o)`.
I guess it would a stretch to compile `for key, value in o` into `for (const [key, value] of Object.entries(o))` ?

**Comment by edemaine** [comment]
Honestly that's pretty weird that `Object.entries` "works". [Here it is in action on the TypeScript playground](https://www.typescriptlang.org/play/?#code/DYUwLgBA9hC8EG8CwAoC6IAsTGFAXBAEwAsqAvqgGZQBOEAFAMZQB2AzpANoDWIAngBoIANwCGwAK4gAutCoQA8gCMAViCZgAdCFZhaASxDsGUAJRnEqdCw5RQWvAHMGffmYDc1jD98B6PwA9AH5vW3Z7EEcoF3EpEE9vX2SAkIpqOkZwyDd5JTUNbTcTc0tkNAhwyOiXN0SK5P8g0JRKFCA). I'd argue that that's a bug in `Object.entries` (and `Object.values`); it's unsound. Ah, indeed, here is the bug: https://github.com/microsoft/TypeScript/issues/38520
We'll see how that issue evolves, but I wouldn't want to build anything on top of a shaky foundation like that.

To fix this, I think what you really want are "exact" object types. TypeScript object types just specify keys that *must* exist, but *any key might exist*. [Flow exact object types](https://flow.org/en/docs/types/objects/#exact-and-inexact-object-types) can specify the exact set of keys that exist. This would enable finer typing of keys and values.

We've discussed exact objects for pattern matching, but adding it to the type system is probably beyond the scope of Civet; it needs to be fixed at the TypeScript level. Unfortunately, that probably means it's a long ways off, if it will ever happen. Long-open issue here: https://github.com/microsoft/TypeScript/issues/12936

One more thing I learned reading these issues is that *inferred* types do behave well with `for..in` and `Object.keys`.  [Here is a rather elaborate example](https://www.typescriptlang.org/play/?#code/DYUwLgBA9gggxmArgQ2BAvBA3gWAFASEQAWIwwUAXBAEwAsANPkRAO5QBOwAJtXTUzwBffHCgA7AM6QoiSJgBmAClgIUwAJTMWAeh0A9APz4FicQgCWEiAoA8AFQggAHmBDjuk6ACMAViAQAPhVqRxc3Dy8AJQDOblsLcQUQDggYBghE5NSAIUCIQwhHanEQADcUjWxtBU4IJTEpSABrEABPTPFoKtwCIg5wRA4u1rbtET6BpGGIACJxKAhRyVn8ISA):

```ts
let oActual = {
    hello: 24,
    world: 42,
}
const out = f(oActual)
     //^? const out: "hello" | "world" | "no keys"
function f<T extends object>(o: T extends Record<infer A, infer B> ? T : never) {
  for (const key in o) {
    return key
  }
  return "no keys"
}
```

This is pretty interesting. I'm not sure exactly in what settings it works. *Maybe* there's some magic that Civet could do to make this automatic... but it's definitely not easy.

Meanwhile, I think you'll need to explicitly type the key, once #1564 gets released.

**Comment by zolomatok** [comment]
> Ah, indeed, here is the bug:

Oh woow!

> but I wouldn't want to build anything on top of a shaky foundation like that.

Yes, of course, makes sense


Thank you guys for looking into this, really appreciate it 🙏

**Comment by STRd6** [comment]
Closing this as it's more of a TS issue and #1564 provides a viable workaround.
