### ISSUE TITLE
Parse error in class method with return type and < 

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#1590]
Trying to upgrade to newer civet version (from 0.6.x), I get some errors in my code, like this won't parse anymore

```coffee
class A
  fn(i: number): string
    if i < 10
      "a"
    else # <--- parse error here 
      "b"
```

The same thing parses fine outside of a class

```coffee
fn := (i: number) : string =>
    if i < 10
      "a"
    else 
      "b"
```

or using `do`

```coffee
class A
  fn(i: number) : string do
    if i < 10
      "a"
    else 
      "b"
```

**Comment by bbrk24** [comment]
> The same thing parses fine outside of a class
> 
> ```coffee
> fn := (i: number) : string =>
>     if i < 10
>       "a"
>     else 
>       "b"
> ```

The reason this works is because it's an arrow. Using a `function` instead also doesn't parse:
```civet
function fn(i: number): string
    if i < 10
      "a"
    else 
      "b"
```
