### ISSUE TITLE
TypeError when compiling `readonly @prop` in c'tor

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1601]
both of these work fine:
```
class Foo
  @(readonly bar)

class Foo
  @(@bar)
```

but you can't combine them.

**Comment by edemaine** [comment]
Isn't combining them kind of redundant? Doesn't `@(readonly bar)` already assign to `this.bar` (if using TypeScript)? I agree it would still be nice, though.

**Comment by bbrk24** [comment]
In that case, it should at least diagnose, rather than crashing the compiler.
