### ISSUE TITLE
`compile` API questions

### ISSUE THREAD

**Issue by johndeighan** [DanielXMoore/Civet#1611]
I'm using deno. In the past, I used the command line version of civet without issues. However, now I'm trying to use the API, specifically the compile() function. The issue is that it complains about this syntax:

```
import {assert} from 'jsr:@std/assert'
import fs from 'node:fs'
import pathLib from 'node:path'
import {globSync} from 'npm:glob'
import lineByLine  from 'npm:n-readlines'
import {compile} from 'npm:@danielx/civet'

```
which is typical with deno

It appears that the compile() function does some checking that the `civet` command does not. Perhaps there's some option on the compile() function that can turn off the extra checks? I think the API should be better documented. I would actually like the checks if they would recognize the admittedly non-standard deno syntax for imports.

**Comment by edemaine** [comment]
> It appears that the compile() function does some checking that the `civet` command does not.

I don't think that's the case. The only difference between calling `compile` directly and the CLI should be an implicit setting of `rewriteCivetImports`, which I don't think would do anything here. And possibly a difference of ESM vs. CJS mode.

Can you give a MWE that causes an error? I don't see anything nonstandard in your example, and it [works in the Playground](https://civet.dev/playground?code=aW1wb3J0IHthc3NlcnR9IGZyb20gJ2pzcjpAc3RkL2Fzc2VydCcKaW1wb3J0IGZzIGZyb20gJ25vZGU6ZnMnCmltcG9ydCBwYXRoTGliIGZyb20gJ25vZGU6cGF0aCcKaW1wb3J0IHtnbG9iU3luY30gZnJvbSAnbnBtOmdsb2InCmltcG9ydCBsaW5lQnlMaW5lICBmcm9tICducG06bi1yZWFkbGluZXMnCmltcG9ydCB7Y29tcGlsZX0gZnJvbSAnbnBtOkBkYW5pZWx4L2NpdmV0Jwo%3D) which also uses the `compile` interface (just like the CLI does).

**Comment by johndeighan** [comment]
Thanks for the quick response. I think the problem may be that I'm not passing the proper options to the compile() function. E.g., when using the command line, I use:

civet --js --inline-map -c src/lib/llutils.civet -o .js

I.e. I want JavaScript code and I want the resulting file extension to be .js, not .jsx.
I also want an inline source map.

It would be a great help to me if you could point me to a web page that describes the options that compile() accepts. I've tried searching github for the actual code to no avail.

**Comment by edemaine** [comment]
* https://civet.dev/getting-started#transpilation gives an example of calling `compile`
* Types for `compile` are in [`types/types.d.ts`](https://github.com/DanielXMoore/Civet/blob/main/types/types.d.ts).
* The source code is here:
 
 https://github.com/DanielXMoore/Civet/blob/7a30fd4ac23b3ef00250d99bf8387567a9c4d06a/source/main.civet#L99

Perhaps the confusion is that `compile` just does transpilation; it doesn't do any file I/O. You're responsible for reading the file and outputting the result.

**Comment by johndeighan** [comment]
I think the problem comes down to the fact that I'm using Deno and not NodeJS. I'm getting an error on an import statement where the imported module uses schemes not supported by NodeJS. Here is an example:

```
# temp.civet

import {compileCielo} from './llutils.js'

export hConfig = {
	'.cielo': {
		outExt: '.js'
		}
	}

```
```
// llutils.js

import {assert} from 'jsr:@std/assert';
import fs from 'node:fs';
import {globSync} from 'npm:glob';

export const globFiles = (pattern) => {

	assert(typeof pattern === 'string');
	let lFiles = globSync(pattern);
	for (path of lFiles) {
		assert(fs.existsSync(path));
		}
	return lFiles;
}
```

I think that the civet compiler doesn't like the jsr: and npm: schemes. You may not need it, but here is the full error message. Note that with Deno, there is no CommonJS - everything is an ES6 module. Also, no package.json so nowhere to put "type": "module". But that's not where the error lies. I'm going to try to use Deno's "imports" field in my deno.jsonc file, but I've had problems with that in the past.

```
$ civet --js --inline-map -o .js temp.civet
(node:14952) [MODULE_TYPELESS_PACKAGE_JSON] Warning: Module type of file:///C:/Users/johnd/vllu/llutils.js is not specified and it doesn't parse as CommonJS.
Reparsing as ES module because module syntax was detected. This incurs a performance overhead.
To eliminate this warning, add "type": "module" to C:\Users\johnd\package.json.
(Use `node --trace-warnings ...` to show where the warning was created)
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'jsr:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:209:11)
    at defaultLoad (node:internal/modules/esm/load:107:3)
    at nextLoad (node:internal/modules/esm/hooks:748:28)
    at load (file:///C:/Users/johnd/AppData/Roaming/npm/node_modules/@danielx/civet/dist/esm.mjs:40:10)
    at nextLoad (node:internal/modules/esm/hooks:748:28)
    at Hooks.load (node:internal/modules/esm/hooks:385:26)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:511:21) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by edemaine** [comment]
That's a Node error message. It means that the Civet CLI is trying to run your code (in Node). The issue is that you're missing a `-c` command-line option to trigger compilation, not execution.

(Civet the compiler does nothing with colons in module specifiers.)
