### ISSUE TITLE
`FORCE_COLOR=1` isn't working flawless on the Civet project

### ISSUE THREAD

**Issue by Yewzir** [DanielXMoore/Civet#1639]
Hello

Last August 3rd, we've officially released the Civet project on [Code Golf](https://code.golf), a platform where we compete in solving programming challenges/puzzles/tasks in the least amount of bytes/characters. Unfortunately, the Civet project's yet to deploy its alpha release with version 1.0.0, which ought to happen anytime soon when we look at the high release frequency.

Now, last month I discovered the existence of an environment variable `FORCE_COLOR` that Node.js offers. Enabling color, setting it to `1`, works just fine for colored error output in the stderr field. Important to note that stderr is really the _only_ field where we want to have that effect.

![image](https://github.com/user-attachments/assets/0f503dc2-2b31-45ac-8c26-96d495a0beb4)

However, the variable causes unwanted behavior on stdout, which is what's evaluated after all. If we want to go with colored output, which is very common, that's a problem. We've come to discover that `console.log` doesn't like integers in at least one particular case when `FORCE_COLOR=1` is defined. Next are three examples of using `console.log` with an integer type.

Example 1:

![image](https://github.com/user-attachments/assets/46a84ff2-55bd-438e-a488-75070944c3b5)

![image](https://github.com/user-attachments/assets/a3abff81-085a-4104-82f6-a7c86680c7a0)

Example 2:

![image](https://github.com/user-attachments/assets/40187ab6-fd0d-4197-8064-eb055fcb6ece)

![image](https://github.com/user-attachments/assets/a3abff81-085a-4104-82f6-a7c86680c7a0)

Example 3:

![image](https://github.com/user-attachments/assets/3f74f164-1c08-4ce6-b47c-a56f70ff663d)

![image](https://github.com/user-attachments/assets/29a84393-3ddb-4c00-ac08-31b028e24c43)

It goes without saying that the third example has the unwanted behavior. Of course, the pull request submission contained default sample code for the language à la third example. It's a bummer really, and I wish I'd found out about `FORCE_COLOR` prior to making the submission. As of now, it's impossible for us to enable it because it would break an ENORMOUS amount of solutions, and we can't do that.

If this can be resolved easily on our end, great, I'm all ears. However, I think this is one for the Civet project since we've had a successful implementation of `FORCE_COLOR=1` for the Gleam project, where JavaScript's the executable target and operates on Node.js as well.

Thank you for your cooperation.

Kind regards
@Yewzir

**Comment by edemaine** [comment]
Thanks for your efforts to include Civet in Code Golf! We're happy to be part of it.

I think we need more information to help track down the issue you're running into. `FORCE_COLOR=1` should cause integers to be colored using ANSI escape codes. That looks like what you're getting in your output: `ESC[33m` represents the yellow color that you're supposed to get. But perhaps your terminal (or whatever you're using to display) isn't interpreting those codes correctly? Does this work for you in other Node-based languages other than Civet? Civet shouldn't be doing any processing here, I don't think. And I'm unable to reproduce it myself in a regular terminal:

![image](https://github.com/user-attachments/assets/b7c80edb-f205-4890-b612-b89f4ef83be4)

![image](https://github.com/user-attachments/assets/99128aa3-5a12-4e5d-87e8-77908b1ccba5)

In both cases, the yellow color gets rendered correctly. So I'm guessing it has something to do with the context in which you're running Civet. Perhaps a pipe or postprocessing is causing some different behavior? Could you elaborate on how you're running Civet?

**Comment by Yewzir** [comment]
> `FORCE_COLOR=1` should cause integers to be colored using ANSI escape codes. That looks like what you're getting in your output: `ESC[33m` represents the yellow color that you're supposed to get. But perhaps your terminal (or whatever you're using to display) isn't interpreting those codes correctly?

Thank you for reply. I think you're misunderstanding, though.

![393504205-29a84393-3ddb-4c00-ac08-31b028e24c43](https://github.com/user-attachments/assets/da3d4934-3ea3-4fd1-aa63-c5c73f276957)

This is the field that represents STDOUT. Not being able to correctly render color in that field is not the issue, the issue is the attempt to actually render color. In other words, there shouldn't be any interpreting at all. In my original post, I mentioned that STDERR is really the only field where the effect is acceptable. That's working perfect for us, but STDOUT needs to preserve its default color at all times. There's no added value in having for instance a Quine or just looping 0-9 render its output in a color other than the default.

> Does this work for you in other Node-based languages other than Civet?

This is confusing, kind of, because it actually does. I've successfully managed to set up the expected behavior for the Gleam project. We'd decided to implement it using JavaScript as the compilation target, and thus let it operate on Node.js. However, `FORCE_COLOR=1` with Gleam performs as expected: color output in the STDERR field, and leave STDOUT as is.

**Comment by edemaine** [comment]
It seems that Node behaves exactly the same as Civet here:

![image](https://github.com/user-attachments/assets/be6ed975-55b8-4389-8ae7-738b56f9f3e7)

* When run directly with a TTY output, the number 5 gets colored yellow.
* When the output is a pipe, the number does not get colored.
* But if we use `FORCE_COLOR=1` and the output is a pipe, the number gets colored yellow.

<https://force-color.org/> doesn't mention anything about stdout vs stderr. Where do you see that only stderr is colored while stdout is not colored?

Could you explain your motivation for using `FORCE_COLOR=1`? It doesn't sound like you want color in your output, so why not avoid setting `FORCE_COLOR` in the first place?

**Comment by Yewzir** [comment]
> Could you explain your motivation for using `FORCE_COLOR=1`? It doesn't sound like you want color in your output, so why not avoid setting `FORCE_COLOR` in the first place?

Because, actually never mind, it's good. We'll manage.

**Comment by edemaine** [comment]
OK - let us know if we can help!
