### ISSUE TITLE
[playground] Selected text shows ligature with unchecked ligature checkbox 

### ISSUE THREAD

**Issue by angelhdzdev** [DanielXMoore/Civet#1644]
Hi 👋,

When selecting text that contains symbols that can be converted to ligatures, and the ligature checkbox is unchecked, it still shows it as ligature. Tested in Chrome and Firefox in Kubuntu, but seems like an issue with the highlighting code so issue most highly will be present in other operating systems.

![image](https://github.com/user-attachments/assets/f7cb5134-83dd-452f-9f62-c208234379d3)

Lots of health, fun, peace, and success to everyone involved in this nice TS superset. Having fun with it.

**Comment by bbrk24** [comment]
On Firefox on Windows 11, clicking the checkbox un-highlights the text, and the ligature does not stay.

**Comment by bbrk24** [comment]
Wait, I misunderstood the issue. After clicking the checkbox to turn ligatures off, re-highlighting the text shows the ligature again. That is odd.

**Comment by edemaine** [comment]
Thanks for the report! It turns out that the default CSS in Chrome for `<textarea>` (the backing text that you copy/paste from) has `font-variant-ligatures: default` instead of `font-variant-ligatures: inherit`. Adding the latter fixed the problem.

![image](https://github.com/user-attachments/assets/f1684277-9ac4-4d08-a5a6-d52ada6dbb9a)

**Comment by angelhdzdev** [comment]
> Thanks for the report! It turns out that the default CSS in Chrome for `<textarea>` (the backing text that you copy/paste from) has `font-variant-ligatures: default` instead of `font-variant-ligatures: inherit`. Adding the latter fixed the problem.
> 
> ![image](https://private-user-images.githubusercontent.com/2218736/395877109-f1684277-9ac4-4d08-a5a6-d52ada6dbb9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODI4MjMsIm5iZiI6MTczNDI4MjUyMywicGF0aCI6Ii8yMjE4NzM2LzM5NTg3NzEwOS1mMTY4NDI3Ny05YWM0LTRkMDgtYTVhNi1kNTJhZGE2ZGJiOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTcwODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI0YTVjZTBmYmNlMDBjMzkzMDRkOTQzYmEwZTk5MjM1NDM5ZDU5MjI3YjdmYzE3NmNmMWM4NGQ0ZGI1OGJmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wfs9PSwmPklajPompFIY1dPKJX9K2_NusB0nkoPP8UE)

Interesting discovery! Thanks for your time.

@bbrk24  thank you as well!
