### ISSUE TITLE
`for first each`, `for sum each`, and others generate incorrect JavaScript

### ISSUE THREAD

**Issue by nicholaides** [DanielXMoore/Civet#1658]
```coffee
for first each item of array
```

produces

```typescript
let results = undefined;
for (
  let i = 0, len = array.length;
  i < len;
  i++
) {
  const item = array[i];
}
results;
```

I expected the for loop to have `return item` in the body.

Similarly, the following generate code that seems to be missing code from the body of the for loop:

```coffee
for sum      each item of array
for product  each item of array
for min      each item of array
for max      each item of array
for join     each item of array
for concat   each item of array
```

The following seems to work **correctly**:
```coffee
for count each item of array
```

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implement logic to handle special aggregation keywords like 'first', 'sum', 'product', etc. in for..each loops. This includes adding the necessary initialization, loop body, and return statements for each aggregation type.

You can review changes in this commit: https://github.com/jacks-sam1010/DanielXMoore-Civet-1658/commit/657e087e0e9c0196ab016d6f9d0e17ca4a4f396e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
