### ISSUE TITLE
Pattern match creates unused variable

### ISSUE THREAD

**Issue by nicholaides** [DanielXMoore/Civet#1660]
```coffee
switch person
  {age: 100}
    console.log("old")
```

generates:

```typescript
if (
  typeof person === "object" &&
  person != null &&
  "age" in person &&
  person.age === 100
) {
  const { age } = person;
  console.log("old");
}
```

Which causes this TypeScript error:
`'age' is declared but its value is never read.typescript(6133)`

**Comment by edemaine** [comment]
Agreed, this annoys me too. The plan is to remove destructuring for properties that have a specified value (though this will be a breaking change). Will try to get to it (and your other bug reports) soon, but Christmas means not for a few days.
