### ISSUE TITLE
feature request: implement pattern matching

### ISSUE THREAD

**Issue by nexxeln** [DanielXMoore/Civet#169]
Civet looks very promising! 

Would be cool to have pattern matching in civet like in OCaml or Elixir or Rust.

**Comment by gustavopch** [comment]
Yeah, it will be awesome. It's being discussed here https://github.com/DanielXMoore/Civet/discussions/150 already. Better close this issue, I think, so we keep everything there.

**Comment by nexxeln** [comment]
> Yeah, it will be awesome. It's being discussed here #150 already. Better close this issue, I think, so we keep everything there.

Really sorry! That didn't come up on my search for some reason. I'll close this.
