### ISSUE TITLE
`::=` type declaration shorthand

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#176]
```typescript
Id ::= string | number
// 👇 ts
type Id = string | number

User ::=
  id: number
  name?: string

// 👇 ts
type User = {
  id: number
  name?: string
}
```

Suggested by @sultan99 with some modifications.

**Comment by STRd6** [comment]
`Id :: string | name` is also a possibility. It won't conflict with `Id::x` because the `.prototype.` shorthand can't have spaces.

**Comment by gustavopch** [comment]
Consolidating with https://github.com/DanielXMoore/Civet/discussions/126 so we can see the consistency:
```ts
// Type
User ::
  name: string

// Object
user :=
  name:: string = 'John'

// Function
createUser := ({
  id: userId: string
  name:: string
  ...rest: SomeOtherProps
}) =>
  // ...
```
I like this.

**Comment by STRd6** [comment]
> Edit: Not sure what the syntax for typing the object properties would be though. Probably not this, I guess:
> 
> ```ts
> user :=
>   name: string: 'John'
> ```

TypeScript [already supports](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgSQCIBUCGBzGAbwF8BuAKCgE8AHOdDGAXhiWQCM4AnGAMgdx5y5UJFiII3ZkXIxWOZHABcMAEQApEAAswqgDSyYASwAmKgOwwcEBuWLkgA):

```typescript
const user = {
  name: "John", // string is inferred
  id: 7 as ID // cast number to ID
}
```

**Comment by gustavopch** [comment]
There's the difference between declaration and assertion.
```ts
const x: 'foo' | 'bar' = 'lalala' // Error
const y = 'lalala' as 'foo' | 'bar' // No error
```
But we don't need to worry about this now.

**Comment by edemaine** [comment]
> `Id :: string | name` is also a possibility.

I'd prefer `::=` for defining a type.  `::` looks too much like "has the type", e.g. in Haskell.  Especially if:



> Edit: Not sure what the syntax for typing the object properties would be though. Probably not this, I guess:
> 
> ```ts
> user :=
>   name: string: 'John'
> ```

In #126 we've discussed using `::` for type specification in objects:

```ts
user :=
  name:: string: 'John'
```

**Comment by STRd6** [comment]
`::=` for type declaration `::` for interface? Just throwing it out there.

**Comment by gustavopch** [comment]
Makes sense because type declarations have an equal sign and interface declarations don’t.

**Comment by edemaine** [comment]
Just pointing out that using `::` for interface declaration would prevent us from using it as `let` shorthand: `name:: type` → `let name: type`.  So at least we should try to think up a good `let` shorthand while also thinking about `interface`, so that we can hopefully make one consistent design.

**Comment by bbrk24** [comment]
I just noticed, this is still marked as "TODO" in the README...
