### ISSUE TITLE
`new` shouldn't need parens

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#177]
`new Foo` (without a following function call) should become `new Foo()`, as  it couldn't mean anything else. CoffeeScript does this too.

**Comment by STRd6** [comment]
ES6 allows omitting the parens on no-arg `new X`. Not adding them keeps the transpiled output closer to the source input.

This might be fine as is.

**Comment by edemaine** [comment]
Oh, I didn't realize that was already in ES, and so early at that. Agreed, we don't need to do anything here.
