### ISSUE TITLE
Decorator syntax

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#18]
What is the Civet syntax for TS **decorators**?

Given:
```
const printable = (target: any, memberName: string) =>
    console.log memberName

class Person
    @printable
    name = 'Jon'
```

I get the warning `Member 'printMemberName' implicitly has an 'any' type.typescript(7008)` because `@` is used for static members.

The Code Sample at the top of the readme contains the
```
experimentalDecorators: true
```
flag in the compiler options, so I assume they are supported.

**Comment by STRd6** [comment]
They currently are not supported but I could probably add them at some point.

Thanks for the report!

**Comment by STRd6** [comment]
What do you think about using `@@printable` for the decorator syntax? That way there is no ambiguity between decorators and `this.` shorthand.

**Comment by edemaine** [comment]
Seems reasonable to me.  I agree that we can't reasonably use `@` for both.

I guess we could start a "jsCompat" or "tsCompat" set of flags (analogous to `coffeeCompat`) that, for starters, removes the `this.` shorthand and instead leaves `@` for decorators.

**Comment by STRd6** [comment]
Ideally we could become so popular that the decorator proposal changes before it becomes a standard 😼

**Comment by zolomatok** [comment]
@STRd6 

In every other language I used, annotations are denoted with `@`. TS, Python, Java.
This may be a controversial suggestion, but how about flipping the current Civet syntax to mirror that convention?

So `@` becomes the syntax for annotations and `@@` (or `#` or `::` maybe) becomes the syntax for class properties.
Though @@ looks kinda funky.

**Comment by STRd6** [comment]
I've added support for decorators with `@@` syntax instead of `@` because `@` is premium real estate and `@id` -> `this.id`, and `@` is also static fields/methods, etc.

If `@` decorator syntax makes it to a standard then maybe I'll re-evaluate but I'd rather pressure the spec in this direction.

**Comment by angelhdzmultimedia** [comment]
> I've added support for decorators with `@@` syntax instead of `@` because `@` is premium real estate and `@id` -> `this.id`, and `@` is also static fields/methods, etc.
> 
> If `@` decorator syntax makes it to a standard then maybe I'll re-evaluate but I'd rather pressure the spec in this direction.

`@Decorators` are not experimental anymore in TypeScript. 🔥🎉
So, time to re-evaluate `@` as decorator, and `->` as `this` maybe?

```
@Injectable
class AuthService
  ->(private prismaService: PrismaService)
    console.log 'Constructor!'
    console.log  ->prismaService
```

**Comment by edemaine** [comment]
`->` is already heavily used for `function`s; I doubt we will change that one.

I could see offering a switch for `@` behavior, maybe as part of jsCompat. Maybe flipping the current meanings of `@` and `@@`? Or another notation for `this` if we can think of one.

**Comment by GoToLoop** [comment]
If just `@` turns out too hard to implement due to ambiguity, `@@` is a fair decorator replacement.

**Comment by angelhdzmultimedia** [comment]
> `->` is already heavily used for `function`s; I doubt we will change that one.
> 
> I could see offering a switch for `@` behavior, maybe as part of jsCompat. Maybe flipping the current meanings of `@` and `@@`? Or another notation for `this` if we can think of one.

I missed this! Thank you!

![image](https://user-images.githubusercontent.com/10191085/228058141-0be6ac36-0ab0-4c3b-9d72-8ee33acbd282.png)

**Comment by angelhdzmultimedia** [comment]
I was playing with different syntax for the decorators, and all roads took me back to `@@`.

And about reversing '@' and '@@', I think it makes sense that '@'  stays as it is currently, pointing to `this`.
Having to use '@@' for 'this' takes away the simplicity, as for decorators, we are already "decorating" a class or function, so one extra `@` doesn't do harm visually and practically.

My 2 cents.

### Question
Anyone knows why I get a syntax error in the playground?

![image](https://user-images.githubusercontent.com/10191085/228062308-e12ec291-be7e-4bd7-998b-9d906db78565.png)

**Comment by edemaine** [comment]
@angelhdzmultimedia Regarding the syntax error, could you open a discussion or issue (or Discord post) with the actual code as text, not a screenshot?

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Regarding the syntax error, could you open a discussion or issue (or Discord post) with the actual code as text, not a screenshot?

Yeah my question was more like "decorators should we working on the online playground, right?"

But sure, I can open an issue for it.

**Comment by STRd6** [comment]
I think the syntax error is because browsers don't natively support decorators yet.

**Comment by edemaine** [comment]
You're right, @STRd6; I missed that this was part of the console output, which happens only when clicking "run".

**Comment by angelhdzmultimedia** [comment]
> I think the syntax error is because browsers don't natively support decorators yet.

Oooh right! I'm so used to the TypeScript playground, were we can configure tsconfig and enable experimental decorators, that I assumed that because the decorators were showcased in Civet's playground, they should have worked. 😁

Excellent, thanks! I'm gonna play with them in VSCode now!

Have fun kind people! 😊🤝🔥
