### ISSUE TITLE
Bug in coffeeFor for loop generation code

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#193]
```coffee
"civet coffeeCompat"
for i in [0...n]
  5
```

transpiles to

```js
var i
for (let i = i = 0, asc = 0 <= n; asc ? i < n : i > n; i = asc ? ++i : --i) {
  5
}
```

which crashes with `i used before assignment`.  If `i` is used within the body, it works: the second instance of `i` gets renamed to `i1`.  So maybe an issue with the ref mechanism?

**Comment by STRd6** [comment]
It may be that the `ref` populating isn't checking the sub-expressions inside `ForStatementParameters`.

**Comment by edemaine** [comment]
Investigating, it seems that the main issue is that this code on looks for `Identifier`s:

https://github.com/DanielXMoore/Civet/blob/507a0cb96bf6689a745f2c9c02127a801492e0eb/source/parser.hera#L5977-L5979

But in the AST we instead have this node:

```js
    {
      type: 'AssignmentExpression',
      name: 'i',
      names: ['i'],
      children: [ { '$loc': [Object], token: 'i' } ]
    },
```

Should `AssignmentExpression` be changed to include an `Identifier` node, or should we add `AssignmentExpression` to the list of things to look for?

**Comment by STRd6** [comment]
I think your first suggestion of having the generated AST nodes be totally conforming to the parsed node interfaces is the way to go.
