### ISSUE TITLE
Loop expressions don't behave well in TypeScript

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#194]
Consider the following simple code:

```coffee
strings := ["civet"]
copy :=
  for s of strings
    s
```

This transpiles to:

```js
const strings = ["civet"]
const copy =
  (results=>{for (const s of strings) {
    results.push(s)
  }; return results})([])
```

TypeScript [complains](https://www.typescriptlang.org/play?#code/MYewdgzgLgBNBOBLMBzCMC8MDaAiYiAbgKZS4C6AsAFCiSygAOAnpjTDABTzEQCuAGygQMAPgDeAMxDwudaHBghJcKElQQAlDHHsOMHvyEQAdIz4QAFpy16AvgG4DpPvDDOjwu5s7ZymoA) because `results` gets automatically typed as `never[]`:

![image](https://user-images.githubusercontent.com/2218736/211681570-655ef662-3fa9-4521-8b85-3517fff1e0c2.png)

I'm not sure the best way to fix this...

**Comment by STRd6** [comment]
`[] as any` would fix the error but wouldn't be the complete solution of inferring the correct type for the array (maybe impossible in the most general case).

**Comment by edemaine** [comment]
Apparently TypeScript is a lot smarter about undeclared variables than function arguments.

The following code correctly types `copy` as `string[]` based on growing `results` type. (I think this was introduced in TS 4.3.)

```ts
const strings = ["civet"]
const copy =
  (() => {
    const results = []
    for (const s of strings) {
      results.push(s)
    }
    return results
  })()
```

[Playground](https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBNBOBLMBzCMC8MDaAiYiAbgKZS4C6AsAFCiSygAOAnpjTDABScCUmAfDADe7DjDrQY8YhACuAGyjos2KtTEwAZiHhcJsdCE1woSVBD4j1GqTIVKAdI1kQAFpwuiOAXy+2osvBgtnKKEKLePLxAA)
