### ISSUE TITLE
Indentation with continued lines

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#203]
The following code does not parse:

```coffee
extension := compileOptions.extension ??
  if compileOptions.js
    ".civet.jsx"
  else
    ".civet.tsx"
```

But this does:

```coffee
extension := compileOptions.extension ??
  if compileOptions.js
    ".civet.jsx"
else
    ".civet.tsx"
```

I assume the issue is that the newline after `??` doesn't trigger a PushIndent, so `else` doesn't know the correct indentation level.  I wonder if `if` should be responsible for pushing an indent? I'm not sure.

**Comment by STRd6** [comment]
We may be able to refine `BinaryOpRHS` to check for nested expressions first before expanding to arbitrary whitespace.

**Comment by edemaine** [comment]
I can't believe I came up with almost the same example in #598 without remembering this issue.  #600 [fixed this](https://civet.dev/playground?code=ZXh0ZW5zaW9uIDo9IGNvbXBpbGVPcHRpb25zLmV4dGVuc2lvbiA%2FPwogIGlmIGNvbXBpbGVPcHRpb25zLmpzCiAgICAiLmNpdmV0LmpzeCIKICBlbHNlCiAgICAiLmNpdmV0LnRzeCI%3D).
