### ISSUE TITLE
Type parameters on following line (not)

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#209]
I was writing [the following code](https://civet.dev/playground?code=bGV0IHN2ZzogU1ZHU1ZHRWxlbWVudAo8aGVhZGVyPgo8c3ZnIHJlZj17c3ZnIX0%2B):

```coffee
let svg: SVGSVGElement
<header>
<svg ref={svg!}>
```

`<header>` gets treated as a type parameter for `SVGSVGElement`. I intended for the implicit return, as in:

```jsx
let svg: SVGSVGElement;
return <>
  <header />
  <svg ref={svg!} />
</>;
```

Current workaround is to add `;` at end of `let` statement.

I think type parameters should not be allowed at the Samedent level; should be strictly indented.

**Comment by STRd6** [comment]
There should probably be no whitespace allowed between the identifier and the `<` to be interpreted as a TypeParameter list.

**Comment by edemaine** [comment]
Ah, probably right: otherwise ambiguous with an implicit function call that contains JSX.
