### ISSUE TITLE
Dot notation with string literals

### ISSUE THREAD

**Issue by orenelbaum** [DanielXMoore/Civet#212]
`x.'y-z'` => `x['y-z']`
```
x.`y-${z}`
//  ↓ ↓ ↓
x[`y-${z}`]
```

**Comment by STRd6** [comment]
I like it!

**Comment by Rishav1707** [comment]
What do you want to change in this issue? @orenelbaum

**Comment by orenelbaum** [comment]
I want to support the syntax I described. Right now it's not supported.

**Comment by Rishav1707** [comment]
> I want to support the syntax I described. Right now it's not supported.

Ok
