### ISSUE TITLE
Dot notation after a space to access member of function call result

### ISSUE THREAD

**Issue by orenelbaum** [DanielXMoore/Civet#215]
Right now in order to get this JS `f(x, y).z`, we have to write it the same way in Civet.
I'm proposing supporting this syntax `f x, y .z` => `f(x, y).y`.
I think that this is really needed.

**Comment by STRd6** [comment]
Not entirely sure about this one. We may want to reserve the `.id` design space for other uses. Hypothetically `people.map .name` for a shorter `&`block notation.

Happy to explore the idea however.

**Comment by orenelbaum** [comment]
Personally I think that using it to escape function params will be much more valuable since this is very common and `&.x` is just one character longer than `.x`.

**Comment by STRd6** [comment]
I did just encounter a situation where it would be handy here: https://github.com/DanielXMoore/Civet/pull/226

Implicit parens on import types and there is not an obvious place for the `.name` so it may make it in yet. :)

**Comment by edemaine** [comment]
I guess my initial worry is that `f x .y` looks an awful lot like `f x.y` (and I assume that's how it currently parses).

Then again, I already expect:

```coffee
f x
.y
```

to parse as `f(x).y`. So maybe the inline version is fine too..

**Comment by STRd6** [comment]
May have a bit of a complication because:

```coffee
f x
  .y
f x
.y
```

```javascript
f(x.y)
f(x).y
```

**Comment by STRd6** [comment]
> May have a bit of a complication because:
> 
> ```coffee
> f x
>   .y
> f x
> .y
> ```
> 
> ```js
> f(x.y)
> f(x).y
> ```

This no longer happens so isn't blocking this issue any more.

Probably needs more discussion and a thorough exploration of situations and examples since it is fairly core to the language.

**Comment by STRd6** [comment]
What happens with this?
```typescript
f g x .y .z
```

**Comment by orenelbaum** [comment]
I would expect it to probably compile to `f(g(x).y).z`
Maybe a bigger question is are we going to allow multiple spaces for more than one level of escape?
`f g x .y` => `f(g(x).y)
`f g x  .y` => `f(g(x)).y`
Maybe this is too much and at this point it would be better to just require the user to write `f(g x).y` or alternatively `f g(x) .y`

**Comment by STRd6** [comment]
This design space got used up for 

```typescript
people.map .name

```
