### ISSUE TITLE
Building is broken from "scripts"

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#217]
If I run
`./node_modules/@danielx/civet/dist/civet test.civet`
everything is **fine**.

But if I add a script in `package.json`:
```
"scripts": {
     "test": "civet < ./test.civet > ./test.ts"
}
```
and try to run it with
`npm run test`

I get:

```
/dev/fd/test.civet failed to load:
[Error: ENOENT: no such file or directory, open '/dev/fd/test.civet'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/dev/fd/test.civet'
}
```

**Comment by zolomatok** [comment]
The above worked `0.4.38`, I just updated to `0.5.36` and it doesn't work anymore.

**Comment by edemaine** [comment]
What operating system are you using?

Does `./node_modules/@danielx/civet/dist/civet < test.civet > test.ts` work on the command line?

Does `civet test.ts -o test.civet` work as a script?

**Comment by STRd6** [comment]
It's working for me on WSL with Civet `v0.5.37` and `v0.5.28` just for an added data point.

**Comment by zolomatok** [comment]
@edemaine 

> What operating system are you using?

I'm on an apple silicon mac.
Running `uname -mprs` produces
`Darwin 21.6.0 arm64 arm` in Terminal and
`Darwin 21.6.0 x86_64 i386`in VSC, I guess that's under Rosetta.

Regarding the results for each command there's no difference whether I run them in the native Terminal or VSC's terminal.

> Does ./node_modules/@danielx/civet/dist/civet < test.civet > test.ts work on the command line?

Nope, it doesn't, in either terminal.

> Does civet test.ts -o test.civet work as a script?

Do you mean `civet test.civet -o test.ts`?

Yes! That works as a script in both native and rosetta terminal.

**Comment by zolomatok** [comment]
> Yes! That works as a script in both native and rosetta terminal.

A simple `civet test.civet` also works as a script.

```
"scripts": {
        "civet2": "civet test.civet"
 }
```

**Comment by edemaine** [comment]
Sorry, I meant `civet -c test.civet -o test.ts` as an alternative way to transpile.

I'll try testing on a Mac myself.

**Comment by zolomatok** [comment]
> Sorry, I meant civet -c test.civet -o test.ts as an alternative way to transpile.

Oh, gotcha, yes, that also works as a script.

**Comment by edemaine** [comment]
Ok, so it's just the pipe form that's broken, so you should be set for a workaround. But we appreciate the report and will investigate!

**Comment by zolomatok** [comment]
Yepp, sure am! Thanks for your help!

**Comment by edemaine** [comment]
I confirmed the buggy behavior on a Mac (probably any Unix actually). Should be all fixed on the latest version of Civet!
