### ISSUE TITLE
autoVar failing with multiple functions

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#220]
[Playground](https://civet.dev/playground/?code=ImNpdmV0IGNvZmZlZUNvbXBhdCIKZnVuY3Rpb24gZgogIGkgZm9yIGkgaW4gWzEuLjVdCmZ1bmN0aW9uIGcKICBpIGZvciBpIGluIFsxLi41XQ%3D%3D)

Input:

```coffee
"civet coffeeCompat"
function f
  i for i in [1..5]
function g
  i for i in [1..5]
```

Output:

```js
function f() {
  var i;
  const results = [];
  for (
    let i1 = (i = 1), asc = 1 <= 5;
    asc ? i1 <= 5 : i1 >= 5;
    i = asc ? ++i1 : --i1
  ) {
    results.push(i);
  }
  return results;
}
function g() {
  const results = [];
  for (
    let i1 = (i = 1), asc = 1 <= 5;
    asc ? i1 <= 5 : i1 >= 5;
    i = asc ? ++i1 : --i1
  ) {
    results.push(i);
  }
  return results;
}
```

The second function has no `var i` declaration.

**Comment by edemaine** [comment]
Here's a [simpler example](https://civet.dev/playground/?code=ImNpdmV0IGNvZmZlZUNvbXBhdCIKZnVuY3Rpb24gZgogIGlmIHRydWUKICAgIGkgPSA1CmZ1bmN0aW9uIGcKICBpID0gMTA%3D) of failure that doesn't involve loops:

```coffee
"civet coffeeCompat"
function f
  if true
    i = 5
function g
  i = 10
```

`autoVar` just seems to be have a hard time distinguishing scopes. 😅

**Comment by STRd6** [comment]
Probably a simple fix making sure we push and pop the declaration stack appropriately.
