### ISSUE TITLE
Multiple divisions are not RegExp

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#221]
`Math.floor x / y / 2` parses as a regular expression instead of two divisions.

I think usually a space after `/` means "not a regular expression".

**Comment by edemaine** [comment]
Even worse, `Math.floor (x / y) / 2` fails to parse. Are we forbidding multiple division in a row?

**Comment by STRd6** [comment]
I think those should be interpreted as divisions, probably just a parsing bug.

**Comment by edemaine** [comment]
Another fun one: `Math.floor x / y // comment` parses as a regular expression, not a comment 😅
