### ISSUE TITLE
LSP catching up

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#222]
When parsing takes a few seconds and you type 5 characters, you get LSP feedback for each version, one at a time.

Instead I'd propose: Once a parsing job completes, fast forward all "file update" messages received in the interim (coalescing multiple single-character updates in one file, for example), and only start a new parsing job with the final versions?

**Comment by edemaine** [comment]
This is fixed now (though I'm not certain the latest changes were released).

**Comment by STRd6** [comment]
Published lsp v0.3.6 today.
