### ISSUE TITLE
Indentation issue... with JSX functions?

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#237]
```coffee
    <For each=characters>
      (character) =>
        function transform
          []
          .filter Boolean
          .join ' '
```

Currently [transpiles to](https://civet.dev/playground/?code=ICAgIDxGb3IgZWFjaD1jaGFyYWN0ZXJzPgogICAgICAoY2hhcmFjdGVyKSA9PgogICAgICAgIGZ1bmN0aW9uIHRyYW5zZm9ybQogICAgICAgICAgW10KICAgICAgICAgIC5maWx0ZXIgQm9vbGVhbgogICAgICAgICAgLmpvaW4gJyAnCg%3D%3D)

```js
    <For each={characters}>
      {(character) => {
        return function transform() {
          return []
        }
      }}
</For>
          .filter(Boolean)
          .join(' ')
```

Maybe a missing `PushIndent` with implicitly brace-wrapped JSX functions? It works with explicit brace wrapping.

Simpler bad example:

```coffee
    <For each=characters>
      (character) =>
        []
        .join ' '
```

**Comment by STRd6** [comment]
I think some JSX rules may need to be added to the `no cache` list:

```
~/apps/civet$ ./dist/civet < test.civet  --no-cache
    <For each={characters}>
      {(character) => {
        return []
        .join(' ')
      }}
</For>
```

An important thing to remember is that even if the rule itself doesn't handle nesting/indentation if it is the parent of a rule that does then it should be no-cache as well.

**Comment by STRd6** [comment]
It may even be a missing `no cache` above the JSX rules as well by the same reasoning.

**Comment by STRd6** [comment]
I was checking this out and it's `StatementListItem`. I've got a commit ready.

**Comment by STRd6** [comment]
Fixed in ad8c65aea330f4f6e8e1262858952bdc63cc4549

**Comment by edemaine** [comment]
Hmm... I still have [the same issue in Playground](https://civet.dev/playground/?code=ICAgIDxGb3IgZWFjaD1jaGFyYWN0ZXJzPgogICAgICAoY2hhcmFjdGVyKSA9PgogICAgICAgIGZ1bmN0aW9uIHRyYW5zZm9ybQogICAgICAgICAgW10KICAgICAgICAgIC5maWx0ZXIgQm9vbGVhbgogICAgICAgICAgLmpvaW4gJyAnCg%3D%3D) (and locally).

**Comment by edemaine** [comment]
Thanks for fixing this!

**Comment by STRd6** [comment]
Thanks for the detailed error report!
