### ISSUE TITLE
Arrow function can be non intuitive for JS developers

### ISSUE THREAD

**Issue by lorefnon** [DanielXMoore/Civet#24]
Currently `y := x => x + 1` compiles to `const y = x(() => x + 1)` which may be a source of confusion for people coming from js which allows parenthesis to be omitted for single argument. 

Should we consider adopting the js behavior by default (unless coffeeCompat is set to true) ? 

Perhaps to reduce ambiguity we enforce that arg list can never be omitted, so instead of `y := -> 1` we'd have to write `y := () -> 1`

**Comment by STRd6** [comment]
I feel the "one arg optional parens" "feature" in ES is a design error. Civet also provides a better way to omit single arguments with the `&+1` => `$=>$+1` function shorthand.

You can use `y := &+1` for your example above.

In cases where CoffeeScript did a feature earlier / better I prefer to use that design to "fix" things where ES left inconsistencies.

A lot of words to say this is by design but maybe a `"civet esCompat"` directive could include this for people who have a large legacy ES codebase to migrate.

**Comment by lorefnon** [comment]
Ok, I'll close this since this design was intentionally chosen. 

I can get used to always needing parenthesis for fn args. 

The `&` syntax is not convenient other than places where the the type can be inferred because something like `y := &+1` results in a ts error that the (mysterious 😄 ) parameter $ implicitly has an any type.

**Comment by STRd6** [comment]
@lorefnon Good point about the type inference. You could add a type annotation to the declaration side like:  `y : (n:number) => number := &+1` but I'm open to exploring a better way.

**Comment by lorefnon** [comment]
I don't have a strong opinion/suggestion here, but I'll see if I can do something on the lsp side to make the error better. The current errors are not very obvious to someone who is not aware of the paramless arrow fn syntax. 

![image](https://user-images.githubusercontent.com/1449492/206758311-9ca18e2d-06d4-4ba9-bedd-94f0b503909d.png)

**Comment by edemaine** [comment]
Would `&: number + 1` or `(&: number) + 1` be interesting typed shorthand for `($: number) => $ + 1`?

**Comment by STRd6** [comment]
@lorefnon TypeScript doesn't allow Type annotations on paren-less single parameters (another reason I choose to disallow them). There is definitely room to improve error messages in the LSP and I'd be happy for you to take a look.

The recommended Civet way to type annotate your example is:

```civet
z : (n: number) => number := &+1
```

Note the annotation is for the type of `z` to the left of the const assignment `:=`.

In cases where the ampersand function is used inline TS can usually infer the type correctly.

```civet
declare const x : number[]

y := x.map &+1
```

@edemaine in light of these examples I think that allowing inline type annotation of ampersand functions makes the intent a bit less clear but I'd be happy to look at some counter examples.

Also, I want to say thank you both for your contributions! It really helps me work out the practical details of the language to see how people feel most comfortable using it.
