### ISSUE TITLE
`null`/`undefined` type shorthands

### ISSUE THREAD

**Issue by xiBread** [DanielXMoore/Civet#242]
Ref: microsoft/TypeScript#7426

I'm suggesting `?type` for `type | null` and `type?` for `type | undefined`. The null prefix would be consistent with [JSDoc's nullable type](https://jsdoc.app/tags-type.html) and the undefined suffix would be similar to TypeScript's existing [optional parameters](https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters). Something else to consider is possibly merging the two to avoid ambiguity à la [Flow's maybe type](https://flow.org/en/docs/types/maybe/).

```ts
type T0 = ?number // => number | null
type T1 = number? // => number | undefined

function foo(a: ?number, b: string?): void
// => a: number | null
// => b: string | undefined
```

Note that `a?: T` and `a: T?` are [not the same](https://www.typescriptlang.org/play?ts=4.9.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAYAKKALnlWQFsAjEGAGnhoH5zLb6BKd6umAFChIsBCnTY8SAIwlenRs3n94AH3hpQiLKhDAeFPvQEDExaV1OyLQA); the former doesn't require `a` to present while the latter does.

**Comment by STRd6** [comment]
Thanks for opening this issue it's definitely something we'd want to add to Civet. Here's a link to a related discussion: https://github.com/DanielXMoore/Civet/discussions/144

**Comment by STRd6** [comment]
I would lean towards Flow semantics:

```typescript
// .civet
function foo(a: ?number, b: string?): void
// ↓↓↓ .ts
function foo(a?: number? | null, b: string?)
```

**Comment by gustavopch** [comment]
I think the code will be harder to read if both prefixes and suffixes are used. I'd rather have a different symbol in the same position than the same symbol in a different position, especially when the types are long.

Also, there's a difference in readability between prefix and suffix.

Preffix:
```ts
x: ?{
  foo: ALotOf
  bar: ?VisualNoiseThat<Your, Eyes>
  baz: WillTry<ToSkip>
  qux: ?WhenQuickly<SkimmingThrough, TheCode>
}
```

Suffix:
```ts
x: {
  foo: ALotOf
  bar: VisualNoiseThat<Your, Eyes>?
  baz: WillTry<ToSkip>
  qux: WhenQuickly<SkimmingThrough, TheCode>?
}?
```

IMO, the suffix is easier to miss than the prefix.

But going a step backwards, how many cases is it even useful to distinguish between `null` and `undefined`? I do it in some rare cases, but I'd be fine to have `?T` mean `T | null | undefined` for most cases and then in the specific cases where I actually need to distinguish, I can be more verbose and explicit with `T | null` and `T | undefined` so nobody reading the code misunderstands it.

**Comment by edemaine** [comment]
Agreed with @gustavopch. If `?T` and `T?` meant different things where one is `null` and one is `undefined`, I doubt I would ever remember which. I think `| null | undefined` is what needs the shorthand the most, and I like that it matches Flow.

**Comment by STRd6** [comment]
The other nuance about Flow semantics is that object properties are required and function parameters are truly optional. Since I don't know enough about the reasoning why Flow chose to do it that way I'd defer to their semantics (especially if we use the same symbol in the same position they do). Maybe if someone can find a link to the original discussion in the Flow project it could add some information to expand/modify the design further.

**Comment by waterstone15** [comment]
Civet could use `nothing` or `nil` as a shorthand for `null | undefined`.

**Comment by waterstone15** [comment]
Civet could use `nothing` or `nil` as a shorthand for `null | undefined`.

`nothing`/`nil` isn't quite as compact as the `?` shorthand, but it would offer some improvement. Plus, this avoids further overloading the meaning of `?`. 'nil' or 'nothing' would be also more distinctly searchable in the docs for newcomers.

**Comment by GoToLoop** [comment]
`nil` to represent both `null | undefined` seems neat. `void` would be nice too.

**Comment by edemaine** [comment]
`void` already has a different meaning in TypeScript. I personally prefer the `?` operator but shorthand for `null | undefined` also seems interesting.

**Comment by STRd6** [comment]
Something to note, it's already possible to do `type nil = null | undefined` in userspace TS: https://www.typescriptlang.org/play?#code/C4TwDgpgBAdglgGygXlgVwUgPlNMAmEAZnDBPgFAWiRQAaKsi140AmowM7ABOpA5lBzwEFIA

My personal feeling is that most of the value of this proposal would be extending TS syntax with the prefix `?` and matching Flow semantics.

**Comment by edemaine** [comment]
This is now (mostly) solved; see https://civet.dev/reference#optional-types

In particular, `T?` means `T | undefined` (for compatibility for most other `?` types), and `T??` means `T | undefined | null`. We didn't define a meaning for `?T` but we could in the future.
