### ISSUE TITLE
interface can't have more than 1 extends; class can't have both extends & implements!

### ISSUE THREAD

**Issue by GoToLoop** [DanielXMoore/Civet#254]
Civet fails to transpile `interface A < B, C` to TS.

Civet transpiles `class Q < W implements A, B` as `class Q extends W(implements(A, B))`.

BtW, it'd be nice for Civet to have a shorthand for keyword `implements` as maybe `<<`:
`class Q < W << A, B`

https://Civet-Web.Vercel.app/#aW50ZXJmYWNlIEEgPCBCCiAgICBmb286IHN0cmluZwoKLy9pbnRlcmZhY2UgQSA8IEIsIEMgLy8gZmFpbHMKLy8gICAgZm9vOiBzdHJpbmcKCmNsYXNzIFEgPCBXCiAgICBmb286IHN0cmluZwoKY2xhc3MgUSBpbXBsZW1lbnRzIEEsIEIKICAgIGZvbzogc3RyaW5nCgpjbGFzcyBRIDwgVyBpbXBsZW1lbnRzIEEsIEIgLy8gVyhpbXBsZW1lbnRzKEEsIEIpKQogICAgZm9vOiBzdHJpbmc=

**Comment by STRd6** [comment]
Adding `implements` to `ForbiddenImplicitCalls` should fix it being parsed as function application.

Changing `InterfaceExtendsClause?` to `InterfaceExtendsClause*` may fix the multiple extends for interfaces.
