### ISSUE TITLE
Support Typescript 5.0 const modifier on type parameters

### ISSUE THREAD

**Issue by adrianhunter** [DanielXMoore/Civet#260]
Typescript 5.0 introduces a new "const" modifier for type parameters. Related PR: https://github.com/microsoft/TypeScript/pull/51865

Where is the const type modifier allowed?
The const modifier is permitted on type parameters of functions, methods, and classes. It is an error to apply the const modifier to type parameters of interfaces and type aliases.

Would be great to have this in civet, as I already have some code that uses this new feature. 

How to use this new feature in normal typescript with vscode?
`npm install typescript@next`  in any project, then select this specific typescript version in the bottom right of vscode, or directly add this to your vscode settings.json 
```"typescript.tsdk": "node_modules/typescript/lib"```

**Comment by STRd6** [comment]
Related: https://github.com/microsoft/TypeScript/issues/51362

Looks like TS will have the 5.0 final release on March 14th so we'd want to be compatible before then.

**Comment by STRd6** [comment]
Fixed in https://github.com/DanielXMoore/Civet/pull/502/commits/a28e79663b50d0f385366478a31c46f0855bef52
