### ISSUE TITLE
Publish editor exention to open-vsx

### ISSUE THREAD

**Issue by tomByrer** [DanielXMoore/Civet#265]
For those of us who have joined the Rebel Alliance & want privacy in our code editors (eg use [VSCodium](https://vscodium.com/)), could you please publish the LSP at open-vsx.org?
[Instructions require an account](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

I'm fine now, I can just copy/paste folders & config JSON from VSCode, so low priority.

**Comment by STRd6** [comment]
Published: https://open-vsx.org/extension/DanielX/civet
