### ISSUE TITLE
A coincidence 

### ISSUE THREAD

**Issue by v3ss0n** [DanielXMoore/Civet#267]
I just found out this framework on the day my pet civet died.his name was Happy and he was 3 years old.
Can he be your mascot?
![IMG_20211111_111129](https://user-images.githubusercontent.com/419606/213919726-c8194eb0-4d31-4e3f-85e5-8e106764ec09.jpg)
![IMG_20220421_043237_BURST1](https://user-images.githubusercontent.com/419606/213919729-5acd9ddb-a932-4ed2-9d1c-b26ea744e197.jpg)
![IMG_20220405_012824](https://user-images.githubusercontent.com/419606/213919731-0f05a7f4-fc5e-40d3-b91a-092a5f175671.jpg)
![IMG_20211111_111239](https://user-images.githubusercontent.com/419606/213919734-228c2fab-42f0-423b-ad6c-f52e30d128c9.jpg)

**Comment by STRd6** [comment]
We are sorry for your loss, rest in peace little fellow.
