### ISSUE TITLE
CLI: bad path escapes in Windows

### ISSUE THREAD

**Issue by tomByrer** [DanielXMoore/Civet#268]
```bash
>> /d/doc/prog/s-m-m/node-ytdl-core (master)
$ civet example\get_info.civet
exampleget_info.civet failed to load:
[Error: ENOENT: no such file or directory, open 'D:\doc\prog\s-m-m\node-ytdl-core\exampleget_info.civet'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\doc\\prog\\s-m-m\\node-ytdl-core\\exampleget_info.civet'
}
```

**Comment by edemaine** [comment]
What shell are you using? Most shells will interpret `\g` as `g` (before giving the argument to Civet) which based on the error message looks to be the problem.

You should do one of the following:
* Use `/g` (yes, I realize you're on Windows, bit this usually works)
* Use `\\g`
* Wrap the path name in quotes
* Use tab auto-completion which usually does one of the above.

**Comment by tomByrer** [comment]
> What shell are you using?

Bash for Git; tends to be what many devs use.
But you're right, I should auto-complete.
