### ISSUE TITLE
JS won't run in .civet (arrow func parameter)

### ISSUE THREAD

**Issue by tomByrer** [DanielXMoore/Civet#269]
I was hoping to progressively switch to Civet, but guess not?
All I did was rename the [`.js` file](https://github.com/fent/node-ytdl-core/blob/master/example/get_info.js) to `.civet`

JS file just worked fine in Node.

```bash
$ civet get_info.civet
get_info.civet crashed while running:
ReferenceError: info is not defined
    at Object.<anonymous> (D:\doc\prog\s-m-m\node-ytdl-core\example\get_info.civet:8:17)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at cli (C:\Users\tomby\AppData\Local\pnpm\global\5\.pnpm\@danielx+civet@0.5.50\node_modules\@danielx\civet\dist\civet:328:29)
```

**Comment by edemaine** [comment]
We're planning to add a `jsCompat` flag that supports single-argument arrow functions without a paren (at the cost of no longer supporting zero-argument arrow functions without parens). Meanwhile you'll have to add parens.

**Comment by tomByrer** [comment]
> Meanwhile you'll have to add parens.

Ah, that's fine
But could the error output reflect that please?
(I'm good at idiot-proofing, since I belong to that club!)

**Comment by tomByrer** [comment]
Suggestion for a work-around for in-line functions?
```js
  fs.writeFile(filepath, json, err2 => {
    if (err2) throw err2;
  });
```

But like I said, I'd prefer a progressive encasement into Civet.

**Comment by edemaine** [comment]
I'm not sure what your suggestion is exactly. That code [already has a meaning](https://civet.dev/playground?code=ZnMud3JpdGVGaWxlKGZpbGVwYXRoLCBqc29uLCBlcnIyID0%2BIHsKICAgIGlmIChlcnIyKSB0aHJvdyBlcnIyOwogIH0pOw%3D%3D): an implicit function call to `err2` with a zero-argument arrow function.

We simply can't have parenless notation for both zero- and one-argument arrow functions (in a world with implicit function calls).

**Comment by edemaine** [comment]
Moving to #270, but if you come up with other workarounds, let us know!

**Comment by STRd6** [comment]
We might also be able to recommend a prettier config that maximizes compatibility.
