### ISSUE TITLE
Arrow functions and parentheticals on their own line

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#272]
The following input transpiles to itself:

```coffee
x
(z) => z
```

But JavaScript has trouble with it, trying to parse it as a function call `x(z)` and then failing with `SyntaxError: Malformed arrow function parameter list`.

Perhaps even grosser is that the following gets treated like a function call, but I don't think it should.

```coffee
x
(z)
```

Perhaps we can automatically add semicolons in these cases?

**Comment by STRd6** [comment]
A simple-ish fix would be to add a look-ahead in `StatementDelimiter` like:

```
&( Samedent "(" ) -> ";"
```

Before the `&EOS` rule.

**Comment by STRd6** [comment]
Probably create and use an `InsertSemicolon` rule to keep token and location info.

**Comment by edemaine** [comment]
This approach works pretty well, though there are some issues:

* If we end up adding an implicit return to the following statement, we don't need to have added a semicolon. (No harm done though.)
* I worry about code like this which would end up adding parens that weren't in the input:
  ```ts
  x
  {y: z} = obj
  ```
  This code has [a different problem](https://civet.dev/playground?code=eAp7eTogen0gPSBvYmo%3D) right now though.

For the second issue in particular, I wonder about doing this in a second pass. Maybe a `processBlocks`? Let me know what you think.

**Comment by STRd6** [comment]
Good points. Maybe it would make more sense to do this in `processBlocks`. I've also been thinking about doing even more processing later in the AST. We may even be able to have it handle expressionizing everything as well.

**Comment by STRd6** [comment]
If we want a quick hacky solution for the meantime:

```
&( Samedent ( "(" / "{" / "[" ) ) -> ";"
```

**Comment by edemaine** [comment]
Fair enough. Tomorrow I can submit a PR for the hacky solution I put together.
