### ISSUE TITLE
Pipe assignment operator `|>=`

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#290]
Like `+=`, we should add a pipe assignment operator `|>=` that works like so:

```coffee
lhs |>= func1 |> func2 |> func3
↓↓↓
lhs = func3(func2(func1(lhs)))
```

In particular, this gives a reasonable alternative to LiveScript's "accessignment":

```coffee
document.title .= toUpperCase()
↓↓↓
document.title = document.title.toUpperCase()
```

Instead we can use this more general operator:

```coffee
document.title |>= &.toUpperCase()
```

**Comment by GoToLoop** [comment]
Seems like we're also gonna need `|>.=` & `|>:=` for `let` & `const` respectively.

**Comment by edemaine** [comment]
@GoToLoop I don't think so:  `|>=` and `+=` and similar operators only make sense when the left-hand side already has a value, so it must already be defined.
