### ISSUE TITLE
Remove non-civet file activationEvents ?

### ISSUE THREAD

**Issue by lorefnon** [DanielXMoore/Civet#30]
Do we need the non-civet-file activation events [here](https://github.com/DanielXMoore/Civet/blob/2cabc7376e73b3fe8b2a904fb778398f31ec30e5/lsp/package.json#L20-L21) ?

I'd like civet extension to not take over for other non-civet related pure-ts/js projects. I can disable it per workspace but I juggle between a dozen plus repos quite frequently so its not ideal.

**Comment by STRd6** [comment]
It's convenient if you have a mixed civet/ts project so that you won't need to open a `.civet` file before a `.ts` file to be handle `.civet` imports from TS.

I'd lean towards keeping it and recommend using "Disable (Workspace)" for non-civet TS projects.

**Comment by lorefnon** [comment]
Oh, seems like I can install & disable the extension, and then enable it for specific workspace. That solves my issue - sorry to bother.

**Comment by STRd6** [comment]
No worries, always good to bring up any difficulties. Glad the Enable/Disable works for you. I might add a note about it in the README.
