### ISSUE TITLE
-> doesn't work in interfaces

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#305]
This works ...

```
interface Cow
    type: 'cow'
    giveMilk : =>
```

... but this doesn't:
```
interface Cow
    type: 'cow'
    giveMilk : ->
```

Shouldn't it? I get:

```
/Users/zolo/project/program/test.civet:17:17 Failed to parse
Expected:
	TypeIndexSignature "readonly"
	DecimalBigIntegerLiteral /(?:0|[1-9](?:_[0-9]|[0-9])*)n/
	BinaryIntegerLiteral /0[bB][01](?:[01]|_[01])*n?/
	OctalIntegerLiteral /0[oO][0-7](?:[0-7]|_[0-7])*n?/
	HexIntegerLiteral /0[xX][0-9a-fA-F](?:[0-9a-fA-F]|_[0-9a-fA-F])*n?/
	DecimalLiteral /(?:0|[1-9](?:_[0-9]|[0-9])*)(?=\.(?:\p{ID_Start}|[_$]))/
	DecimalLiteral /(?:0|[1-9](?:_[0-9]|[0-9])*)(?:\.(?:[0-9](?:_[0-9]|[0-9])*))?/
	DecimalLiteral /(?:\.[0-9](?:_[0-9]|[0-9])*)/
Found: ">"
ts
```

**Comment by edemaine** [comment]
Indeed, `->` currently is not allowed for types. I guess it should mean the same thing as `=>`?

**Comment by zolomatok** [comment]
Hmmm, I guess it makes sense that they are not supported, because regular functions don't work as type hints in TS either.

And transpiling `->` into `() => void` is misleading, since `->` is explicitly _not_ an arrow function. 🤔

**Comment by zolomatok** [comment]
I think we should close this issue and leave the implementation as is.

**Comment by STRd6** [comment]
We do something similar in `class` definitions with `coffeeCompat` enabled

```typescript
"civet coffeeCompat"

class Cow
  type: 'cow'
  giveMilk: ->

---

class Cow {
  type = "cow";
  giveMilk() {}
}
```

We may want to make that a default behavior for classes and interfaces especially because the existing transpilation of `key: ->` is pretty broken.

**Comment by edemaine** [comment]
To be clear, the following already has a meaning (literal type for `type`)

```ts
class Cow
  type: 'cow'
```

I assume you mean that the default behavior should be the following?

```ts
class Cow
  type: 'cow'
  giveMilk: ->

---

class Cow {
  type: "cow"
  giveMilk: () => void
}
```

**Comment by zolomatok** [comment]
> should be the following
```
class Cow {
  type: "cow"
  giveMilk: () => void
}
```

This still translates `->` into an arrow function though which might explicitly not what the author was going for, else they would have typed `=>`.

**Comment by edemaine** [comment]
Counterargument: TypeScript's `=>` type [allows for a `this` specifier](https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function), so it's really appropriate for a `->` function too.

**Comment by STRd6** [comment]
I was thinking that for classes and interfaces we should compile like so:

```typescript
class Cow
  type: 'cow'
  giveMilk: ->

interface Cow
  type: 'cow'
  giveMilk: ->

interface Cow2
  type: 'cow'
  giveMilk: -> number

---

class Cow {
  type = "cow";
  giveMilk() {}
}

interface Cow {
  type: "cow"
  giveMilk(): void
}

interface Cow2 {
  type: "cow"
  giveMilk(): number
}
```

**Comment by edemaine** [comment]
This would prevent [TypeScript field declarations](https://www.typescriptlang.org/docs/handbook/2/classes.html#fields).

**Comment by STRd6** [comment]
It seems like field definitions would mostly be fine, `x: ->` would imply a class method `x` rather than a field definition for a function.

```
class Point {
  x: number;
  y: number;
  z: Function;
}
```

There are other places where we modify `->` to be a function `fn := ->` and in class bodies with `coffeeCompat`. `=>` could remain unchanged as a field definition in TS.

**Comment by edemaine** [comment]
@STRd6 Could you clarify your proposal for `class`es?  You wrote:

```ts
class Cow
  type: 'cow'
  giveMilk: ->
---
class Cow {
  type = "cow";
  giveMilk() {}
}
```

But this is surely not what we want for `type`; it should remain a TypeScript field declaration `type: "cow"`.

What I'm less clear about is whether you intended to compile `giveMilk` to a function (CoffeeScript style) or a field declaration (TypeScript style). I would have expected TypeScript style, but you seem to be leaning toward CoffeeScript style?

**Comment by STRd6** [comment]
@edemaine ok now that I've slowed down and read more carefully that makes sense. Here's an updated proposal.

For classes:

```typescript
class X
  fn1: ->
  fn2 = ->
  fn3: =>
  fn4 = =>
---
class X {
  fn1: function() {} // currently doesn't work, should become TS field definition
  fn2 = function() {} // works
  fn3: () => undefined // currently doesn't work, empty block doesn't become undefined
  fn4 = () => undefined // currently doesn't work, empty block doesn't become undefined
}
```

For interfaces:

```typescript
interface X 
  fn1: ->
  fn2: =>
---
interface X {
  fn1(): void // Currently doesn't work but could
  fn2: () => void
}
```

**Comment by edemaine** [comment]
Sorry, I'm still confusing.  I feel like the existing behavior for classes `fn2` through `fn4` is pretty good:

```ts
class X
  fn2 = ->
  fn3: =>
  fn4 = =>
---
class X {
  fn2 = function () {}
  fn3: () => void
  fn4 = () => {}
}
```

I think the main issue is whether `fn1` should work in both classes and interfaces. I like the idea of compiling `->` into a method form for interfaces, though I guess that doesn't make sense for classes.  I also feel like just treating `->` exactly like `=>` in the context of a type is pretty reasonable... Do we have a situation where we'd like to do something special?

**Comment by STRd6** [comment]
It may not matter much either way. There is a subtle difference between method and arrow with `--strictFunctionTypes` but I don't think we want to emphasize that. Maybe making `->` always be `=>` in types is the way to go (at least until a compelling reason otherwise emerges).
