### ISSUE TITLE
Deno: Don't change import path file extensions

### ISSUE THREAD

**Issue by phil294** [DanielXMoore/Civet#306]
Civet seems to change import paths from `.ts` to `.js`, even when you're specifying `-o .ts` output.

I'm using Civet on a Deno project and this breaks Deno logic. For example,

```ts
// Civet
import { DB } from "https://deno.land/x/sqlite/mod.ts"
```
becomes
```js
// JS
import { DB } from "https://deno.land/x/sqlite/mod.js"
```

**Comment by edemaine** [comment]
[The code](https://github.com/DanielXMoore/Civet/blob/80e9e876f4eb02d82453ca49fa328505cd69254b/source/parser.hera#LL3394-L3397) says that this is a workaround to fix https://github.com/microsoft/TypeScript/issues/42151 — `import "t.ts"` causes TypeScript to throw "An import path cannot end with a '.ts' extension. Consider importing './t.js' instead."  I guess this doesn't happen with Deno.  I guess we need another command-line / compiler option?

**Comment by STRd6** [comment]
I think TS 5 made some progress on fixing this. We should add a config in the meantime.

**Comment by STRd6** [comment]
@phil294 Fixed in Civet v0.5.60, let me know how it goes!

**Comment by phil294** [comment]
perfect, thank you

**Comment by phil294** [comment]
strictly speaking, this is not an exclusive Deno phenomenon though, as importing from urls is es6 browser spec. It's rather unlikely that you would want to import a JS file which ends on `.ts` in your browser though, so I think the wording is fine

**Comment by edemaine** [comment]
I wonder whether this affects Bun too?

**Comment by eevleevs** [comment]
While this works, the LSP still complains that `An import path cannot end with a '.ts' extension`. Can we disable it?
