### ISSUE TITLE
Coffeescript bug: postfix if

### ISSUE THREAD

**Issue by greghuc** [DanielXMoore/Civet#308]
### Coffeescript bug (parse error)

```
"civet coffeeCompat"

[1,2,3].forEach((value) -> console.log(value) if true)      
```
gives
```
"civet coffeeCompat"

[1,2,3].forEach((value) -> console.log(value) if true)      
                                                     ^ ParseError
```

### Playground links

Coffeescript: https://coffeescript.org/#try:%5B1%2C2%2C3%5D.forEach((value)%20-%3E%20console.log(value)%20if%20true)%20%20%20%20%20%20
Civet: https://civet.dev/playground/?code=ImNpdmV0IGNvZmZlZUNvbXBhdCIKClsxLDIsM10uZm9yRWFjaCgodmFsdWUpIC0%2BIGNvbnNvbGUubG9nKHZhbHVlKSBpZiB0cnVlKSAgICAgIA%3D%3D

**Comment by greghuc** [comment]
[Rewriting over multiple lines](https://civet.dev/playground/?code=ImNpdmV0IGNvZmZlZUNvbXBhdCIKClsxLDIsM10uZm9yRWFjaCgodmFsdWUpIC0%2BCiBjb25zb2xlLmxvZyh2YWx1ZSkgaWYgdHJ1ZQopICAgICAgCgoKCgoK) fixes the error:

```
"civet coffeeCompat"

[1,2,3].forEach((value) ->
 console.log(value) if true
)      
```

**Comment by greghuc** [comment]
This bug is more of an FYI. I fixed it in the Coffeescript codebase I'm exploring porting to Civet by switching to the parsable form.

**Comment by edemaine** [comment]
I think this is a general issue with trailing `if`s not being able to generate `?:` expressions. I've noticed it in JSX, where I often write:

```jsx
<div x={y if z}/>
```

This [works in CoffeeScript](https://coffeescript.org/#try:%3Cdiv%20x%3D%7By%20if%20z%7D%2F%3E) but [not Civet](https://civet.dev/playground?code=PGRpdiB4PXt5IGlmIHp9Pg%3D%3D), and would be nice to fix.
