### ISSUE TITLE
Allow TS non-null assertion in object literal context

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#313]
```typescript
{
  isOpen,
  inputValue!,
}
---
{
  isOpen,
  inputValue: inputValue!,
}
```

**Comment by edemaine** [comment]
[Already done](https://civet.dev/playground?code=ewogIGlzT3BlbiwKICBpbnB1dFZhbHVlISwKfQ%3D%3D). Or did you have an instance where it doesn't work?

**Comment by STRd6** [comment]
I didn't even realize! Was just programming in TS today and felt like Civet should have this... little did I know it already did!
