### ISSUE TITLE
Unary operator followed by a space

### ISSUE THREAD

**Issue by phil294** [DanielXMoore/Civet#324]
```civet
! x
```
fails with `ParseError`

**Comment by STRd6** [comment]
Thanks for the report! Currently unary operators don't allow whitespace between the operator and the operand. It may be possible to relax this for some operators in some situations but I'll have to think about it further.

**Comment by STRd6** [comment]
My main concern is if we add a future `a ! b` binary op then I wouldn't want people to have gotten used to `! x` in the meantime.

**Comment by edemaine** [comment]
Note: `not` (currently behind `coffeeNot` flag, but see #287) allows whitespace after it, so that's an alternative to use.

**Comment by STRd6** [comment]
We're not currently planning to change this but please re-open the issue if you have other ideas about it.
