### ISSUE TITLE
Incorrect output without -c

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#329]
The following code

```
let animals = [{name: 'Fluffy'}, {name: 'Fido'}]
let test = animals.map (if &.name == 'Fluffy' then 'Cat' else 'Dog')
```

translates to the **correct** TS code if I do
`civet -c ./test.civet`

However, when I run
`civet ./test.civet`

I get
```
./test.civet crashed while running:
TypeError: Cat is not a function
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/zolo/project/arena/test.civet:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at cli (/Users/zolo/project/arena/node_modules/@danielx/civet/dist/civet:329:29)
```

Running it under `Bun` shows:
<img width="468" alt="Screenshot 2023-02-04 at 20 01 06" src="https://user-images.githubusercontent.com/11703903/216784918-02b30a95-8f4e-4255-be23-0e79aa59a453.png">

**Comment by zolomatok** [comment]
Civet **0.5.62**

**Comment by STRd6** [comment]
I think what you want is closer to:

```
let animals = [{name: 'Fluffy'}, {name: 'Fido'}]
let test = animals.map &.name == 'Fluffy' ? 'Cat' : 'Dog'
```

Breaking down the original:

```
let animals = [{name: 'Fluffy'}, {name: 'Fido'}]
const condition = &.name == "Fluffy"
let test = animals.map (if condition then "Cat" else "Dog")
```

the `if` doesn't get pushed into the `&.block` and is instead choosing which string to pass to map.

Let me know if that makes sense!

**Comment by zolomatok** [comment]
Ah, yeah, I get it, thank you Daniel!
Looks like the `-c` version of the original doesn't work either when the TS code is actually tested, I was just bamboozled.

If `if`s don't work here, is there any way to have a condition that's not returning anything? Where a ternary operator doesn't help. Eg:
`animals.forEach console.log 'test' if &&.name == 'Fluffy'`

This doesn't work of course, but something similar? 🤔

**Comment by STRd6** [comment]
Probably something like this:

```
animals.forEach &.name == 'Fluffy' ? console.log 'test' : null
```

**Comment by zolomatok** [comment]
Ah, yes, of course, thank you, I was blanking out.
