### ISSUE TITLE
`{f().g}` no longer works

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#332]
Turns out #330 is a little buggy: `{f().g}` is now treated like the method definition `{f() &.g}` instead of the object literal shorthand.

Thoughts on how to best exclude this? A simple fix is to try matching object literal shorthand first. But maybe we just need to `!Dot` for method bodies.

**Comment by STRd6** [comment]
`!Dot` in method bodies makes sense to me.
