### ISSUE TITLE
CLI can't use ref functions multiple times

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#339]
The CLI (run simply as `civet`) runs commands multiple times in the global context. The result is that multiple `const` declarations cause an error like so:

![image](https://user-images.githubusercontent.com/2218736/217379712-88f6f8fe-4d27-4669-acdb-812039c760bd.png)

Should we change automatic ref functions from `const` to `var`? Or get the parser to return prelude content separately so we can deduplicate in the CLI?

**Comment by GoToLoop** [comment]
Well, Civet got `:=` for `const` and `.=` for `let`.
Maybe Civet should have 1 just for `var` as well.
And Civet should always honor it when transpiling its code.

**Comment by edemaine** [comment]
The issue here is that `1 %% 5` compiles to
```js
const modulo: (a: number, b: number) => number = (a, b) => ((a % b) + b) % b;
modulo(1, 5);
```

The user didn't write `const` (or `:=`); Civet did. The result is pretty confusing behavior that you can only use the `%%` operator once.

**Comment by GoToLoop** [comment]
Oh! Even TS uses `var` when it adds hidden functions to our for the obvious reasons that both `var` & `function` can redeclare existing variables.

Civet could do the same for all of its extra hidden functions:
`function modulo(a: number, b: number) { return (a % b + b) % b; }`

**Comment by GoToLoop** [comment]
A more boilerplate implementation based on TS' ___decorate_ hidden `var` function:
```ts
var __modulo: (a: number, b: number) => number = this?.__modulo || 
  function (a: number, b: number) { return (a % b + b) % b; };
```

**Comment by STRd6** [comment]
Using `var` is probably fine as a quick fix until we think of something better.
