### ISSUE TITLE
Mixins for Civet

### ISSUE THREAD

**Issue by bennidi** [DanielXMoore/Civet#35]
Thank you very much for your efforts on Civet. I am intrigued because I used to love CoffeeScript and wrote various projects with it.

I built a small library to make CoffeeScript support Mixins or Traits in an idiomatic way.

Maybe check out this code and tell me if you like the style of it and if it's worth porting it to Civet.

https://github.com/bennidi/coffee-latte/blob/master/src/mixins.spec.coffee

**Comment by STRd6** [comment]
Hi, thanks for the feedback!

A primary goal of Civet is to stick to JS semantics as much as possible. In the case of mixins we'll probbaly converge on [ESDecorators](https://github.com/tc39/proposal-decorators) when/if it becomes a standard. Civet currently supports  decorators using `@@decorator` syntax (a single `@` is ambiguous with class static fields and methods currently).

Thanks for sharing the code sample it looks pretty close to the direction that JS/TS is heading with decorators and I'm always happy to find inspiring ways to make syntax nicer.

I'm glad you like Civet and hope that it will make your wildest dreams come true.
