### ISSUE TITLE
Expressionized statements and await

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#355]
Should  expressionized statements that contain an await also await?

```civet
let a = try { await b } catch { c }
```

```
let a = await (async () => {
  try {
    return await b;
  } catch () { return c }
})();
```

- [ ] Fix `catch { c }`
- [x] Implicit `async`
- [x] Add implicit `await` when `await` is used in an expressionized statement.

**Comment by STRd6** [comment]
CoffeeScript does this and it seems like a good idea.

**Comment by gustavopch** [comment]
- What if you don’t want to await and just want the promise?
- Return statements inside the expression may behave unexpectedly because of the IIFE.

**Comment by STRd6** [comment]
> * What if you don’t want to await and just want the promise?

Hmm, not sure. It's probably 90+% of the time you'd rather have the result. And if your function is already async then it will get bundled into the outer promise. Maybe we need some more examples to think it through. `Promise.all`, etc.

> * Return statements inside the expression may behave unexpectedly because of the IIFE.

Already an issue that should be solved: https://github.com/DanielXMoore/Civet/issues/202

**Comment by gustavopch** [comment]
Sometimes I want to start loading something as soon as possible, but I don't need it yet, so I don't await the promise. Then when I actually need it, I await knowing it's already loaded or almost.
```ts
const stuffPromise = loadStuff()

const callback = () => {
  const stuff = await stuffPromise
  // ...
}
```

**Comment by edemaine** [comment]
Certainly promises shouldn't be auto-awaited in general. The question here is whether functions *automatically injected by Civet* should be auto-awaited. I think the answer is "yes" but it is probably worth looking at examples.

Currently Civet adds wrapping functions to for loops (to accumulate the results) and try expressions. (A near-term other use is do expressions.) Clearly if the wrapped content contains `await`, then the wrapping function needs to be `async`.

Let's consider a for loop where some iterations await and others don't:

```coffee
out := for item of list
  if item.url
    await fetch item.url
  else
    item.data
```

I expect `out` to be an array here, not a Promise. And I think the right semantics is exactly to `await` the wrapping function, which should be equivalent to waiting for all wrapped `await`s to complete. If you didn't want to `await`, don't write `await`...

**Comment by gustavopch** [comment]
> If you didn't want to `await`, don't write `await`...

My example was not the best. I was actually imagining something like the following where I want to await inside the block:
```ts
const stuffPromise = (async () => {
  const response = await fetch(...)
  return response.json()
})()

const callback = () => {
  const stuff = await stuffPromise
  // ...
}
```

But I agree with your points.
