### ISSUE TITLE
return =

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#361]
It's common to want to do some cleanup before actually returning a value.  Declaring a variable to store that value seems superfluous, and less declarative.  Let's use `return` like a variable we can assign to!

```coffee
function f(list)
  for item of list
    if match item
      return = item
      break
  if (return.value) return += 1
  list.destroy()
  return
---
function f(list) {
  var returnValue
  for (item of list) {
    if (match(item)) {
      returnValue = item
      break
    }
  }
  if (returnValue) returnValue += 1
  list.destroy()
  return returnValue
}
```

* [x] `return = foo` changes the default return value for a bare `return`
* [x] `return += foo` modifies that value
* [x] `return.value` lets you query that value. So `return = foo` is shorthand for `return.value = foo`.
* [ ] `return?` could test for whether a value has been specified i.e. shorthand for `return.value?`

Open question: If there's no explicit `return` at the end of a function using `return =`, should we return the last expression as usual, or should we return `return.value`?  For example, if there wasn't a bare `return` in the example above, we could plausibly compile to:

```coffee
  return ref = list.destroy(), returnValue ?? ref
```

I'm not sure this is particularly intuitive, though.  Unlike JavaScript and Python, our functions don't have an implicit `return` at the end.  And I think it makes more sense for `return = foo` to set the default behavior of `return`, not implicit return.

On the other hand, I think we could override in the case of no implicit return, like so:

```coffee
  list.destroy();
---
  list.destroy();
  return returnValue
```

**Comment by STRd6** [comment]
My feeling is that if a `return =` is present anywhere inside a function it will override the implicit return. Otherwise you'd always need to change two places in code to switch between using `return =` and implicit returns.
