### ISSUE TITLE
returning value from try

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#369]
The following Civet code...
```
function someFunction()
  return 5
let x = try someFunction()
```

... generates ...
```
function someThrowingFunction() {
  return 5;
}

let x = (() => {
  try {
    return someThrowingFunction();
  } catch (e) {}
})();
```

... which runs into the error `Not all code paths return a value.(7030)` because the catch block doesn't include `return undefined` or `return null`.

**Comment by edemaine** [comment]
Seems reasonable to add `return` to the empty `catch` block, when adding implicit `return`s.
