### ISSUE TITLE
Implicit return not working in nested arrow function

### ISSUE THREAD

**Issue by tanishqmanuja** [DanielXMoore/Civet#378]
### Civet Code
```civet
arr := [1,2,3,4];
add := (x: number) -> (y: number) -> x + y;
arr.map add(1) |> console.log;
```

### Expected Outcome
```javascript
"use strict";

// src/index.civet
var arr = [1, 2, 3, 4];
function add(x) {
  return function(y) {
    return x + y;
  };
}
console.log(arr.map(add(1)));
```
Console : [ 2, 3, 4, 5 ]

### Actual Outcome
```javascript
"use strict";

// src/index.civet
var arr = [1, 2, 3, 4];
function add(x) {
  return function(y) {
    x + y;
  };
}
console.log(arr.map(add(1)));
```
Console : [ undefined, undefined, undefined, undefined ]

#### Note:
- What i have to do to solve this is pipe return like `add := (x: number) -> (y: number) -> x + y |> return;`
- If civet is a superset of TypeScript, and Typescript is a superset of javascript shouldn't this just work?

#### My setup:
tsconfig.civet.json
```json
{
	"compilerOptions": {
		"target": "ES2022",
		"module": "ES2022",
		"moduleResolution": "nodenext",
		"esModuleInterop": true,
		"strict": true,
		"skipLibCheck": true,
		"noEmit": true,
		"outDir": "dist"
	},
	"include": ["src"]
}
```

build.mjs
```javascript
import civetPlugin from "@danielx/civet/esbuild-plugin";
import esbuild from "esbuild";

esbuild
	.build({
		entryPoints: ["src/index.civet"],
		tsconfig: "tsconfig.civet.json",
		bundle: true,
		outdir: "./dist",
		platform: "node",
		plugins: [civetPlugin],
	})
	.catch(() => process.exit(1));
```

**Comment by shurko0x4cfd** [comment]
> add := (x: number) -> (y: number) -> x + y;

It works if avoid ";" at the end of the line:

`add := (x: number) -> (y: number) => x + y`

**Comment by tanishqmanuja** [comment]
Yes indeed but this behavior is strange.

**Comment by edemaine** [comment]
Oops, I missed the semicolon! That's an intentional feature; implicit return only works without a trailing semicolon. See the info box at https://civet.dev/cheatsheet#function

This is actually aligned with Type/JavaScript which doesn't do implicit return, except with one-line thick-arrow functions (this is a deviation, but you also weren't using a thick-arrow function).

**Comment by tanishqmanuja** [comment]
Ohh, My bad i didn't read the cheat sheet thoroughly. But yeah I see now the implementation choice the library has made.

Also i tried with fat arrow => syntax first, as one would do in typescript but result was same. Semi colon is the differentiating factor irrespective of the arrow -> or =>.

Thanks for the early response :) . You can assume this issue closed from my side if no further process is due.

**Comment by edemaine** [comment]
Thanks for the input! It is definitely good guidance for improving our documentation.

**Comment by edemaine** [comment]
We created this new documentation page inspired by this issue and other past hurdles folks have run into: <https://civet.dev/comparison>
Thanks again for the input!
