### ISSUE TITLE
Thick pipe bugs

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#387]
- [x] This puts the `return` in the wrong place:

```coffee
count |> &+1
||> (c) => console.log c
|> return
---
((c) => return console.log(c))(count+1),count+1
```

[Playground link](https://civet.dev/playground?code=Y291bnQgfD4gJisxCnx8PiAoYykgPT4gY29uc29sZS5sb2cgYwp8PiByZXR1cm4%3D)

1. I guess we need to take care not to put `return` inside a single-line fat-arrow function like this.
2. We're missing a `return` at the beginning of the line.

---

- [x] This seems to generate even worse code: (never mind the known issue of no refs)

```coffee
fetch url |> await
||> ({status}) =>
      console.log `Fetched ${url} with ${status}`
|> .json() |> await
||> (json) =>
      console.log `Parsed JSON ${json}`
|> return
---
(({status}) => {
      ((json) => {})(await console.log(`Fetched ${url} with ${status}`).json()),await console.log(`Fetched ${url} with ${status}`).json()
      return return console.log(`Parsed JSON ${json}`)
})(await fetch(url)),await fetch(url)
```

[Playground link](https://civet.dev/playground?code=ZmV0Y2ggdXJsIHw%2BIGF3YWl0Cnx8PiAoe3N0YXR1c30pID0%2BCiAgICAgIGNvbnNvbGUubG9nIGBGZXRjaGVkICR7dXJsfSB3aXRoICR7c3RhdHVzfWAKfD4gLmpzb24oKSB8PiBhd2FpdAp8fD4gKGpzb24pID0%2BCiAgICAgIGNvbnNvbGUubG9nIGBQYXJzZWQgSlNPTiAke2pzb259YAp8PiByZXR1cm4%3D)

3. Not sure how there got to be an empty block `{}`.
4. `return return` should never happen.

**Comment by STRd6** [comment]
😬

**Comment by STRd6** [comment]
I think for the next part I need to do something with `Samedent / IndentedFurther` for pipeline continuations

**Comment by edemaine** [comment]
Oh, I see, this is a general binary operator issue.  `+ x` on a following line currently always continues the previous expression, even if there's a function that might seem 'closed' by the dedentation.  With binary arithmetic this is maybe fine because we don't generally do arithmetic with functions (yet anyway 😉), but we see it with pipelines.

**Comment by edemaine** [comment]
That said, I could see replacing `__` with `_? / Samedent / IndentedFurther` in general for binary operators, not just pipes.

**Comment by STRd6** [comment]
I'm leaning in that direction generally, just need to keep testing and seeing where things break.
