### ISSUE TITLE
Pattern matching operator

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#391]
Proposal: `=~` (as in Perl and Ruby) and `is like` operator to do the equivalent of a single [pattern match `switch`](https://civet.dev/cheatsheet#pattern-matching). For example:

```coffee
match := x =~ [/\s+/, ...rest]
---
const match = Array.isArray(x) && x.length >= 1 && /\s+/.test(x[0])
const [, ...rest] = match ? x : [undefined]
```

```coffee
if x =~ [/\s+/, ...rest]
  console.log rest
---
if Array.isArray(x) && x.length >= 1 && /\s+/.test(x[0])
  const [, ...rest] = x
  console.log(rest)
```

(based on discussions in Discord)

**Comment by STRd6** [comment]
We may want to explore the details a little more. Maybe `:~` if it is making const binding match declarations?

```
[/\s+/, ...rest] :~ x
```

**Comment by STRd6** [comment]
This may be satisfied by conditional bindings. Since you'd need to check the result of the match anyway you'll always need an if condition. At least I don't know of any compelling examples where a standalone operator would be better than what we added recently.

**Comment by edemaine** [comment]
Good point; we'd just need to extend conditional lexical binding to include pattern matching. (Without the condition in not sure it makes sense, as you say.) 

The order is flipped though. Consider for example:

```coffee
if /\s+/ := string
  console.log "whitespace"
```

I wonder if it makes sense to offer a flipped version. But instead of `=~` it could be spelled `=:`.

```coffee
if string =: /\s+/
  console.log "whitespace"
```

**Comment by STRd6** [comment]
It looks like conditional declarations handle this pretty well:

https://civet.dev/playground?code=aWYgWy9ccysvLCAuLi5yZXN0XSA6PSB4CiAgY29uc29sZS5sb2cgcmVzdA%3D%3D

```civet
if [/\s+/, ...rest] := x
  console.log rest
```

**Comment by edemaine** [comment]
I agree this covers many use cases, where you want to fork immediately depending on whether something matches a pattern. But I've had a couple of occasions recently where I want to store a boolean for whether there's a match. Current example:
```coffee
infinite := end matches {type: "Identifier", name: "Infinity"}
```
To use pattern matching, I need to do something like
```coffee
infinite := if {type: "Identifier", name: "Infinity"} := end then true
//or
infinite := switch end
  {type: "Identifier", name: "Infinity"} then true
```

Partly it'd be nice to have notation for `if ... then true else false`. I guess we'd normally write that `Boolean ...` so one option is:
```coffee
infinite := Boolean {type: "Identifier", name: "Infinity"} := end
```
If we wanted a new keyword:
```coffee
infinite := whether {type: "Identifier", name: "Infinity"} := end
```
Probably there are many more options... but perhaps worth kicking this one around some more.

**Comment by STRd6** [comment]
Would a custom inline operator that people can declare handle this?

**Comment by edemaine** [comment]
An idea for an operator that doesn't need a new keyword: another extension of `is`. We already have `is not` and `is in` (though admittedly both `not` and `in` are keywords now). We could add an `is like`:
```coffee
infinite := end is like {type: "Identifier", name: "Infinity"}
```
This would prevent us from comparing something to a variable `like` via the `is` operator, but if we like this notation, maybe that's a small price to pay?

**Comment by STRd6** [comment]
`is like` sounds good to me.
