### ISSUE TITLE
`catch` braced block without argument

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#400]
https://civet.dev/playground/?code=dHJ5IGEgY2F0Y2ggeyBjIH0%3D

```
try a catch { c }
--- actual
try {
  a;
} catch ({ c }) {}
--- expected (or similar)
try {
  a;
} catch(e) {
  c;
}
```

_Originally posted by @STRd6 in https://github.com/DanielXMoore/Civet/issues/399#issuecomment-1437453463_

**Comment by STRd6** [comment]
Now that I'm looking at this more closely it may be correct as is. :|

**Comment by STRd6** [comment]
Seems correct.

**Comment by edemaine** [comment]
I think it's a bit awkward for JavaScript compatibility.  Here's a more real example:

```js
function parse(x) {
  try {
    JSON.parse(x)
  } catch {
    defaultObject
  }
}
```

Admittedly I'm relying on implicit returns here, so there's some Civet buy-in.  On the other hand, it's nice to match exception objects without having to wrap in parens...

Perhaps we could have the best of both worlds like so?
* `catch !OpenBrace expr block` works as usual; `block` is optional
* `catch &OpenBrace expr block` *requires* `block`.
* `catch block` is the third thing to try, and `block` is optional here (as in CoffeeScript)

The idea is that it's not useful to destructure without having a block, because bindings are local.  Of course, I say that, but we could have

```js
try
  foo
catch {@foo}
```

That doesn't compile correctly currently... but that's a bug.

**Comment by STRd6** [comment]
I think the correct fix will be an `esCompat` flag to address this as well as: https://github.com/DanielXMoore/Civet/issues/667 and non-parenthesized single argument arrow functions.

**Comment by edemaine** [comment]
OK, added to #270
