### ISSUE TITLE
Multiline strings in JSX attributes

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#405]
Apparently this JSX:

```jsx
<div class="hello
world"/>
```

gets translated to a string with a newline in it. (At least [with Solid](https://playground.solidjs.com/anonymous/dd826685-a801-45c2-b389-3984761340b7).)

However, Civet translates it to

```jsx
<div class="hello\nworld">
```

but [`\` escape characters don't work in JSX strings](https://facebook.github.io/jsx/#sec-jsx-string-characters), so this ends up having a literal `\` in it. (At least [with Solid](https://playground.solidjs.com/anonymous/b7e791eb-1c3b-4cd5-b2f6-d612881ff7b6).)

Probably just need to remove newline handling in JSX strings without braces, but need to test the various cases.

**Comment by STRd6** [comment]
Another option would be to convert the `\n` to ` ` in JSX. It looks like TS also treats it as `\\n` in React mode (as the JSX spec proscribes). https://www.typescriptlang.org/play?#code/DwEwlgbgBAxgNgQwM5ILwCIAWBTOcD2AOgHYDu+ATnCOgPQB8QA

**Comment by STRd6** [comment]
Though not transforming it at all like you suggest is also a good option.
