### ISSUE TITLE
Non-idempotency in braced literals

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [DanielXMoore/Civet#415]
Braced literal expressions involving function calls duplicate them; this is problematic in the case that those functions do IO or observe or mutate state, as seen below:
https://civet.dev/playground/?code=aSAuPSAwCmYgOj0gKCkgPT4gaSsrCnQgOj0gWyJhIiwgImIiXQpjb25zb2xlLmxvZyB7dFtmKCldfQ%3D%3D

**Comment by TheGreatCatAdorer** [comment]
A similar problem occurs for multi-assignment syntax: https://civet.dev/playground/?code=KGNvdW50KGtleSkgPz0gMCkrKwooY291bnQoa2V5KSA%2FPSAwKSArPSAxCisrY291bnQgKj0gMg%3D%3D

**Comment by edemaine** [comment]
Indeed, this is a "need refs" issue, currently tracked here: https://github.com/DanielXMoore/Civet/issues/50#issuecomment-1402394139

The next step here is #406, which we discussed recently on `#compiler` in Discord. Once that's complete, these should be easy to fix.
