### ISSUE TITLE
Triple-quoted literals don't escape backslashes

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [DanielXMoore/Civet#416]
Inserting a backslash into string literals quoted with `'''` only results in one in the output; therefore, a backslash inserted before an escape (which is itself escaped because it is inside backticks) results in the expression being interpolated.
https://civet.dev/playground/?code=Y29uc29sZS5sb2cgJycnCiAgPGRpdj4KICAgIFwkezMgKyA0fQogIDwvZGl2PgonJyc%3D

**Comment by STRd6** [comment]
Also seems to happen for triple backtick blocks as well: https://civet.dev/playground/?code=Y29uc29sZS5sb2cgYGBgCiAgPGRpdj4KICAgIFwkezMgKyA0fQogIDwvZGl2PgpgYGA%3D
