### ISSUE TITLE
Cannot directly export classes with decorators

### ISSUE THREAD

**Issue by kwaa** [DanielXMoore/Civet#420]
Playground:

- [`@foo class Bar`](https://civet.dev/playground/?code=aW1wb3J0IHsgaHRtbCwgY3NzLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JwppbXBvcnQgeyBjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJwoKQEBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKQpjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQKICBAc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YAoKICBAQHByb3BlcnR5KCkKICBuYW1lID0gJ1NvbWVib2R5JwoKICByZW5kZXIoKQogICAgaHRtbGA8cD5IZWxsbywgJHt0aGlzLm5hbWV9ITwvcD5gCg%3D%3D)
- [`@foo export class Bar`](https://civet.dev/playground/?code=aW1wb3J0IHsgaHRtbCwgY3NzLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JwppbXBvcnQgeyBjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJwoKQEBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKQpleHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50CiAgQHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWAKCiAgQEBwcm9wZXJ0eSgpCiAgbmFtZSA9ICdTb21lYm9keScKCiAgcmVuZGVyKCkKICAgIGh0bWxgPHA%2BSGVsbG8sICR7dGhpcy5uYW1lfSE8L3A%2BYAo%3D) (ParseError)
- [`export @foo class Bar`](https://civet.dev/playground/?code=aW1wb3J0IHsgaHRtbCwgY3NzLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JwppbXBvcnQgeyBjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJwoKZXhwb3J0IEBAY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJykKY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50CiAgQHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWAKCiAgQEBwcm9wZXJ0eSgpCiAgbmFtZSA9ICdTb21lYm9keScKCiAgcmVuZGVyKCkKICAgIGh0bWxgPHA%2BSGVsbG8sICR7dGhpcy5uYW1lfSE8L3A%2BYAo%3D) (Incompatible with TypeScript)

**Comment by STRd6** [comment]
Published in v0.5.80
