### ISSUE TITLE
Console output text is not visible when light mode is selected  In Playground 

### ISSUE THREAD

**Issue by RinGoku** [DanielXMoore/Civet#424]
No problem when dark mode is selected.
<img width="1453" alt="スクリーンショット 2023-03-02 8 24 45" src="https://user-images.githubusercontent.com/36734151/222289874-ed04840d-6925-45f7-8d6a-aff7c2c57b8c.png">

Console output text is unreadable when light mode is selected.
<img width="1465" alt="スクリーンショット 2023-03-02 8 24 39" src="https://user-images.githubusercontent.com/36734151/222289885-f22d9929-adbe-4935-a67a-a0ae2271884f.png">

We can see it by dragging. So I think it's a style issue.
<img width="1503" alt="スクリーンショット 2023-03-02 8 22 35" src="https://user-images.githubusercontent.com/36734151/222289909-4d75bd6c-3bb1-4605-8bb9-7e612052ed44.png">

**Comment by edemaine** [comment]
Thanks for the report! Should be fixed now.
