### ISSUE TITLE
CoffeeScript auto async and auto generator syntax missing

### ISSUE THREAD

**Issue by waterstone15** [DanielXMoore/Civet#427]
I believe auto `async` function syntax is not added when there is an `await` in the function body and the `"civet coffeeCompat"` flag is used. Same for `yeild` and generator function syntax.

These would be nice features in Civet core as well, or at least under `"civet autoAsyncCompat"` and `"civet autoGeneratorCompat"` flags.

**Comment by STRd6** [comment]
I think these would be good to add to Civet in general and shouldn't need compat flags.

**Comment by STRd6** [comment]
Fixed in v0.5.82
