### ISSUE TITLE
Civet Extension produces error typescript(6056)

### ISSUE THREAD

**Issue by skaneprime** [DanielXMoore/Civet#438]
` File 'w:/vault/libs/nest/src/index.ts' is not under 'rootDir' 'w:\vault\apps\server\auth\'. 'rootDir' is expected to contain all source files. `

All I know is that Civet Extension throws this error on nx monorepo due to ignoring `paths` in tsconfig.base.json 

To replicate it you can 
```
pnpm create nx-workspace (integrated, apps) 
pnpm i -D @nrwl/nest
pnpm exec nx g @nrwl/nest:app my-app
pnpm exec nx g @nrwl/nest:lib my-lib
```

Open ` /my-monorepo/apps/my-app/src/app/app.module.ts ` and import lib you created it should be located in tsconfig.base.json 

This will reproduce error

**Comment by skaneprime** [comment]
Finding this issue was quite a hellish job neither useful info nor there was a clue to extension

**Comment by edemaine** [comment]
#921 added support for TypeScript's `paths` alias in the LSP. I'm still getting the same error, but I assume it's now something to do with nx configuration.... See https://github.com/nrwl/nx/issues/5952 and https://github.com/nrwl/nx/issues/10773
