### ISSUE TITLE
Code formatter feature of Civet vscode extension

### ISSUE THREAD

**Issue by nguyenhothanhtam0709** [DanielXMoore/Civet#454]
Hi Civet team, I used Civet with Vs code. I have a question that: Can the Civet vscode extension format Civet code?

**Comment by STRd6** [comment]
Not currently but it is something we'd like to do in the future.

**Comment by nguyenhothanhtam0709** [comment]
@STRd6 S, Thanks for answering me. Hope Civet grows strongly.

**Comment by STRd6** [comment]
Closing in favor of #956
