### ISSUE TITLE
Decorator and nest js support

### ISSUE THREAD

**Issue by CherphAlt** [DanielXMoore/Civet#455]

**Comment by STRd6** [comment]
Can you provide more details?

**Comment by CherphAlt** [comment]
Do normal typescript decorators work?

For example:

```js
@Controller()
export class Hello{
@Get('/')
MyCoolRoute(){
return "Hello"
}
}
```

**Comment by CherphAlt** [comment]
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by CherphAlt** [comment]
Found out instead of using single '@' for decorators we need to use double '@@' 
Like: '@@'
