### ISSUE TITLE
Same-line decoration

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#462]
Civet seems to support `@@decorate class Foo` but not `@@decorate method()`.
By contrast, TypeScript supports `@decorate class Foo` and `@decorate method()`.

Full example:

```coffee
class Foo
  @@decorate foo();
```

Currently fails to parse. Expected compilation:

```ts
class Foo {
  @decorate foo() {}
}
```

**Comment by STRd6** [comment]
I don't think there is a way to allow this without preventing implicit application for decorators.

**Comment by edemaine** [comment]
Ah yeah, that makes sense... The method definition looks like a function call. The indented body is a bit special but still could be ambiguous (especially once we allow that for a function call).

I'd be inclined to leave things as is, but could go either way. For comparison, Python requires `@` on its own line.

**Comment by STRd6** [comment]
We probably should at least note the situation in the docs.

**Comment by edemaine** [comment]
I added some docs in 8e425b2430841d9656bd1902de56a13cefaf2ec3
