### ISSUE TITLE
Inline implicit object literals in function arguments bug

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#478]
This code should be a function call with two arguments, one object literal and another variable:

```coffee
f x: y, z
```

CoffeeScript [agrees](https://coffeescript.org/#try:f%20x%3A%20y%2C%20z).
But Civet parses the `x: y,` (note the trailing comma) as an object literal, which ends up with this compilation:

```js
f({x: y,}(z))
```

Do we need yet another flag for this, to avoid eating the trailing comma?  Seems like there ought to be a better way...

Maybe `InlineObjectLiteral` should just never consume the final comma; it seems like it should be treated as incorrect.

**Comment by STRd6** [comment]
😬
