### ISSUE TITLE
& function shorthand improvements

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#480]
Currently, the rule is: unary operators to the left of, and everything to the right of, a `&` symbol get wrapped into the function.

The proposal (from Discord discussion on March 1) is to make `&` "go up a level" if there's nothing right before or after it, namely, when it's followed by a comma or closing bracket.  Examples:

```coffee
f(a, &, b)    →  $ => f(a, $, b)
console.log & →  $ => console.log($)
& |> f |> g   →  $ => g(f($))      — already implemented
[&, x]        →  $ => [$, x]
{text: &}     →  $ => {text: $}
{&: "value"}  →  $ => {[$]: "value"}
x.filter !Array.isArray &
              →  x.filter($ => !Array.isArray($))
x > &         →  $ => x > &
```

None of these parse currently (except for the one already implemented).

I think we need to precisely define "go up a level", but I guess I'm imagining until a level of brackets or a function call, but also preceding unary operators and maybe stuff trailing the function call.

~~We also lack a notation for `$ => $`, which is occasionally useful (e.g. for `filter`).  With this notation, `(&)` would still work well.~~ Dealt with in #635.

Related: #75 (essentially partials; cf. `%` for generic pipe placeholder), and various proposals for `&` escaping another level up (e.g. `((&))`)

**Comment by STRd6** [comment]
One challenge is the interaction with existing `&` shorthand is some positions:

```coffeescript
x:
  a: &
  b: & + 1
```

```typescript
// Ex. 1
$ => ({x:
  a: $
  b: $ => $ + 1
})
// Ex. 2
$ => ({x:
  a: $
  b: $ + 1
})
```

It seems like `unwrapping` the same level shorthands makes sense and is generally what would be expected (Ex. 2). It does however make passing sibling functions challenging in other circumstances.

Just wanted to note this so we can figure out the edge cases.

**Comment by edemaine** [comment]
Good point. Alternate parses for that same example:

```coffee
// Ex. 3
x: $ => {
  a: $,
  b: $ => $ + 1
}
// Ex. 4
x: $ => {
  a: $,
  b: $ + 1
}
```

I realize this is also related to #85. If we end up with Ex. 2 or Ex. 4, we should reconsider whether `&+&` should in fact parse to `$ => $+$`. But as you say, we need to take care with shorthand functions contained in or sibling to other shorthand functions.

**Comment by juh9870** [comment]
And this is how that example parsed by web playground:
```ts
({
  x: {
    a: ($) =>
      $({
        b: ($1) => $1 + 1,
      }),
  },
});
```

**Comment by gwhitney** [comment]
Presumably the recently-added `x > &` case would also cover other operators like `3 - &` or `test ? & : null`. Except wait a minute `& ? trueVal : falseVal` doesn't even parse right now, even though it would seem to be OK from the current rule of `starts with & except for unary operators`. So perhaps that's verging on an inconsistency/bug in Civet as it stands? Should I file that observation of ternary operator with & first not working as a separate issue?

**Comment by edemaine** [comment]
Yes, it seems like we forgot about the ternary. Oops!

**Comment by bbrk24** [comment]
> unary operators to the left

Not even: I tried `++&` as a synonym for `(1+)` and that doesn't parse. `++& % y` becomes `++$ => $ % y` which is completely invalid JS.

**Comment by edemaine** [comment]
Replaced by the (now implementred) #1070 which lets `&` escape all the way to (but not including) a function call or assignment/declaration.
