### ISSUE TITLE
ESM loader requires @cspotcode/source-map-support

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#489]
Currently `dist/esm.mjs` includes the line

```js
import sourceMapSupport from "@cspotcode/source-map-support"
```

Was this supposed to be inlined via esbuild?

If not, I guess anyone using `--loader @danielx/civet/esm` needs to have `@cspotcode/source-map-support` installed locally.

Unfortunately, this means that the ESM version of the CLI still isn't working without locally installing the dependency. (It was only working in my `npm link` testing, because that gives access to Civet's dependencies, not just `dist`.)

For what it's worth, even when I do install the dependency locally, I get the error message `No source map found in code` in console, and none of the line numbers are correctly remapped. Probably a separate issue though.

**Comment by STRd6** [comment]
We can probably make it optional with a dynamic import. It's necessary to get the source maps working correctly.

**Comment by edemaine** [comment]
Hmm, or maybe the issue is that `@cspotcode/source-map-support` needs to be listed in `dependencies`.

**Comment by STRd6** [comment]
Adding to dependencies might be the simplest most straightforward fix.

👍
