### ISSUE TITLE
process.argv[1] has trailing .tsx

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#490]
Apparently this is the way to check whether you're running a script directly in ESM:

```coffee
import.meta.url.startsWith('file:') and
process.argv[1] === url.fileURLToPath import.meta.url
```

Unfortunately, it doesn't work for scripts currently run via the `civet` CLI, because `process.argv[1]` ends up being not the original `.civet` filename but the pretend compiled filename `.civet.tsx`.  Thus we currently need to do:

```coffee
import.meta.url.startsWith('file:') and
process.argv[1]+'.tsx' === url.fileURLToPath import.meta.url
```

I think we should probably not have the `.tsx` suffix in `process.argv[1]`. This should be an easy fix; just marking it for later.

**Comment by edemaine** [comment]
This actually seems difficult to do right.  `civet filename.civet` is simply executing

```sh
node --loader @danielx/civet/esm filename.civet
```

The actual issue is that the ESM loader adds `.tsx` to the official URL:

https://github.com/DanielXMoore/Civet/blob/db932b8f7fb98ab67752178e73d7028421f8fcca/source/esm.civet#L80

This is kind of annoying in that `import.meta.url` now no longer refers to an actual physical file.

On the other hand, this kind of URL mangling is presumably necessary to trigger `ts-node`. (That's not happening in this case, but in other invocations could be necessary.)

Do you still a way to improve this situation? If not, maybe we just need to document this weirdness. I'll use `import.meta.url.replace /\.tsx$/, ''` for my application. (Detecting the "main" module is getting *really* hard!)

**Comment by STRd6** [comment]
I think we can continue to append `.tsx` so that downstream loaders/transforms work as expected. We can then probably strip it out after awaiting the result of downstream loaders.
