### ISSUE TITLE
splice type issue

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#492]
Consider this code:

```coffee
declare var list: string[]
[...rest, last] := advisors
```

It [compiles to](https://civet.dev/playground?code=ZGVjbGFyZSB2YXIgbGlzdDogc3RyaW5nW10KWy4uLnJlc3QsIGxhc3RdIDo9IGFkdmlzb3Jz):

```ts
const splice: <T>(
  this: T[],
  start: number,
  deleteCount?: number
) => T[] = [].splice as any;
declare var list: string[];
const [...rest] = advisors, [last] = splice.call(rest, -1);
```

The result is that [TypeScript types `last` as unknown](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA3W8IEsDOAXAXPbMaAdgOYDaAugNwBQYA9kdvgA7pgh4A8AKgHwAKGvHhYAFpjw9KAGmH4ssXPCIBXALYAjEDDkjQEEFhABheqqJYA-HjVadNAJTwAvH3jSKr+JQB0GNjQOeCgMEKIAT1oGJiwfXwS4bC8XVEwsGR9oZO8A9hBfMCgICAEkjPgAWgBGR1oRBsam5pEAelb4AD0rIA). I'm not entirely sure why.

It seems like the following transpilation is both more efficient (fewer function calls) and [satisfies TypeScript](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA3W8IEsDOAXAXPbMaAdgOYDaAugNwBQYA9kdvgA7pgh4A8AKgHwAKGvHwgIAMzw9KAGmH4ssXPCIBXALYAjEDDkjQEEFhABheqqJYA-HjVadNAJTwAvH3jSKr+JQB0GNjQOXzAoCAh4KAxIogBPWgYmLB9fVLhsLxdUTCwZH2gM7wD2EAF03PgAWgBGR1oRBsam5pEAelb4AD0rIA):

```ts
declare var list: string[];
const splice: <T>(
  self: T[],
  start: number,
  deleteCount?: number
) => T[] = [].splice.call as any;
const [...rest] = list, [last] = splice(rest, -1);
```

Assuming you agree, this should be a very easy fix.

**Comment by STRd6** [comment]
We may even be able to do:

```typescript
declare var list: string[];
const [...rest] = list, [last] = rest.splice(-1);
```

**Comment by edemaine** [comment]
That seems good to me. We currently generate direct method calls for `is in` (`.includes`), which enabled overloading. In this case, we actually have a guarantee that it's an array (as we just built it). I don't think there's a significant performance advantage to the current adding this layer of indirection.
