### ISSUE TITLE
using / Python like with statement

### ISSUE THREAD

**Issue by CherphAlt** [DanielXMoore/Civet#503]
This statement would be better as it would increase readability and improve the language semantics

**Comment by edemaine** [comment]
For those unfamiliar: [Python's `with x as y` statement](https://docs.python.org/3/reference/compound_stmts.html#the-with-statement) does the following:
* Calls `x.__enter__()`, and sets `y` to the result (within the block).
* Runs the block
* Calls `x.__exit__()`, with any raised exception if the block raised one.

The most common use-case is probably opening files and automatically closing them. Indeed, [Janet has a similar `with` function](https://janet.guide/tables-and-polymorphism/) that just calls the `:close` method at the end of the block (no `enter` and no special double underscores).

Note that this is very different from JavaScript's `with` statement. #214 proposes a `with` statement that is more along the lines of JS but less ambiguous. Plausibly the two proposals could be combined into one: `with` could define a meaning for a symbol like `^` while also checking for methods to call before/after the block.

The main challenge I have with this proposal is that it's not clear what the API pattern should be: what to call before and after the block.  We could call a `.close()` method at the end, and this might work with some APIs.  Or we could follow the Python double-underscore methods, but JS doesn't have a pattern of these so it would look pretty weird, and it wouldn't work with any existing APIs off-the-shelf.  Did you have something specific in mind?

**Comment by edemaine** [comment]
TypeScript 5.2 is [adding a `using` keyword](https://twitter.com/mattpocockuk/status/1669630994280849408) based on a [Stage 3 JS proposal](https://github.com/tc39/proposal-explicit-resource-management/).

Inspired by C#, `using` essentially gives a block-free version of the exit mechanics of Python's `with`. In some ways the block-freeness is superior. Technically it prevents enter functionality, but I've never needed that personally, so this may be a good solution.

We'll want to support `using` in Civet soon for TypeScript compatibility. We could also transpile ourselves when in JS mode. [Here's the relevant transpilation equivalent](https://github.com/tc39/proposal-explicit-resource-management/#using-declarations-with-multiple-resources).

(based on Discord messages from me and Daniel)

**Comment by edemaine** [comment]
Now that [TypeScript 5.2 is released](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/), we should prioritize adding `using` support, at least passing it through in TypeScript mode. (It'd be nice to do our own transpilation in `js: true` mode, but that's harder.)

**Comment by STRd6** [comment]
I suppose we also need a `using` declaration shorthand at some point too...
