### ISSUE TITLE
`for*` generator expressions

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#505]
We can make it easy for `for` to generate (`yield`) values instead of accumulating an array and returning it, given that we're already wrapping in an IIFE.

See https://github.com/jashkenas/coffeescript/issues/5379 for this exact idea.  I didn't think `for*` made sense in a CoffeeScript syntax, but it makes sense in Civet which inherits all of ECMAScript; I think it nicely pairs with the recently added `async for`.  I'm also inspired here by [Janet's `generate`](https://janet.guide/control-flow/).

**Comment by STRd6** [comment]
`loop*` and `while*` could also be cool for infinite generators.
