### ISSUE TITLE
vscode civet extension throws error on enum

### ISSUE THREAD

**Issue by vshesh** [DanielXMoore/Civet#520]
in a blank file on vscode typing 

```
enum Test {One, Two, Three}
```

Gives an error:
```
Failed to parse
Expected:
	Colon ":"
Found: " "
```

Compiling the file with `civet -c` works just fine though.

**Comment by edemaine** [comment]
Can you make sure that you've `npm install @danielx/civet` locally within the repo you're working? The vscode plugin is likely using an old version of Civet.

**Comment by vshesh** [comment]
ok, that solved the issue, thank you. 
is there a version of the plugin with a new version of civet?
