### ISSUE TITLE
VS Code error:  module `.civet` was resolved to `.civet.tsx`

### ISSUE THREAD

**Issue by iliocatallo** [DanielXMoore/Civet#522]
Hello there!

I set up a very basic Civet project. Everything seems to be working fine. The only issue I'm experiencing so far is the following error in VSCode:

<img width="1186" alt="civet-tsx" src="https://github.com/DanielXMoore/Civet/assets/3093067/0b2570e5-d963-4fd1-8723-a562fa0c84e7">

Despite the error, I can still jump between modules using the Civet extension.  Any clue on how to stop VSCode from complaining?

Thank you,
Ilio.

**Comment by iliocatallo** [comment]
Hi Daniel,

Thanks for the suggestion. Ideally, I would like to keep TypeScript out of the picture and just write Civet code that gets compiled to JavaScript. I tried to add a `jsconfig.json` file with the settings suggested in the [Getting Started](https://civet.dev/getting-started) page (which includes `jsx: preserve`), but VSCode was still complaining.

After moving to TypeScript (`typescript`, `ts-node`, `@types/node`), `tsconfig.json` started producing the desired effect (I also instructed VSCode to use the TypeScript installation from `node_modules/`). 

I guess there's no way to circumvent TypeScript, correct?

Thank you.

**Comment by edemaine** [comment]
Did you try creating a `tsconfig.json` file without actually using TypeScript? (Shouldn't need to install or use those packages.)

The error (really, a warning) is caused by the plugin running TypeScript on your code to try to detect errors (and types). This is what you're configuring. It doesn't mean you actually need to write TypeScript types or run your code via TypeScript; you can continue to tool by compiling to JS and running that directly.

We should look into whether we can specify a default for JSX mode so that including a tsconfig.json file isn't necessary.

**Comment by iliocatallo** [comment]
Hi Erik,

I just removed TypeScript from my [my (very) basic project](https://github.com/iliocatallo/civet-playground/tree/without-ts), while keeping `tsconfig.json` – and it seems to be working fine, thank you! 

Still, I would find it a bit surprising to land on a project with a `tsconfig.json` file, just to discover that there's no use of TypeScript at all in the project toolchain. Since VSCode own [documentation](https://code.visualstudio.com/docs/languages/jsconfig) mentions that:

> `jsconfig.json` is `tsconfig.json` with `"allowJs"` attribute set to `true`, 

my hope was to use `jsconfig.json` in place of `tsconfig.json` when using Civet in a purely JavaScript project. Maybe the Civet LSP extension can fallback to`jsconfig.json` if no `tsconfig.json` is present.

I'm also curious to know what TypeScript installation the Civet extension is using when the TypeScript SDK is overridden at the workspace level  (via the `"typescript.tsdk"` in the project `.vscode/settings.json`). As different releases of VSCode ships with different versions of TypeScript, to improve reproducibility I usually have "typescript.tsdk"  point to use the installation in `node_modules/`. Would it also affect how the LSP extension type-checks the code?

Thank you!

**Comment by STRd6** [comment]
Having the LSP default to "preserve" if no jsx option is specified is good idea.

Additionally there is more we should do to properly support `jsconfig.json` as well.

As for `"typescript.tsdk"` ideally the Civet LSP should respect what is configured though I'm not sure if it currently does.

Thanks for the thoughtful feedback!
