### ISSUE TITLE
How do I do constructor overloading in civet?

### ISSUE THREAD

**Issue by vshesh** [DanielXMoore/Civet#538]
First there is another parsing error on this test file: 

```ts
class Test 
  variable: string[] 
  constructor({x: number, z: Nesting, y: SubElement[]})
```
(yes this isn't a valid class yet without an implementation but the error is a parse error not a syntax error)
```
test.civet:3:52 Failed to parse
Expected:
	Whitespace /[\s]+/
	JSMultiLineComment "/*"
	CoffeeHereCommentStart /###(?!#)/
	JSSingleLineComment /\/\/(?!\/)[^\r\n]*/
	Equals "="
	NonNewlineWhitespace /[ \t]+/
	InlineComment "/*"
	Comma ","
	ObjectPropertyDelimiter "}"
	EOL /\r\n|\n|\r|$/
Found: "[]})"
ts
```

And in general I am curious how best to implement overloaded constructors in civet. Didn't see it in the cheatsheet. 
I want to allow passing in a single object with all params and passing it params as args, so something like: 

```ts
class Test < SomeOther
  # In TS i would have to write the clunkier constructor(obj: {x:number, y:number, z:number} = {x: 0, y: 1, z: []}), this is an easy syntax improvement win (although would need an error like "need to define defaults for all values of an object param")
  @(obj: {x: number = 0, y: number = 1, z: number[] = []})
  # do i do @(public x: number = 0, ...) ? 
  @(p: number = 0, y: number = 1, z: number[] = [])
      if (y == undefined) {
        let {x, y, z} = p;
      } else {
        let x = p;
      }
      super(x,y)
      this.z = z
```

(with the parse error I can't tell whether this works or not)

it would be quite amazing if civet could intelligently construct a "unified" implementation from overloads (functions and methods and constructors) that have different types and arities, like so: (the fact that typescript doesn't do this automatically kind of surprises me)

```ts
function test(obj: {x: number, y:number=1, z:number[]=[]}): Type
  test(x, y, z)
function test(x: number, y:number = 1, z: number[]=[]): Type
  // ... does something
``` 

would turn into something like: 
```ts
function test(obj: {x:number, y:number, z:number[]} = {y:1, z:[]}): Type;
function test(x: number, y:number=1, z:number[] = []): Type; 
function test(xOrObj: number | {x:number, y:number, z:number[]}, y:number=1, z:number[] = []): Type {
  if (y == undefined) { 
     // boilerplate destructure
     let {x,y,z} = xOrObj; 
     // copies implementation here
     return test(x, y, z) 
  }
  // ... does something [copied here]
}

```
could also make two dummy functions which copy both implementations and call them in place with the correct arity.
```ts
function test(xo: number | {x:number, y:number, z:number[]}, y: number=1, z: number[] = []) {
  if (y == undefined) {
    // copy implementation here as IIFE
    return (({x:number, y:number, z:number[]}) => test(x, y, z)})(xo)
  } 
  return ((x,y,z) => {
     // ... does something
  })(x, y, z)
}
```
although of course first option is preferred.

Idk if civet understands types but even doing this for different arities would be a big dev boon

**Comment by STRd6** [comment]
Thanks for the report. The lack of constructor and method overloading in classes currently is a bug and I hope to fix it soon.

There is some discussion about mixed type/value destructuring here: https://github.com/DanielXMoore/Civet/discussions/126 and it is something we are interested in but it is challenging to find a unified syntax that is compatible with existing TypeScript while being simple enough and providing enough value but I think we are getting close. Feel free to add your thoughts to the discussion.

Thanks again and I hope you enjoy programming with Civet!
