### ISSUE TITLE
Bind in implicit function call

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#539]
`@@foo` works, but `f @@foo` fails to parse

**Comment by STRd6** [comment]
This is a compromise due to some overlap with decorator syntax but we may be able to be more precise about it.

See: https://github.com/DanielXMoore/Civet/blob/7d6e6c30227625396727ef2c3c1695c919a5a41d/test/class.civet#L658-L672

**Comment by edemaine** [comment]
Ah, right, I forgot. This definitely makes sense at the start of the line, but `f @@foo` can't possibly be a decorator, right? Indeed, it fails to parse now... Will need to investigate.

**Comment by edemaine** [comment]
I understand the conflict now. Implicit function calls are forbidden when the argument starts with `@@`, because it can be the start of a new decorator.

Currently we support these forms:

```js
@@dec1 @@dec2 class Foo // reasonable

@@dec1 arg, arg @@dec2 arg, arg class Foo // unreasonable?

@@dec1 arg, arg
@@dec2 arg, arg
class Foo  // reasonable
```

I think it would be reasonable to only allow multiple decorators in a row when they have no implicit function calls. I'm not sure that makes it easier to parse though (unless we add another flag for whether implicit calls are allowed).

By the way, it looks like we don't support decorators on class methods or fields, unlike the [TC39 spec](https://github.com/tc39/proposal-decorators). The following [transpiles into the wrong thing](https://civet.dev/playground?code=Y2xhc3MgRm9vCiAgQEBkZWMgeCA9IDUKICBAQGRlYyBmKHgpCiAgICB4), and without the final `x` it doesn't even parse:

```js
class Foo
  @@dec x = 5
  @@dec f(x)
    x
```
