### ISSUE TITLE
`@foo` in constructor should make class attribute declaration or use `public`

### ISSUE THREAD

**Issue by iliocatallo** [DanielXMoore/Civet#549]
Hi,

When copy-pasting the `Rectangle` class from the official [Cheatsheet](https://civet.dev/cheatsheet#constructor)

```civet
class Rectangle
  @(@width: number, @height: number)
```

VSCode is complaining about the fact that:

```
Property 'width' does not exist on type 'Rectangle'.
Property 'height' does not exist on type 'Rectangle'
```

Which I think it's reasonable, given that the code gets translated into:

```ts
class Rectangle {
  constructor(width: number, height: number) {
    this.width = width;
    this.height = height;
  }
}
```

A better translation might be:

```ts
class Rectangle {
  public width: number;
  public height: number;
  constructor(width: number, height: number) {
    this.width = width;
    this.height = height;
  }
}
```

or even:

```ts
class Rectangle
  constructor(public width: number, public height: number) {}
```

Thanks, ciao!

**Comment by edemaine** [comment]
We can already write
```js
class Rectangle
  @(public width: number, public height: number) {}
```
in Civet. I guess the issue with this is that it only works in TypeScript. I like the idea of automatically adding attribute types (if they aren't already), as in your first transpilation.

**Comment by GoToLoop** [comment]
```coffee
class Rectangle
  @(@width: number, @height: number)
```

IMO, the code above should be transpiled as just:
```ts
class Rectangle {
  constructor(public width: number, public height: number) {}
}
```

Which is pretty enough valid for TS.

**Comment by edemaine** [comment]
The issue with this compilation is that it *requires* the use of a TypeScript transpilation phase afterward, whereas some only use TypeScript for checking and not building. It's also less symmetric with how other functions compile...

So while I agree it's a decent approach (if we also improve Civet's JS mode to deal with `public` etc in constructors), IMO it'd be simpler to just add property declarations too...

**Comment by GoToLoop** [comment]
> , whereas some only use TypeScript for checking and not building.

IMO, Civet should focus on transpiling to TS only. Let CoffeeScript deal w/ JS transpilation.

**Comment by bbrk24** [comment]
Jumping in to say that going from civet straight to JS is exactly the use case I plan to need. I don't think tsc supports stdin so I can't just do `npx civet <file.civet | npx tsc >file.js`. I'm fine if civet internally creates TS and then invokes tsc itself, but I don't want to have to create an intermediate file.
