### ISSUE TITLE
`coffeeCompat` thicc arrow function in classes

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#55]
```
class X
  y: => b
```

https://coffeescript.org/#try:class%20X%0A%20%20y%3A%20%3D%3E%20b

**Comment by bbrk24** [comment]
This seems to be supported now: https://civet.dev/playground?code=J2NpdmV0IGNvZmZlZUNsYXNzZXMnCgpjbGFzcyBYCiAgeTogPT4gYg%3D%3D

Or was it about using `=>` vs `bind`?

**Comment by edemaine** [comment]
Yes, I think the point is to add the bind wrapper (and maybe also switch the function into a method declaration), for CoffeeScript compatibility.

**Comment by bbrk24** [comment]
You're right; I just checked, and the compilation has not changed since then.
