### ISSUE TITLE
civet extension has started showing lots of basic errors

### ISSUE THREAD

**Issue by vshesh** [DanielXMoore/Civet#560]
It feels like the typescript compiler has just lost its stdlib or something. 

Errors are things like `cannot find name Date` or `cannot find name RegExp` or `cannot use number to index {}` on something that is clearly a `number[]`. The same errors are being shown in the `.ts` file. 
I don't think I did anything different, my tsconfig is below: 
```
{
  "compilerOptions": {
    "strict": true,
    "jsx": "preserve",
    "lib": ["es2021", "dom"],
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "declaration": true,
		"allowSyntheticDefaultImports": true,
		"skipLibCheck": true,
    "sourceMap": true
  },
  "ts-node": {
    "transpileOnly": true,
    "compilerOptions": {
      "module": "ES2020"
    }
  }
}
```

this is the sidebar of my vscode window

<img width="57" alt="Screen Shot 2023-07-01 at 5 59 35 PM" src="https://github.com/DanielXMoore/Civet/assets/2929957/898ae649-71d1-4625-95cc-f4b8c21eb307">

it's probably not strictly a civet issue, but I cannot figure out how to solve and thought i would post it here

Everything still works fine when running civet compiler and using bun/node to run files. the ide is just missing definitions.

**Comment by vshesh** [comment]
Ok I have done some rebooting and reinstalling and this is back to working now
Can't figure out how I created or solved this issue ........

**Comment by edemaine** [comment]
Glad you got it working. In the future, there's a "restart extension" command, or you can try just restarting VSCode. If you are able to reproduce the crash, though, let us know!
