### ISSUE TITLE
Compiling to js doesn't support const enums

### ISSUE THREAD

**Issue by esthedebeste** [DanielXMoore/Civet#564]
```
$ pnpm civet --js
Civet 0.6.10 REPL.  Enter a blank line to execute code.
🐱> const enum Options { A }
... console.log(Options.A)
...
REPL3:2
console.log(Options.A)
            ^
Uncaught ReferenceError: Options is not defined
```
The `const enum` declaration is fully dropped resulting in non-functional code

**Comment by edemaine** [comment]
This is now worked around in 0.6.26. (In `--js` mode, `const enum`s are now compiled the same as `enum`s, but at least they should work.)
