### ISSUE TITLE
Impossible to avoid implicit return in async functions without extra line

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#595]
There are three ways to make a synchronous function not to return a value:
1. Specifying a `void` return type
2. Adding a final semicolon
3. Explicit `return`

For an asynchronous function, the first way is not possible because the return type of the async function can't be `void` and should be `Promise<void>` instead. But `Promise<void>` is not `void`, so there is an implicit return according to current rules of Civet. But if there is a return, then the return type is probably no longer `Promise<void>`. Typescript will complain.

Adding a semicolon is only a solution for simple functions that don't have nested indented blocks. In complex cases, a semicolon can of course be added on the new last line, but it looks odd and it's better to write empty `return` (3rd way) instead of a semicolon. But that's a whole extra line of code with cryptic behaviour for js/ts-developers.

Is it possible to make an async function's return type `Promise<void>` act like `void` for synchronous functions? In Typescript, we do not need extra lines of code if the function does not return anything. In Civet, this is not possible for asynchronous functions, if I understand correctly of course.

**Comment by STRd6** [comment]
Thank for the suggestion, we should definitely improve our handling of implicit return in `Promise<void>` functions.

**Comment by edemaine** [comment]
A return type of `Promise<void>` should stop implicit returns from async functions, as of 0.6.17.
