### ISSUE TITLE
CLI for type checking

### ISSUE THREAD

**Issue by lorefnon** [DanielXMoore/Civet#61]
Vue has a cli utility called [vue-tsc](https://www.npmjs.com/package/vue-tsc), which can be used for type-checking in CI env etc. It would be good to have something similar for civet.

**Comment by edemaine** [comment]
Agreed. I was imagining a `civetsc` CLI tool (or something like that) that runs TypeScript on the transpiled files, following `tsconfig.json` (or maybe even `tsconfig.civet`?).

Perhaps it should be a second `bin` for the main Civet package. Or perhaps it should be its own NPM package, given that it would have a `typescript` peer dependency?

**Comment by lorefnon** [comment]
> runs TypeScript on the transpiled files

That may not be a great idea. Ideally we'd non-interactively do what the lsp client already does so that any errors etc. have correct source line numbers. 

@STRd6 Are you open to  bin/civettsc (or maybe just civetc) ? I think keeping this outside may be a maintenance burden because I think tsserver integration is still early and keeping the two in sync may need more work.

**Comment by edemaine** [comment]
I agree that this should be part of this repo (but maybe separate NPM package), and wyen I said "run TypeScript" I meant the same thing as the LSP (not running tsc).

**Comment by STRd6** [comment]
Having an additional `civetc` build product in `bin` makes sense. I also agree that making use of the same TSServer wrapping is important so that the editor error messages match the cli error messages exactly. I'm in support of anyone who wants to work towards this.

**Comment by lorefnon** [comment]
Ok cool. Looks like everyone is on the same page then. 

I can take this up mid next week.

**Comment by STRd6** [comment]
Feel free to refactor out the TSServer wrapping from lsp into a shared lib if it makes things easier.

**Comment by edemaine** [comment]
An update on this: if you use Vite, Rollup, ESBuild, or Webpack to build your Civet code, our [new unplugin for these systems](https://github.com/DanielXMoore/Civet/tree/main/integration/unplugin) now has a `typecheck: true` option that will do typechecking. So we now have a reasonable way to do type checking in CLI!

**Comment by danielbayley** [comment]
Surely the bin should be called `tscivet`… or `tscvt`?

**Comment by edemaine** [comment]
I guess it's a tradeoff on whether to have just one `bin` or multiple. I don't have a strong feeling, but most of the code would be shared with the CLI so I think allowing for `civet -t` at least makes sense. We could also add an alias of `tscivet` or `civetsc` if we want.
