### ISSUE TITLE
Missing `return` when using `then` inside `switch`

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#615]
You probably already know this, but just in case. It seems #612 didn't solve the `return` issue mentioned in #607.

Current version of Civet from the repository compiles this code
```coffee
sign := (x) -> switch x
  > 0 then 1
  < 0 then -1
  else 0
```
to this
```js
function sign (x) { if(x > 0) { 1}
else if(x < 0) { -1}
else  { return 0 } }
```

But the resulting code should be like this
```js
function sign (x) { if(x > 0) { return 1 }
else if(x < 0) { return -1 }
else  { return 0 } }
```

**Comment by edemaine** [comment]
Should be fixed in 0.6.20!
