### ISSUE TITLE
Hoisting of generated variables

### ISSUE THREAD

**Issue by Mokshit06** [DanielXMoore/Civet#624]
I was trying out the `for item, index in array` syntax and came across a hoisting bug in civet.
Using the loop as a statement by itself works fine
```coffee
for ai, i of a
     ai + b[i]
```
And so does using it as an expression in global scope
```coffee
(for ai, i of a
     ai + b[i]
)
```
but when using it as an expression inside a nested scope like function
```coffee
function x()
    (for ai, i of a
        ai + b[i]
    )
```
it throws this error `Couldn't find expression in block for hoistable declaration.`.

Another behaviour I noticed, assigning the expression to a new variable (`:=`,`.=`) makes it work:

```coffee
function x()
  b := (ai + b[i] for ai, i of a)
```
but assigning it to an already declared variable (`=`) throws the same error.

It occurs because the way `for item, index of array` is compiled, the `index` variable is declared outside the iife closure, rather than inside.

**Comment by edemaine** [comment]
Should be fixed in 0.6.22!
