### ISSUE TITLE
Postfix conditional expressions shouldn't require parens inside object properties

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#628]
Works:
```
BoardPlayerTemplate
  class: ("opponent" if i)
```

Doesn't work:
```
BoardPlayerTemplate
  class: "opponent" if i
```

**Comment by edemaine** [comment]
CoffeeScript [supports](https://coffeescript.org/#try:BoardPlayerTemplate%0A%20%20class%3A%20%22opponent%22%20if%20i%0A) the first example, but treats it like

```coffee
BoardPlayerTemplate(
  (class: "opponent") if i
)
```

I'm not sure which is the better parse... I do think your "works" is perhaps more intuitive, but it's not CS compatible. 🙁 

---

This is kind of an aside, but what I'd rather have is a magical feature like this:

```js
type: "foo"
class: className if className?
↓↓↓
{type: "foo", ...(className != null ? {class: className} : void 0)}
```

But I'm not sure what the non-multiline form would look like. The following already has a different (less useful) meaning.

```coffee
type: "foo"
if className? then class: className
```

Perhaps this magic should only be a feature of braced literals, as in

```js
{
  type: "foo"
  if className?
    class: className
}
// or
{type: "foo", class: className if className?}
```

**Comment by STRd6** [comment]
Yeah, that is a bit tricky.

I think in cases where it is unambiguous (multiline object properties, braced or not) then we can allow for postfix if expressions where currently it's a parse error.

I think CoffeeScript actually does it "right" when the inline object is multi-line: https://coffeescript.org/#try:X%0A%20%20class%3A%20%22opponent%22%20if%20x%0A%20%20y%3A%20yo

**Comment by edemaine** [comment]
Oh, nice. I'd be tempted to have the "right" behavior in all cases, making CoffeeScript more "self-consistent". (Similar to what you did with relational operators like `in`.)
