### ISSUE TITLE
Late assignment for unary prefix `!`

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#629]
```
!x = 3
```

This matches CoffeeScript: https://coffeescript.org/#try:!x%20%3D%203

**Comment by STRd6** [comment]
I was thinking it might be useful to extend for `if` declarations but negating will never enter the block with a non-false result so I can't think of any situation where it would come in handy.

Just posting here in case it sparks any other ideas:

```
if !{a, b} := fn(x)
  ...
```

**Comment by edemaine** [comment]
> I was thinking it might be useful to extend for `if` declarations but negating will never enter the block with a non-false result so I can't think of any situation where it would come in handy.

Maybe if you wanted to then distinguish `undefined`, `null`, `false`, `""`, `0` (or just return whatever falsey value you got).

I find `!x = 3` pretty weird looking; I parse it in my head as `(!x) = 3`, which doesn't have a meaning. But I can't think of what else it would mean, so I'm fine with matching CoffeeScript here.
