### ISSUE TITLE
Identity function shortcut

### ISSUE THREAD

**Issue by eevleevs** [DanielXMoore/Civet#635]
As discussed on Discord, would be useful to have something like `(&)` as a shortcut for `($x) => $x`.

**Comment by edemaine** [comment]
Agreed! I think this is tracked by #480; feel free to leave more feedback there. Adding the identity function specifically should be straightforward... But I may not be able to work on it for a little bit.

**Comment by STRd6** [comment]
Brainstorming some options:

`xs.map .`
`xs.map ()`

Alternatively in the meantime:

```civet
const I = <T, >(x: T) => x

xs.map I
```

**Comment by edemaine** [comment]
* `.` is pretty cute, and feels consistent with `.foo` property accessors. Needs to be followed by whitespace I imagine, and we should check whether it's ambiguous with anything current (but I think actual property access can't have whitespace after the dot).
* I also still find `(&)` pretty intuitive.
* `()` feels a bit counterintuitive to me.

So maybe the first two, by analogy to `.foo` and `&.foo` both working?

**Comment by STRd6** [comment]
`(&)` is released as an identity function shorthand in v0.6.28
