### ISSUE TITLE
Config.civet reserved

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#641]
I haven't found any mention of a `config.civet` either on the website or on the GitHub page, but I guess `config.civet` is a reserved filename?

I happened to have `config.civet` file in my working dir with my own stuff in it and every time I wanted to compile, an empty output file was created and the process seemingly never completed. Took me ages to figure out what's going on.

The issue occurs even if nothing imports the file. Renaming the file solves the issue. Naming it back resurfaces it.

I assume [https://civet.dev/config](https://civet.dev/config) is supposed to detail what goes inside.
Even before it does, let's mention this in the readme, so peeps don't fall into the same hole I did.

---

Additionally, can we maybe think about not calling it `config.civet`? To me that seems too much like a project file, rather than a sort of meta config file. I assume it's a _.civet_ file, cause it can have some dynamic fields or something? If not, can't we just have a `json` file instead?

----

After some more testing, I found it that it probably does get over it at some point (maybe), because the time it takes seems to depend on the length of the file. But my original config file of 99 lines did not finish in _13 minutes_ (after which I stopped the timer).

**Comment by STRd6** [comment]
Thanks for the report, we could definitely use some more documentation around this and may want to reconsider the naming as well.

A possible workaround is to add the `--no-config` flag when you run the `civet` command to tell it that you don't want to autoload a config file.

**Comment by edemaine** [comment]
* [ ] Yes, documenting this is on my to-do list.
* [ ] We should avoid infinite recursion when trying to explicitly compile the config file (which is going to be common e.g. when `civet -c *.civet`).
* [ ] Agreed `config.civet` is probably too useful a filename (maybe good it's not documented yet!). I think `civetconfig.civet`, while repetitive, is probably better. (I think we support both, and should drop `config.civet`.)

**Comment by zolomatok** [comment]
I like how Bun does it with bunfig.toml, maybe we could do it similarly. 

But civfig doesn’t sound that hot. Catconfig would be fun, but may be a stretch :)

**Comment by zolomatok** [comment]
Sold! 🔨

**Comment by zolomatok** [comment]
How about simply `civet.toml`? 🤔
catfig.toml? khajiit.toml? 😄
