### ISSUE TITLE
Implicit returns ignore the return type in arrow functions

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#699]
Looks like I'm a big fan of functions without `return`.

#### Synchronous function:
```coffee
abort := (): void =>
  process.exit 1
```
↓↓↓
```js
const abort = (): void => {
  return process.exit(1);
};
```

#### Asynchronous function:
```coffee
run := async (command: string): Promise<void> =>
  await exec command
```
↓↓↓
```js
const run = async (
  command: string
): Promise<void> => {
  return await exec(command);
};
```

**Comment by STRd6** [comment]
I think this was a regression from the fix to https://github.com/DanielXMoore/Civet/issues/695

I've added more tests and it's now fixed in v0.6.31
