### ISSUE TITLE
Parse error in function type aliases when line is split

### ISSUE THREAD

**Issue by gwhitney** [DanielXMoore/Civet#704]
```
type Fred = (a: string) => number
```
parses (and is left alone, as it is valid TypeScript), but neither of
```
type Fred =
    (a: string) => number
```
nor
```
type Fred
   (a: string) => number
```
parses (even though the first is valid TypeScript as it stands).

**Comment by edemaine** [comment]
Should be fixed in 0.6.50. Thanks for the report, and sorry for the delay!
