### ISSUE TITLE
Update assignment inside function arguments lacks parentheses

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#715]
```civet
f ++x *= 3
```

Actual:
```typescript
f(++x, (x *= 3));
```

Expected:
```typescript
f((++x, (x *= 3)));
```

**Comment by abdullah-25** [comment]
where exactly this code is?

**Comment by STRd6** [comment]
@abdullah-25 I think it's around here in the code generation: https://github.com/DanielXMoore/Civet/blob/5291ec2bdd352045dc99ce61a8202327b2d956b0/source/lib.civet#L2113

And here is the relevant area in the parser:
https://github.com/DanielXMoore/Civet/blob/5291ec2bdd352045dc99ce61a8202327b2d956b0/source/parser.hera#L434-L451

I often find it helpful to add a single test case with `.only` so that it is the only test that runs, add a `debugger` statement inside the handler code, then debug it with `yarn test --inspect-brk` and open up the dev tools to step through and see what is happening.

Thanks for taking a look and let me know if you have any other questions!
