### ISSUE TITLE
LSP dependency on tsconfig.json

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#72]
The LSP should re-parse everything when `tsconfig.json` changes. Currently I need to restart. By contrast, `.tsx` files update when I change `tsconfig.json`.

Ideally the same for `node_modules/@danielx/civet`, for upgrading Civet more seamlessly.

**Comment by STRd6** [comment]
This should be pretty straightforward now that we have the restart command in the LSP. It may just be a matter of hooking it up to trigger when the file changes.
