### ISSUE TITLE
non-toplevel `import`ing

### ISSUE THREAD

**Issue by esthedebeste** [DanielXMoore/Civet#727]
```ts
async function lazyUseLibrary
  import { getX } from library
  return getX()
// to
async function lazyUseLibrary() {
  const { getX } = await import("library");
  return getX();
}
```
note that things like `assert { type: "json" }` still work: `await import('./foo.json', { assert: { type: 'json' } })`

**Comment by edemaine** [comment]
Do we definitely want to do the automatic `library` → `"library"` conversion here? Because unlike static imports, this has a meaning with `library` remaining a variable.

**Comment by STRd6** [comment]
I think the module specifier would need quotes when used in this position.

**Comment by STRd6** [comment]
> I think the module specifier would need quotes when used in this position.

Though maybe not, since this is still in statement position we could infer and only require quotes when used as an expression.

Will likely require a bit of playing around with to find out the best way.

**Comment by esthedebeste** [comment]
thinking about just allowing quotification if it starts with a url scheme (`node:fs`, `npm:meow`), `./`, or `../`
