### ISSUE TITLE
`@` in initializer for member variables

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#745]
We currently support:

```coffee
class X
  @foo = 1
```

Even this works:

```coffee
class X
  @foo = 1
  @bar = @foo  // should get value 1
↓↓↓
class X {
  static foo = 1
  static bar = this.foo  // gets value 1
}
```

But the following does not:

```coffee
class X
  @foo = 1
  bar = @foo  // should get value 1
↓↓↓
class X {
  static foo = 1
  bar = this.foo  // but this likely gets undefined
}
```

I think it should instead act like so:

```coffee
class X {
  static foo = 1
  bar = this.constructor.foo  // gets value 1
}
```

The concept is that, at the class scope, `@foo` should consistently refer to a static variable `X.foo`.

For comparison, [here's CoffeeScript's compilation](https://coffeescript.org/#try:class%20X%0A%20%20%40foo%20%3D%201%0A%20%20bar%20%3D%20%40foo%0A). It does correctly bind `@foo` to `X.foo` in this case. But it's compiling the member variable differently, obviously. Related to #457.

**Comment by edemaine** [comment]
After some more discussion, this might be wrong. Consider:
```js
class X
  foo = 1
  bar = @foo  // 1?
```
This is pretty natural coming from JS semantics. And if we want to support this, we probably don't want to redefine `@foo` to mean `this.constructor.foo`.

**Comment by STRd6** [comment]
There's been some requests for a `this.constructor` shorthand.
