### ISSUE TITLE
Add support for pipe operator, function currying, and partials

### ISSUE THREAD

**Issue by francescoagati** [DanielXMoore/Civet#75]
Livescript support piping partials and curry function. Should be nice have this in Civet

**Comment by STRd6** [comment]
Thanks for the suggestions!

We'll probably add the `|>` pipe operator at some point.

I don't think we'll add LiveScript's operators as functions, instead we have `&` function syntax which covers a lot of that same need.

```
list.map &+1
people.map &.name
---
list.map($=>$+1)
people.map($=>$.name)
```

I also don't think we'll add `-->` curried functions but I'm open to be convinced with examples.

**Comment by edemaine** [comment]
We now have the pipe operator `|>`, but I think we're still lacking in what are called placeholders in [the TC39 proposal](https://github.com/tc39/proposal-pipeline-operator/issues/91), which I think is a natural way to support partials/currying. Copying from https://github.com/DanielXMoore/Civet/pull/83#issuecomment-1364739339 :

I imagine it's really common to want to pass the piped value in as a first argument to a function, with other arguments given explicitly. What we want is shorthand for `($) => func($, foo, bar)`.

* One proposal on Discord was `func((&), foo, bar)`, where each extra layer of parens around `&` pushes the function wrapper up a level.
* Another option might be `func(&&, foo, bar)`, where each additional `&` pushes the function wrapper up a level.
* A bolder option would be to redefine the meaning of `func(&, foo, bar)` in the context of the right-hand side of `|>` (probably a bad idea?).
* The TC39 proposal suggests `func(%, foo, bar)` or [various other notation](https://github.com/tc39/proposal-pipeline-operator/issues/91) that is specific to pipelining; for example, `^^` might mean the left-hand side of `|>` (no matter how deep we are), or we could optionally add an identifier like `|foo>` to mean "wrap the right-hand side in a function with single argument `foo`). For example, `|$> func($, foo, bar)` would be equivalent to `|> ($) => func($, foo, bar)`.

Not sure what's best, but it kind of highlights the limitation of the current `&` notation... yet it feels like we're close.

**Comment by STRd6** [comment]
I think using explicit arrow functions as a way to re-order arguments or specify a local alias is good. That way you can add type annotations and make use of destructuring and everything should compose fine. This way we can combine with existing language features rather than making special purpose syntaxes for every situation.

```typescript
x + 1 |> ($) => $ * $
```

```typescript
credentials
|> login
|> getUser
|> ({id}) => register id, 1
```

**Comment by sultan99** [comment]
I have noticed the `->` is taken for the function declaration.
It could be great if it were for curried functions.
Just an example:

```ts
fun add(x::number, y::number)
  x + y

// equals 👇
function add(x: number, y: number) {
  return x + y
}

add := (x:: number, y:: number) => x + y
// equals 👇
const add = (x: number, y: number) => x + y

add := (x:: number, y:: number) -> x + y
// equals 👇
const add = curry((x: number, y: number) => x + y)

// 🧂add can be called:
add(1, 2)
add(1)(2)


// usage
input := 4

// pipe version
input
  |> add(3)
  |> minus(2)
  |> console.log
 
// function composition
const compute = compose(
  console.log,
  minus(2),
  add(3),
)

compute(input)

// prints 👉 5
```

Or maybe we can use '>->' ?
<img width="51" alt="image" src="https://user-images.githubusercontent.com/2598056/211211058-6e05b58e-c36e-483d-be09-9e70002f8989.png">

Many [monospaced fonts](https://github.com/tonsky/FiraCode) have that array in ligatures.

**Comment by STRd6** [comment]
@sultan99 Thanks that's a great example for how curried functions can combine with the pipe operator.

I think using LiveScript's `-->` or your suggestion of `>->` for a curried function declaration is something we could add.

**Comment by sultan99** [comment]
@STRd6, any of these can be!

`-->` & `>->` monolisa & fira fonts have them:
<img width="72" alt="image" src="https://user-images.githubusercontent.com/2598056/211212271-0a28f30d-35ef-41ff-99a3-793ef5f124a5.png">

**Comment by gustavopch** [comment]
What about `~>`?

**Comment by STRd6** [comment]
> What about `~>`?

Ideally whichever we choose would have both `==>` and `-->` versions to correspond to the two ES flavors of functions.

**Comment by sultan99** [comment]
I have checked the ligatures, and we all of them!

== === != !== > -->  => ==> ~> >->
👇
<img width="308" alt="image" src="https://user-images.githubusercontent.com/2598056/211214539-60946a75-048f-4e56-8dae-59bd86cc819b.png">

I think `==>` & `-->` are the best:

```ts
add := (x:: number, y:: number) ==> x + y
// equals 👇
const add = curry((x: number, y: number) => x + y)

add := (x:: number, y:: number) --> x + y
// equals 👇
const add = curry(
  function(x: number, y: number) {
    return x + y
  }
)
```

In the second example, we can use `this`.
Not sure why but anyway: 

```ts
add := (x:: number, y:: number) -->
  console.log(&.name)
  x + y
```

**Comment by sultan99** [comment]
Guys, it would be sexy syntax!

```ts
toJson := res => res.toJson()
pick := (key:: string, obj:: Record<sting: any>) ==> obj[key]


id := 123
fetch 'api/users/:#{id}'
  .then toJson
  .catch pick 'message'
  .finally console.log
```

**Comment by orenelbaum** [comment]
If we're using the `==>` operator, why do we need the `::` instead of normal `:`?
As for the compilation output, not sure you need a utility function, you could just compile it this way
```js
add := (x:: number, y:: number) ==> x + y
const add = (x: number) => (y: number) => x + y

add := (x:: number, y:: number) --> x + y
const add = (x: number) => function (y: number) { return x + y }
```

**Comment by sultan99** [comment]
I have seen `::` in the discord chat as a suggestion to use it for typing.
I'm not familiar with syntax yet and I'm still confusing proposals with real syntax.
Sorry...

**Comment by gustavopch** [comment]
@sultan99 The `::` is for https://github.com/DanielXMoore/Civet/discussions/126, where we plan to provide a more concise way to destructure and type parameters at the same time.

**Comment by kabo** [comment]
Not sure if this is the right ticket for what I'm after, let me know if not and I'll create a new ticket instead.

I use ramda a lot and I'm curious if civet could support a few things natively. Something I do a lot with ramda is create a function using pipe. For example:

```typescript
const doTheThing = R.pipe(
  R.pluck('myprop'),
  R.map(R.toUpper)
)

console.log(doTheThing([{myprop: 'hello'}])) // outputs [HELLO]
```

My attempt at doing this with civet
```
input := [myprop: 'hello']
pluck := (prop) => .map .`${prop}`

// works
input
  |> pluck 'myprop'
  |> .map .toUpperCase() 
  |> console.log

// doesn't do what I want it to do
doTheThing := pluck 'myprop' |> .map .toUpperCase()

// doesn't work either, but in a different way
doTheThing2 := .map .myprop |> .map .toUpperCase()

console.log doTheThing2 input
```

doTheThing comes out as
```typescript
const doTheThing = pluck("myprop").map(($3) =>
  $3.toUpperCase()
);

// as the first thing in the pipe is a function I would have wanted
const doTheThing = ($) => pluck("myprop")($).map(($3) =>
  $3.toUpperCase()
);
```

doTheThing2 comes out as
```typescript
const doTheThing2 = (($4) =>
  $4.map(($5) => $5.myprop)).map(($6) =>
  $6.toUpperCase()
);

// I would have wanted (note one less paren after $5.myprop, it's added to the last line instead
const doTheThing2 = (($4) =>
  $4.map(($5) => $5.myprop).map(($6) =>
  $6.toUpperCase()
));
```

[playground link](https://civet.dev/playground/?code=aW5wdXQgOj0gW215cHJvcDogJ2hlbGxvJ10KcGx1Y2sgOj0gKHByb3ApID0%2BIC5tYXAgLmAke3Byb3B9YAoKLy8gd29ya3MKaW5wdXQKICB8PiBwbHVjayAnbXlwcm9wJwogIHw%2BIC5tYXAgLnRvVXBwZXJDYXNlKCkgCiAgfD4gY29uc29sZS5sb2cKCi8vIGRvZXNuJ3QgZG8gd2hhdCBJIHdhbnQgaXQgdG8gZG8KZG9UaGVUaGluZyA6PSBwbHVjayAnbXlwcm9wJyB8PiAubWFwIC50b1VwcGVyQ2FzZSgpCgovLyBkb2Vzbid0IHdvcmsgZWl0aGVyLCBidXQgaW4gYSBkaWZmZXJlbnQgd2F5CmRvVGhlVGhpbmcyIDo9IC5tYXAgLm15cHJvcCB8PiAubWFwIC50b1VwcGVyQ2FzZSgpCgpjb25zb2xlLmxvZyBkb1RoZVRoaW5nMiBpbnB1dA%3D%3D)

Or perhaps I'm just using it wrong, perhaps the pipe operator `|>` is only intended to be used when there's a start value, and there's something like fp-ts flow operator that I'm missing? [Pipe vs flow in fp-ts](https://rlee.dev/practical-guide-to-fp-ts-part-1).

**Comment by orenelbaum** [comment]
the operator works only on a start value, you are looking for a function composition operator (flow in fp-ts) which we discussed a bit in the Discord.

**Comment by STRd6** [comment]
@kabo this might work but I agree that it would be nice to have a cleaner syntax for function composition kinds of things.

```typescript
doTheThing := ($) => (pluck 'myprop' |> .map .toUpperCase())($)
```

**Comment by kabo** [comment]
ok, so I can go ahead and create a ticket for a function composition / flow operator?

**Comment by STRd6** [comment]
@kabo Sounds good. I don't think we have another issue specifically for composition / flow yet. There are some discussions and maybe an issue that are related but we can link them in later.

Thanks for the detailed report and clear description!

**Comment by danielbayley** [comment]
> I think `==>` & `-->` are the best:

@sultan99 Agreed, out of those… There is also `=>>` and `->>`, which haven’t been mentioned, and also have ligatures.

**Comment by edemaine** [comment]
Closing this as:
* [Pipelines](https://civet.dev/reference#pipe-operator) have been implemented
* [Partials](https://civet.dev/reference#partial-function-application) have been implemented: `f(x, ., y)` compiles to `$ => f(x, $, y)`, especially useful in pipelines
  * Note that we still don't have a pipeline placeholder operator `%`. There are some limited cases not yet covered, like `|> foo(a, bar(b, %))`. But we can revisit that in the future.
* Currying has a separate issue #818
