### ISSUE TITLE
Incorrect parsing with coffeeCompat and Array#reduce

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#751]
[copied from discord]

> ```ts
> 'civet coffeeCompat'
> 
> let threads: Object[] # sparse array
> let threadCount: number
> 
> threadCount is threads.reduce (x) -> x + 1, 0
> 
> // ↓↓↓ Civet 0.6.39
> 
> let threads: Object[]; // sparse array
> let threadCount: number;
> 
> threadCount ===
>   threads.reduce(function (x) {
>     return x + 1, 0;
>   });
> ```
> CoffeeScript generates `threads.reduce(function (x) { return x + 1; }, 0)`

**Comment by STRd6** [comment]
Also a general ES issue: https://www.typescriptlang.org/play?experimentalDecorators=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAooAueAHgBUAaAPgIA9SKBKeAXhvmvjFLQGtUOAO6pmpAG44swAFChIsBGDwBnDD1IAiAJ44tsxEXacoVHsyA

**Comment by bbrk24** [comment]
Sure, but we can handle it differently when `civet coffeeCompat` is declared, right? AIUI the whole point in that directive is to change the generated code to match CoffeeScript (modulo typing).

**Comment by STRd6** [comment]
Sorry for the terse comment, I was saying the the bug is larger than just `coffeeCompat` and also applies to general ES compatibility as well so it should be fixed for all cases.

**Comment by edemaine** [comment]
Should be fixed in 0.6.50. Thanks for the report, and sorry for the delay!
