### ISSUE TITLE
`unless const` is a bit useless

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#756]
Comparing Swift and Civet here

```swift
if let foo = getFoo() {
  // foo is in scope and not nil
}
// foo is out of scope

guard let foo = getFoo() else {
  // foo is out of scope
}
// foo is in scope and not nil
```

```civet
if foo := getFoo()
  // foo is in scope and not null
// foo is out of scope

unless foo := getFoo()
  // foo is in scope but guaranteed to be null
// foo is out of scope so the value is unusable
```

**Comment by bbrk24** [comment]
There's another subtle difference here that I didn't realize at first: Swift only filters `nil`, while Civet filters all falsey values. Not sure which one is more generally useful in the JS ecosystem; Swift doesn't have a concept of "falsey" as you can't convert other types to `Bool`.

**Comment by edemaine** [comment]
Interesting. Do you have a proposal for different `unless` behavior? It feels weird for `foo` to be accessible in the block *after* `unless`. In particular I assume the `guard else` clause is forced to return somehow. So I think the analogous place for `foo` to be accessible would be in the `else` block, as in:

```js
unless foo := getFoo()
  // foo is in scope but guaranteed to be falsey
else
  // foo should maybe be in scope, but isn't yet
```

Actually, I see that we currently don't support `unless ... else`, but I'd prefer that we do.

Regarding falsey vs. null: it might be nice to have a way to specify testing for null values, as in our `foo?` operator — something like:

```js
if (foo := getFoo())?
// or
if? foo := getFoo()
```

**Comment by bbrk24** [comment]
Swift generally allows pattern-matching of sum types ("enums") in if statements:

```swift
enum E {
  case foo(Int)
  case bar(String)
}

if case E.foo(let i) = x {
  ...
}
```

`if let x = y` and `if case let x? = y` are special-case shorthands for `if case Optional.none(let x) = y`.

And yes, the block following a `guard ... else` statement is required to do one of the following:
- `return` or `throw`
- call a function that returns `Never`
- if in a loop or switch, `break` or `continue`

**Comment by bbrk24** [comment]
I suppose the `throw` and `Never` cases in particular could be `foo := getFoo() ?? throw new Error`, but that wouldn't work for the loop keywords or `return`.

**Comment by edemaine** [comment]
Pattern matching `unless` is even more useless. Here's the current behavior:

```js
unless [x, ...] := f()
↓↓↓
let ref;
if((!(ref = f())) && Array.isArray(ref) && ref.length >= 1) {
  const [x, ...ref1] = ref;
}
```

That `if` condition will *never* be true, because arrays are always truthy.
