### ISSUE TITLE
Enchanced ES6 or ESNext mode, but not TS?

### ISSUE THREAD

**Issue by unit-404** [DanielXMoore/Civet#759]
I would an ES6 or ESNext mode of Civet, without typescript types and strictness. Do you have plans about that?

**Comment by edemaine** [comment]
Could you clarify what specific behaviors you're looking for, that Civet doesn't already provide (if you just choose not to use TypeScript features)?

**Comment by unit-404** [comment]
I mean about not checking for async or sync function type, not checking types in general, implicit arguments spread (to func call).

**Comment by edemaine** [comment]
I believe Civet already does those things:
* it automatically adds `async` to any functions using `await`, so you don't have to worry as much about async vs sync (unless you wanted sone kind of implicit `await`)
* Civet doesn't check types, and doesn't require you to specify them. 
* You can use rest arguments without types.

I'm probably missing something though. Maybe give Civet a try and give some specific examples if what you run into?

**Comment by unit-404** [comment]
Just VS code thinking that Civet is TypeScript, and validify as it.

**Comment by bbrk24** [comment]
If you throw `// @ts-nocheck` at the top of the file, the language server will stop trying to typecheck it.

**Comment by unit-404** [comment]
I don't know why fallthrough switch isn't convert to 'break;' version by default.
