### ISSUE TITLE
CoffeeScript compatibility issue: `do` expressions

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#763]
This is a bit of an edge case, but given the following CoffeeScript code:

```coffee
f = ->
  foo.bar = do
    bar = getBar()
    bar.baz = 3
    bar
```

CoffeeScript itself produces this:

```js
f = function() {
  var bar;
  foo.bar = (bar = getBar())();
  bar.baz = 3;
  return bar;
};
```

The indentation is misleading: the lines `bar.baz = 3` and `bar` are not part of the `do` expression, but statements at the top level of `f`. Civet with `'civet coffeeCompat'` follows the indentation and produces this output:

```js
f = function () {
  var bar;
  return (foo.bar = (bar = getBar()(
    (bar.baz = 3),
    bar
  ))());
};
```

**Comment by edemaine** [comment]
Related CoffeeScript issue: https://github.com/jashkenas/coffeescript/issues/5458

Like that proposal, I think Civet should fail to parse / emit an error here (in `coffeeCompat` mode).
