### ISSUE TITLE
Auto-typing of return.value when function return value has been explicitly typed?

### ISSUE THREAD

**Issue by gwhitney** [DanielXMoore/Civet#765]
Tangentially related to the discussion in #744, I note in the playground that
```
function dupem(thing: Record<string, string>): Record<string, string>
   return := {}
   for item, value in thing
     return.value[item] = value + value
```
compiles to
```
function dupem(
  thing: Record<string, string>
): Record<string, string> {
  const ret = {};
  for (const item in thing) {
    const value = thing[item];
    ret[item] = value + value;
  }
  return ret;
}
```
which then doesn't type in TypeScript, with an error

`S7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.`

Couldn't/shouldn't civet generate
```
function dupem(
  thing: Record<string, string>
): Record<string, string> {
  const ret: Record<string, string> = {};
  ...
```
instead when the function has been explicitly typed? In that case, we know what type `ret` has to be, so it can't be any detriment to the type checking to explicitly type it, it seems to me.

**Comment by STRd6** [comment]
Yes, we probably should.

**Comment by edemaine** [comment]
FWIW, this code already gets the correct typing:

```coffee
function dupem(thing: Record<string, string>): Record<string, string>
   return = {}
   for item, value in thing
     return.value[item] = value + value
```

The only difference is whether `return` is declared (`:=`) or just assigned (`=`). Civet knows how to create a fresh declaration correctly, but modifying an existing declaration is a bit harder. Will try to get it working though; I agree it should work either way.

**Comment by gwhitney** [comment]
Ah. I guess since the first example in the Civet reference involves declaring return, I thought you had to declare it to get the magic return behavior. I didn't notice that an undeclared assignment to return was going on in the center of the second example. Perhaps the reference should say under what circumstances you might or might not want to declare return rather than just start assigning to it; I suppose the main reason would be to make it const? I.e., in that first example in the reference, there's really no reason to write `return .= 0` (as is shown) versus `return = 0`, is there? Maybe that's why I assumed a declaration was necessary.
