### ISSUE TITLE
unplugin watch

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#773]
The esbuild unplugin doesn't currently work with [`watch`](https://esbuild.github.io/api/#watch). I believe we need to return [`watchFiles`](https://esbuild.github.io/plugins/#on-resolve-results).

Progress so far:
- [x] Rollup
- [x] Webpack
- [x] Vite build mode
- [x] Vite dev mode
- [x] esbuild (waiting on https://github.com/unjs/unplugin/pull/345)

**Comment by STRd6** [comment]
This probably requires a PR to https://github.com/unjs/unplugin/

https://github.com/unjs/unplugin/blob/39c0b22a30bdd7112962e377c39d2a24dcbc5847/src/esbuild/index.ts#L64 is setting the namespace to the plugin name and not `file` which is required by esbuild to watch paths.

https://esbuild.github.io/plugins/#on-resolve-results

**Comment by STRd6** [comment]
Additionally there is currently no way in unplugin to pass through `watchFiles` or `watchDirs`.

**Comment by edemaine** [comment]
unplugin [claims support for `this.addWatchFile`](https://github.com/unjs/unplugin/blob/main/README.md#supported-1) but not yet for esbuild. Maybe we can easily add it (via a PR to unplugin) by storing them in an array and returning it from [`getWatchFiles`](https://github.com/unjs/unplugin/blob/39c0b22a30bdd7112962e377c39d2a24dcbc5847/src/esbuild/utils.ts#L134).

**Comment by STRd6** [comment]
Watch works in [`esbuild-plugin`](https://github.com/DanielXMoore/Civet/blob/main/source/esbuild-plugin.civet) but it has some other bugs (something with sourcemaps, and https://github.com/DanielXMoore/Civet/issues/750). We may be able to update it to be at parity and it would help us understand the build process better as well.

**Comment by STRd6** [comment]
I think the core unplugin issue is that it sets `namespace` to be the name of the plugin instead of `file` which causes the files to not be visible to `watch`.

**Comment by edemaine** [comment]
I'm not sure removing the `namespace` setting from unplugin would fix the problem, because our `resolveId` callback (`onResolve` in esbuild terminology) adds a `.tsx` or `.jsx` extension to the filename, so it will no longer be a valid filename. (I assume this means watch is broken in all systems? Also it maybe explains the choice of namespace.) I'm hoping implementing `addWatchFile` might be a better universal solution for all build systems.

**Comment by edemaine** [comment]
Update: #780 fixed watch mode on Rollup and Webpack. esbuild is waiting on https://github.com/unjs/unplugin/pull/345 gets merged. Vite still isn't working (on Windows or Linux).

**Comment by edemaine** [comment]
Vite dev mode was fixed by #860, and esbuild was fixed by #895. 0.6.61 should have a fully working watch mode!
