### ISSUE TITLE
Vite unplugin doesn't support project-absolute paths

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#774]
> The paths also seem to be resolved differently if I'm building it, but only if it's a civet file. By default the script looks like this in `index.html`: `/src/main.ts`, note the starting `/`, which works normally with Vite and even works with `.ts` file even if I use the civet plugin. But if I use `/src/main.civet` it seems to try to resolve it from the machine's root, not the project root and doesn't find the file. Only in build. Changing it to `./src/main.civet` works but it is different from normal Vite though.

[Stackblitz Reproduction](https://stackblitz.com/edit/vitejs-vite-vy56su?file=index.html)

**Comment by STRd6** [comment]
What's the proper way to define project-absolute paths so the TS LSP picks it up?

In my testing it (surprisingly) worked with the Civet LSP in `.ts` files but the TS LSP thinks they are actual absolute paths and I don't know any config option to set to make TS understand this pattern.

Any thoughts?

**Comment by edemaine** [comment]
I think you can use `baseUrl` (unclear if it works with leading slash though). `paths` is also a common solution.

**Comment by STRd6** [comment]
The Stackblitz web based editor seems to pick it up fine but the same project and same configuration don't work locally on VSCode 🙀 

![image](https://github.com/DanielXMoore/Civet/assets/18894/2a7e4d6d-4e93-4eba-a65a-c727de0e3d4e)

![image](https://github.com/DanielXMoore/Civet/assets/18894/c89e99ef-f350-4245-8c10-09ef9e830826)
