### ISSUE TITLE
if-const + try throws a compiler error

### ISSUE THREAD

**Issue by aleksrutins** [DanielXMoore/Civet#792]
When using `if` with constant assignment from a `try` expression:
```coffee
if x := try hello()
  print "hello"
```

The compiler throws:
```
Cannot read properties of undefined (reading 'type')
```

This works properly with a non-constant assignment, however:
```coffee
if x = try hello()
  print "hello"
```

I found this while messing around in one of the playground boxes on the homepage.

**Comment by edemaine** [comment]
Should be fixed in 0.6.49. Thanks for the report!
