### ISSUE TITLE
Python-style imports?

### ISSUE THREAD

**Issue by sudo97** [DanielXMoore/Civet#800]
I'm not sure if that's possible, just been reading the reference, and realized that it would be a great development experience, when one could write
```
from "module" import { a, b}
```

thus IDE would be able to tell us what is there to import

**Comment by edemaine** [comment]
Yep, this is planned! See discussion https://github.com/DanielXMoore/Civet/discussions/320. Adding it to the language should actually be pretty easy.

On the other hand, I'm not sure how to make the LSP give the import hints, but hopefully it is possible.

**Comment by esthedebeste** [comment]
sourcemapping (`|` is cursor) `from library import {| }` to `import {| } from library` would work, right? 

also, for a little extension of this proposal, this syntax could allow for unambiguous braceless renamed imports (that look exactly like python); `from library import PI as HALF_TAU` => `from library import { PI as HALF_TAU }` => `import { PI as HALF_TAU } from "library"`.
