### ISSUE TITLE
Strange behavior and errors when using unplugin with vite or esbuild

### ISSUE THREAD

**Issue by mixty1** [DanielXMoore/Civet#804]
I've got some issues with vite and/or bun(tried esbuild too).

My `package.json`:
```json
{
  "name": "myapp.js",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@danielx/civet": "^0.6.50",
    "@types/node": "^20.9.0",
    "@types/uuid": "^9.0.7",
    "bun-types": "^1.0.11",
    "typescript": "^5.2.2",
    "vite": "^4.5.0"
  },
  "dependencies": {
    "uuid": "^9.0.1"
  }
}
```

`node version 20.7.0`
`npm version 10.1.0`
`bun version 1.0.11`

I have 2 `.civet` files:
```tsx
project-root/
  src/
    main.civet
    SortableDnD.civet
  index.html
  vite.config.ts
  bunfig.toml
  ...
```

`index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + TS</title>
  </head>
  <body>
    <style>
      ul {
        /* display: flex; */
      }
      li {
        width: 100px;
        height: 100px;
        background-color: brown;
        margin-bottom: 10px;
        transform: translate3d(var(--x), var(--y), 0);
        will-change: transform, left, top;
        contain: layout;
        user-select: none;
      }
    </style>
    <div id="app">
      <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
      </ul>
    </div>
    <script type="module" src="./src/main.civet"></script>
  </body>
</html>
```

`vite.config.ts`:
```tsx
import { defineConfig } from 'vite'
import civetVitePlugin from '@danielx/civet/vite'
import path from 'path'

export default defineConfig({
  resolve: {
    extensions: ['.civet', '.tsx', '.jsx', '.js', '.ts'],
    alias: {
      '@': path.resolve(__dirname, './src')
    }
  },
  plugins: [civetVitePlugin({})]
})
```

`bunfig.toml`:
```toml
preload = ["@danielx/civet/bun-civet"]

[loader]
".civet" = "tsx"
```

`main.civet`:
```tsx
SortableDnD from './SortableDnD'

SortableDnD.create '#app ul'
```

When i try to start `vite dev` it starts, but on the page in console i've got an error:
`Uncaught SyntaxError: Unexpected string (at SortableDnD.civet?import:1:21)`

`SortableDnD.civet`:
```tsx
{ v4: uuidv4 } from 'uuid'

interface IOptions
  itemSelector?: string
  clone?: boolean


export default class SortableDnD
  #cloneEl?: HTMLElement
  #target: HTMLElement
  #children: (Element | Node)[] = []
  #draggable: HTMLElement | null = null
  #bbox: DOMRect | null = null
  #raf: number | null = null
...
```

Maybe he thinks it's a tsx file, i can't understand this behavior.

Strange thing if i add `.civet` extension in `main.civet` for this line: `SortableDnD from './SortableDnD.civet'` and start dev server, he throws another error:
```
The keyword 'interface' is reserved (Note that you need plugins to import files that are not JavaScript)
file: src/SortableDnD.civet.tsx:3:0
1: import { v4 as uuidv4 } from 'uuid'
2: 
3: interface IOptions {
   ^
4:   itemSelector?: string
5:   clone?: boolean
```

And other strange things is with bun, when i type `bun ./src/main.cviet`, it throw error:
```
44 |     #target =
45 |       if target <? 'string'
46 |         document.querySelector<HTMLElement>(target) ?? throw new Error errMsg
47 |       else
48 |         target
49 | 
           ^
ReferenceError: Can't find variable: document
```

Ok, maybe it bug in bun.
Now i start again `vite dev` and it works(but hot reload not work), but if i try to start `vite build` it throws errors, that was before `bun` command with `vite dev` command. And i don't know how, but this behavior resets maybe when i reload vscode and reinstall node_modules and then it starts all over again.

I've tried with `esbuild` too, same strange behavior =(
I took `esbuild` config from [this](https://github.com/DanielXMoore/Civet/tree/main/integration/unplugin/examples/esbuild) examples folder

When I used `vite-plugin-civet` everything was fine, but when I updated versions and tried new integrations, this above happened.

**Comment by edemaine** [comment]
Currently, the `.civet` extension is required in `import`s, but we will add a feature for implicit extensions. As you confirmed, replacing your first line of `main.civet` with
```js
SortableDnD from './SortableDnD.civet'
```
works for dev mode. (Now all errors seem to be in the code itself. Same for Bun, which doesn't define `document`.)

There's a separate issue, which we are already working on, that Rollup (as used by Vite's build mode) needs our plugin to do TS → JS conversion ourselves. For now, you can specify `js: true` in the plugin's options:
```js
plugins: [civetVitePlugin({
  js: true
})]
```
But note that `js: true` supports most but not all TypeScript features. We'll offer alternatives to this option in the future.

**Comment by mixty1** [comment]
Thank you for your quick response. Yes, now the `vite build` works correctly. I hope you can find a solution for hot reload, because now changes only works if you manually restart the dev server😔.

**Comment by edemaine** [comment]
I'm happy to report that, as of Civet v0.6.57:
* `vite dev` now correctly watches files and updates via HMR.
* Importing `'./SortableDnD'` should now work, with an implicit `.civet` extension.

We've also changed how TypeScript gets handled via the [new `ts` flag](https://github.com/DanielXMoore/Civet/tree/main/integration/unplugin#options); the default behavior is the equivalent of `js: true` described above, but there are other options with more complete TypeScript support.
