### ISSUE TITLE
Named export default

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#806]
I think "everything is an expression" should imply the following:
```js
export default name := "abc"
↓↓↓
const name = "abc"
export default name
```
This would in particular be consistent with our implicit `return` for an assignment at the end of a function.

The motivation is the same: useful to be able to name something when exporting it, even if the export doesn't have a name. Here it could actually be functional, too, as `name` could be used elsewhere (below) within the module.

Currently supported workaround:
```js
"civet autoVar"
export default name = "abc"
```

**Comment by bbrk24** [comment]
This seems to be done now: https://civet.dev/playground?code=ZXhwb3J0IGRlZmF1bHQgZm9vIDo9IDU%3D probably by the same thing that fixed #965 . Can this be closed now?
