### ISSUE TITLE
Cannot find module '@danielx/civet/esbuild-plugin' or its corresponding type declarations.

### ISSUE THREAD

**Issue by thetarnav** [DanielXMoore/Civet#81]
There are no types for the `esbuild-plugin` submodule. This is useful when creating esbuild/tsup configs with typescript.

![image](https://user-images.githubusercontent.com/24491503/209389059-7764d40d-06a7-4d26-b7fa-4af15036d61a.png)

**Comment by STRd6** [comment]
I pushed a simple fix, let me know how it goes!
