### ISSUE TITLE
Parse error on multiline constructor arguments with defaults

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#811]
Doing this using `public` is fine

```coffee
class Test
  @(
    public a : number = 0
    public b : number = 1
  )
```

But using `@` leads to a parse error

```coffee
class Test2
  a : number
  b : number
  @(
    @a : number = 0 
    @b : number = 1
#               ^ Parse Error
  )
```

Putting a comma at the end of the previous line resolves the error but I guess that shouldn't be needed.

**Comment by edemaine** [comment]
I imagine this is #760, which we only partially fixed. Thanks for the real-world example where it fails! This will help is verify that a fix works properly.
