### ISSUE TITLE
Unplugin-civet error: could not load some path

### ISSUE THREAD

**Issue by mixty1** [DanielXMoore/Civet#813]
I've got an error when `vite build` as lib:
`[unplugin-civet] Could not load Users/<username>/Development/mylib.js/src/lib.civet.jsx: ENOENT: no such file or directory, open '/Users/<username>/Development/mylib.js/Users/<username>/Development/mylib.js/src/lib.civet'`

I think he tries to concat project root dir with file absolute path.

```tsx
// vite.config.ts

import { defineConfig } from 'vite'
import civetVitePlugin from '@danielx/civet/vite'
import path from 'path'

export default defineConfig({
  resolve: {
    extensions: ['.civet', '.tsx', '.jsx', '.js', '.ts'],
    alias: {
      '@': path.resolve(__dirname, './src')
    }
  },
  plugins: [civetVitePlugin({ js: true })],
  build: {
    lib: {
      entry: path.resolve(__dirname, './src/lib.civet'),
      name: 'Main',
      fileName: 'main'
    }
  }
})

```

`OS: MacOS Sonoma 14.0`

Maybe the problem is [here](https://github.com/DanielXMoore/Civet/blob/0efd56eb5fff8f35173a17623064279753409476/integration/unplugin/src/index.ts#L224)

I tried to fix it in my own `node_modules` folder:
`node_modules/@danielx/civet/dist/unplugin-shared.js`

this line of code:
```js
const absolutePath = rootDir != null && path.isAbsolute(id) ? path.join(rootDir, id) : path.resolve(path.dirname(importer ?? ""), id);
```
to this code:
```js
const absolutePath = rootDir != null && path.isAbsolute(id) ? path.join(id) : path.resolve(path.dirname(importer ?? ""), id);
```
And it's worked.

I think it's not correct fix, but i don't deeply explored in `unplugin` code😅

**Comment by edemaine** [comment]
Apologies; some of our recent changes to unplugin hadn't been released yet. Can you try v0.6.51? This should fix the bug with absolute paths.

**Comment by mixty1** [comment]
Thx, now it's working!)
