### ISSUE TITLE
Pattern matching with an enum value

### ISSUE THREAD

**Issue by JUSTIVE** [DanielXMoore/Civet#821]
```ts
enum A {
  B=0,
  C=1
}

const x:A = A.B

switch x
  B
    => console.log "B"
  C
    => console.log "C"
```

I though the code above should be parsed correctly, but in playground, it shows error like this:

```ts
enum A {
  B=0,
  C=1
}

const x:A = A.B

switch x
  B
  ^ ParseError
```

**Comment by unlessgames** [comment]
It should be `A.B` inside the switch as `B` is defined under `A` in your example, but that still doesn't parse. 

The closest I found to parse successfully is using `is` or `==`:

``` coffee
switch x
  is A.B
    console.log "ab"
  == A.C
    console.log "ac"
```

**Comment by JUSTIVE** [comment]
Thanks for the reply! here's another following question:  how can I match a pattern if an enum-typed value is a field of an object? 

```
enum A {
  B=0,
  C=1
}

type X = {
  value : string
  key : A
}

const x:X = {
  key: A.B
  value: "a"
}

switch x
  { key: A.B, value:"a" }
    console.log "b"
  { key: A.C }
    console.log "c"

console.log a
```
from the code above, I want to evaluate to `b` only when `key` is A.B and value is `a`.

**Comment by unlessgames** [comment]
I guess this is where this missing feature you've found of pattern matching with enums starts to become more inconvenient.

This is the simplest workaround I could come up with using the [infix operator](https://civet.dev/reference#functions-as-infix-operators) feature, maybe someone else with chime in something better.

```coffee

enum A
  B
  C

type X =
  value : string
  key : A

x : X :=
  key : A.B
  value : "a"

operator key := (x : X, k : A) => x.key is k

switch x
  key A.B
    console.log "b"
  key A.C
    console.log "c"
```

Note it only matches the `key` and not `value` and won't work with non-X types (this would require generic type annotation or using some interface when defining the custom operator to not anger the type checker).

**Comment by edemaine** [comment]
Back to what the language *should* be, I think we should allow `A.B` (member expressions with at least one dot) to be treated like constants, as follows:

```js
switch x
  A.B
    console.log "b"
  A.C
    console.log "c"
---
if (x === A.B) {
  console.log("b");
} else if (x === A.C) {
  console.log("c");
}
```

Plausibly I think `^A.B` should also be treated identically to `A.B`, as the meaning is intuitively the same. Currently it's [rather broken](https://civet.dev/playground?code=c3dpdGNoIHgKICBeQS5CCiAgICBjb25zb2xlLmxvZyAiYiIKICBeQS5DCiAgICBjb25zb2xlLmxvZyAiYyI%3D).

**Comment by JUSTIVE** [comment]
> I guess this is where this missing feature you've found of pattern matching with enums starts to become more inconvenient.
> 
> This is the simplest workaround I could come up with using the [infix operator](https://civet.dev/reference#functions-as-infix-operators) feature, maybe someone else with chime in something better.
> 
> ```coffee
> enum A
>   B
>   C
> 
> type X =
>   value : string
>   key : A
> 
> x : X :=
>   key : A.B
>   value : "a"
> 
> operator key := (x : X, k : A) => x.key is k
> 
> switch x
>   key A.B
>     console.log "b"
>   key A.C
>     console.log "c"
> ```
> 
> Note it only matches the `key` and not `value` and won't work with non-X types (this would require generic type annotation or using some interface when defining the custom operator to not anger the type checker).

as shown in my second code, I also want to match the field named `value` with the value 'a'. infix operator cannot handle this case hence custom infix handles only two parameters(as far as I know. correct me if I'm wrong).

**Comment by JUSTIVE** [comment]
where can i find the `^` operator by the way? Can't find any from homepage

**Comment by unlessgames** [comment]
The `^` is the [bitwise XOR operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_XOR), it's part of core javascript.

To answer your previous question, a custom infix operator is just a function that returns a boolean, the second argument can be an object with multiple values. Depending on what cases you want to match exactly you could define it to check both `key`and `value`. Obviously it's all very workaroundish though. Below is an operator that matches whatever object has the target's keys and values.

```coffee
enum A
  B
  C

x := { value : "a", key : A.B }

operator matches := (obj, target) =>
  for key, value in target
    if obj[key] is not value then return false
  true

switch x
  matches { value : "b", key : A.B }
    console.log "this won't print"
  matches { value : "a", key : A.B }
    console.log "matching"
```

**Comment by edemaine** [comment]
We definitely need to add documentation for `^` - thanks for pointing that out. `^x` refers to the variable `x` in the parent scope, as opposed to a name `x` that should be assigned by the pattern match. For example `[x]` matches any length-1 array, while `[^x]` matches a length-1 array whose first item equals `x`. It's called "pinning" e.g. in [Erlang](https://hexdocs.pm/elixir/1.16/pattern-matching.html#the-pin-operator).

**Comment by JUSTIVE** [comment]
> To answer your previous question, a custom infix operator is just a function that returns a boolean, the second argument can be an object with multiple values. Depending on what cases you want to match exactly you could define it to check both `key`and `value`. Obviously it's all very workaroundish though. Below is an operator that matches whatever object has the target's keys and values.
> 
> ```coffee
> enum A
>   B
>   C
> 
> x := { value : "a", key : A.B }
> 
> operator matches := (obj, target) =>
>   for key, value in target
>     if obj[key] is not value then return false
>   true
> 
> switch x
>   matches { value : "b", key : A.B }
>     console.log "this won't print"
>   matches { value : "a", key : A.B }
>     console.log "matching"
> ```

oh my god, just mind-blown by the `matches`. what a wonderful approach
maybe it would be better to be embedded in the syntax(with recursive checking, of course) for the structural pattern matching.

**Comment by edemaine** [comment]
On the documentation side, I added a section on pinning to https://civet.dev/reference#pattern-matching . Let me know if you have ideas for improvement.

We still need to support `A.B` (and maybe `^A.B`) as literal values to match.

**Comment by JUSTIVE** [comment]
besides of pinning, there's still a problem with enums in structural matching.
for example, this is the original code where I found this issue.

```coffee
import { SourceFile,FunctionDeclaration, VariableStatement,SyntaxKind } from "ts-morph";

exportKeywordMatcher := (node:FunctionDeclaration|VariableStatement) =>
  switch node.compilerNode
    { modifiers: [{ kind: SyntaxKind.ExportKeyword }], }
      true
    else
      false
```

even with the pinning, it still won't work as intended.

```coffee
import { SourceFile,FunctionDeclaration, VariableStatement,SyntaxKind } from "ts-morph";

exportKeywordMatcher := (node:FunctionDeclaration|VariableStatement) =>
  switch node.compilerNode
    { modifiers: [{ kind: ^SyntaxKind.ExportKeyword }], } <-- Failed to Parse
      true
    else
      false
```

I was able to make it parsed with the `matches` operator trick above, but I can't make the operator every time.

**Comment by STRd6** [comment]
> To answer your previous question, a custom infix operator is just a function that returns a boolean, the second argument can be an object with multiple values. Depending on what cases you want to match exactly you could define it to check both `key`and `value`. Obviously it's all very workaroundish though. Below is an operator that matches whatever object has the target's keys and values.
> 
> ```coffee
> enum A
>   B
>   C
> 
> x := { value : "a", key : A.B }
> 
> operator matches := (obj, target) =>
>   for key, value in target
>     if obj[key] is not value then return false
>   true
> 
> switch x
>   matches { value : "b", key : A.B }
>     console.log "this won't print"
>   matches { value : "a", key : A.B }
>     console.log "matching"
> ```

I didn't even know Civet could do this 🙃

**Comment by edemaine** [comment]
v0.6.54 now supports pinning more general expressions, including

```js
exportKeywordMatcher := (node:FunctionDeclaration|VariableStatement) =>
  switch node.compilerNode
    { modifiers: [{ kind: ^SyntaxKind.ExportKeyword }], } //<-- Failed to Parse
      true
    else
      false
```

Simple cases like this also work without the need for pinning:

```js
switch x
  A.B
    console.log "b"
  A.C
    console.log "c"
```
