### ISSUE TITLE
x<y>z

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#824]
`x<y>z` currently fails to parse, because `x<y>` parses as a unary expression (type arguments), preventing the `<` from being recognized as a binary operator.  By contrast, `x<y>z` [parses in TypeScript](https://www.typescriptlang.org/play?#code/B4HgngfAXkA) as `x < y > z` (not that that means anything in JavaScript, but it does in Civet).

I think we should add some kind of assertion after type arguments that allows for tight comparisons like this. I'm not sure exactly what the right assertion is though... maybe there's one in the TypeScript source?

**Comment by STRd6** [comment]
Even simpler `x<y` is currently a parse error... 🙀
