### ISSUE TITLE
Unicode issues on the website

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#827]
There seem to be issues with Unicode support inside the editors on the website. 

* On the Reference page while trying to edit any of the examples with unicode symbols inside (for example the **Includes Operator**), the editor element seems to rerender and the text cursor/focus is lost. Once you remove all the unicode instances the issue goes away.

* On the Playground the above doesn't happen, instead when trying to run a unicode containing example, the last code will run instead?

1. open the Playground in an incognito window without any code in the URL
2. you get the 'Hello Civet' example
3. replace the example code by pasting any code with Unicode symbols like

```coffee
f := (x) → x * x

console.log f 4
```

4. The transpiled JS shows the correct output
5. Click Run
6. 'Hello Civet' prints to the Console Output

I guess the issue is related to the Unicode symbols not making it into the URL parameters (until you delete all Unicode symbols the URL shows the last non-unicode containing example's query string). 

Overall, this makes it confusing to test out these things on the playground as you get outputs from code that is no longer on the screen and sharing the snippets is also impossible because of the above issue.

As a sidenote I think it would be great if the reference included a comprehensive list of all the built-in unicode symbols in civet similar to the table in #555

**Comment by edemaine** [comment]
Agreed! I notice there's a console error, confirming your hypothesis that it's URL encoding related:

> DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by edemaine** [comment]
I think this is all fixed, including [a table for #555](https://civet.dev/reference#unicode-operators). Let me know if you still encounter this issue!

**Comment by unlessgames** [comment]
Great, thanks! I gave it a quick test and everything is working nicely!
