### ISSUE TITLE
Slice notations

### ISSUE THREAD

**Issue by JUSTIVE** [DanielXMoore/Civet#836]
ideas from [proposal-slice-notation](https://github.com/tc39/proposal-slice-notation)

seems like we'll have Python-like slice notations in the future, why not adopt it before JS does? (as same as pipeline operators, or pattern matching, etc..)

**Comment by edemaine** [comment]
Civet already has [slice notation](https://civet.dev/reference#array-string-slicing) (from CoffeeScript). This proposal is essentially just `:` in place of `...`, and with fewer features (no splicing, no inclusive form `..`).

We *could* support colon, but I'm not sure we need two notations for the same feature... at least until this proposal gets some traction. Stage 1 means they're considering it but not that they plan to include it (and even then they may decide to change the notation).

I didn't understand their justification for [why not use the CoffeeScript syntax](https://github.com/tc39/proposal-slice-notation#why-pick-the-python-syntax-over-the-rubycoffeescript-syntax). `x[...5]` is different from `[...5]`.

**Comment by 747** [comment]
Not sure if related, but currently in Civet:
```
for [0..1]
  console.log 'Hello Civet!'
for [0 .. 1]
  console.log 'Hello Civet!'
for [0...1]
  console.log 'Hello Civet!'
```
gives
``` ts
for (let i = 0; i <= 1; ++i) {
  console.log("Hello Civet!");
}
for (let i1 = 0; i1 <= 1; ++i1) {
  console.log("Hello Civet!");
}
for (let i2 = 0; i2 < 1; ++i2) {
  console.log("Hello Civet!");
}
```
but
```
for [0 ... 1]
  console.log 'Hello Civet!'
```
returns `ParseError`.

Also,
```
for i in [0 ... list]
  console.log 'Hello Civet!'
```
becomes
``` ts
for (const i in [0(...list)]) {
  console.log("Hello Civet!");
}
```

**Comment by JUSTIVE** [comment]
Thank you for bringing this to my attention; I wasn't aware that this feature already existed. I agree that having multiple syntaxes for the same feature can be problematic. However, as JavaScript evolves and potentially adopts features similar to those in CoffeeScript, it might create confusion, especially for users accustomed to the colon syntax. This leads to a broader question: as future JavaScript updates potentially clash with CoffeeScript-influenced syntax in Civet, should we consider Civet as a 'TypeScript-superset' to address these overlaps?

**Comment by STRd6** [comment]
@JUSTIVE Our current strategy is to adopt the default syntax of features that make it into standard JS. In the case of situations where Coffee differs from JS we'll go with the JS (`of` for example). Sometimes we can expand the JS syntax to fill in the gaps (rest parameters in any position). Occasionally but very rarely we'll use a non-standard JS syntax if it's worth it (`@@decorators` so we can keep `@property` -> `this.property`).

For these cases we try and have configuration options so people can migrate gradually. It also gives us the possibility to migrate to whatever the JS standards committees throw at us as necessary.

**Comment by 747** [comment]
Maybe I should have posted my comment as an separate bug report, but I just found this page on the top page of issues...

I don't think the current syntax creates a critical collision, and feel it can be solved with more rigorous parser, unless I'm wrong.

**Comment by edemaine** [comment]
@747 Yes, I agree it's a bug; perhaps you could split it off to a separate issue for better tracking?

**Comment by edemaine** [comment]
I think we can close this issue for now, until [proposal-slice-notation](https://github.com/tc39/proposal-slice-notation) reaches a later stage or until someone has a specific proposal.

@STRd6 points out that supporting `x[a:b]` is actually difficult in Civet, because Civet [already has a meaning for this](https://civet.dev/playground?code=eFthOmJd): `x[{a: b}]`.
