### ISSUE TITLE
Better notation to re-use `&`?

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#85]
Currently, if you want a quick function that uses the input twice, e.g. `($) => $+$`, you can write `&+$`.  I find this syntactically inappropriate, as `$` doesn't appear until you use it the second time; I don't find it at all intuitive that `&` binds `$`. And it's especially bad if you use `$` yourself or nest `&` functions inside of each other.

I would rather find a notation that is similar in the first and second uses, or that doesn't use an existing identifier. Obviously `&+&` has a meaning though, namely, `($) => $ + ($$) => $$`. And it could get more ambiguous with e.g. `&(&)`.

Some possible proposals (which I think I mentioned previously in Discord):
1. A second `&` refers to the same variable as the first, so `&+&` would mean `($) => $+$`. This would forbid nesting a `&` function shorthand inside another one, but we can use alternatives to just `&`. For example, if you want the current meaning of `&+&`, you could use something like `&+&&` or `&+&2` or `&1+&2`.
2. Almost the opposite: `&&` or `&1` could mean "re-use the last `&` variable", similar to how `$` behaves now. We could extend to `&&&` or `&2` referring to two levels up, etc.
3. Similar to 2, we could use a special notation for the current `&` argument, like `^`, or `^^` for two levels up etc.  Or `&^`, `&^^`, etc.

It occurs to me that `&&` is probably syntactically ambiguous with the `and` operator, so the above suggestions are only really serious with the `&n` notation for an integer `n`, or something else like `&^`.

FWIW, Ruby, Crystal, and Elm don't seem to have anything for this. So another option (other than leaving things as is) would be:

4. Forbid accessing the argument a second time. `&+$` would become `($$) => $$ + $`.  If you want `($) => $+$`, write that.

Also possibly related to pipe operator and https://github.com/DanielXMoore/Civet/issues/75#issuecomment-1365340146 ...

**Comment by STRd6** [comment]
I think forbidding access to the function variable is probably correct. I just sort of happens to work by chance of implementation currently.

I think in cases where you need to reference the parameter using an explicit arrow function is the simplest and most direct way to do it.

**Comment by edemaine** [comment]
Sounds good. I think we can turn `$` into a Ref to achieve this?

**Comment by STRd6** [comment]
@edemaine Yes, that should work.

**Comment by lorefnon** [comment]
I didnt realize something like `&+&` doesn't work - that is counterintuitive. 

For multiarg probably the closest precedent in mainstream langs is swift - which allows `$n` eg. `numbers.reduce(0) { $0 + $1 }` which is nice but I too think its not that much better than just having an inline lambda with named args.

**Comment by edemaine** [comment]
Huh, I was wondering about wrapping `&` expressions (or some other notation) in braces to indicate where the function wrapper goes (especially for placeholders). But yeah, not much more concise than an arrow function. I guess the nice thing is not having to spend time naming the arguments and not having to repeat them more than once... So I think it still might be interesting to think about.

**Comment by lorefnon** [comment]
>  I was wondering about wrapping & expressions (or some other notation) in braces to indicate where the function wrapper goes (especially for placeholders)

Yeah I think most of the ambiguity here is around identifying where the function boundary goes. I propose simply mandating that the function is explicit (similar to my other suggestion in the do discussion)

ie. `[1, 2, 3].map(new User(id: &))` -> `[1, 2, 3].map(-> new User(id: &))`

If this seems too big of a change, then can we separately adopt `it` as kotlin supports it ? If a function doesn't have any explicit arguments, it gets an implicit argument called `it` which is the solo argument. 

It is also convenient for nested lambdas, because `it` always comes from the nearest parent function without an explicit argument: 
```
[1, 2, 3].map(-> foo(name -> `name${it}`))
``` 
Transpiles to: 

```
[1,2,3].map(function(it) { 
    return foo(function(name) { 
        return `name${it}` 
    })
})
```

**Comment by STRd6** [comment]
The `$` ref part of this was fixed in https://github.com/DanielXMoore/Civet/commit/1d9e4d0a1149e2248881e1593ff9d6d54815b374

**Comment by STRd6** [comment]
It might not be too hard to get `&` as a topic reference in places where it is unambiguous. It may require some clever lookaheads in some other situations.

**Comment by STRd6** [comment]
Just had a thought that maybe we could have a syntax like `&.` but which creates a new `this` scope so that `@` is the topic reference.

```
@.something // if we want to accessor into @something
---
function(){ return this.something }.call
```

We could maybe use a different symbol as well.

**Comment by STRd6** [comment]
Did a quick search of the CoffeeScript codebase and `@.` appears zero times so it's a good candidate. We could disable it in `coffeeCompat` as well.

**Comment by STRd6** [comment]
```
items.map @\ `${@name}: ${@price}`
animals.forEach @\ console.log 'test' if @name == 'Fluffy'
```

Seems ok, but still might need to refine the symbol.

**Comment by edemaine** [comment]
Neat idea! The two issues I see are that it shadows `this` in the surrounding context (might be annoying in some cases), and that `@` already means something when followed by a `[`, `(`, or binary op (and `.` too), so the notation feels limited.

I wonder whether something like `{ @.foo }` could be shorthand for `function() { return this.foo }.call`? This has the advantage that you can actually specify the block boundary, e.g. `{ 'hello' + @ }` works. The only conflict I know is object literal syntax like `{ @foo }` but I believe that doesn't work with a dot. Oh, no, it does, with the new object literal shorthand. Also `{ @(5).x.y }` is an object literal now I think.
