### ISSUE TITLE
Unexpected output with indenting function arguments

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#869]
```coffee
v := (@x, @y) =>
  @length := () => Math.sqrt(@x**2 + @y ** 2)
  @

v
  v 2, 4
    .length()
  0.5
```
the second part compiles to 

```js
v(v(2, 4)).length()(0.5);
```

when I would expect it to become

```js
v(v(2,4).length(), 0.5);
```

Since if I would get that shape if I were to replace the inner `v` with a literal like

```coffee
v 
  2
  4
```
it would just be 

```js
v(2, 4)
```
It would also work if I didn't use indentation like and included parens, like

```coffee
v
  v(2, 4).length()
  0.5
```

or if I used a separate expression like

```coffee
l := v 2, 4
        .length()

v 
  l
  0.5
```

For these reasons it would be nice if the same expression inside or outside would work the same way.

**Comment by edemaine** [comment]
I'm guessing we need to add trailing `.prop` access support in an argument context.
