### ISSUE TITLE
Improve indentation tracking

### ISSUE THREAD

**Issue by lorefnon** [DanielXMoore/Civet#88]
So I frequently run into function application getting introduced at unexpected places. An example that currently behaves weirdly is: 

```
 foo := [
  a: 10
  b: 20
]
```

```js
const foo = [
  {a: 10({
  b: 20,
})}
]
```

There were a few previously discussed comments which were also variations of same problem: https://github.com/DanielXMoore/Civet/pull/84#issue-1511119727,  https://github.com/DanielXMoore/Civet/pull/83#discussion_r1056865524

I think crux of the problem is that our rules are evaluated inside out and indentation tracking (PushIndent, PopIndent) is interspersed in the same pass. 

So when `a: 10` is getting parsed, the rule for `NestedElementList`: 

```
NestedElementList
  PushIndent NestedElement*:elements PopIndent ->
```
is yet to be evaluated. The `PushIndent` in this rule hasn't yet run so `module.currentIndent` is still same as previous level (in this case 0)

Because of that the next indented expression `b: 20` **appears** to be indented further than current level, which is wrong. 

This can probably be addressed by a smart rearrangement of rules on a case by case basis, but that is pretty hard to reason about (atleast for me). 

A simpler solution is to potentially separate out indentation tracking in a separate previous pass (perhaps alongside lexing). 

Alternatively the parser could apply rules left -> right and also provide a way to revert any shared state modifications if rules to right don't match.

**Comment by STRd6** [comment]
I agree that indent tracking is a little complicated but I'm not sure that adding an extra parsing pass would make it less complicated. I think it is one of the core complexities of an indentation based parser. I'd be happy to take a look at other languages that have solved the problem well but I personally haven't found many good references yet.

**Comment by edemaine** [comment]
FWIW, Python and CoffeeScript have a tokenization pass that generates indent/dedent tokens separate from newline tokens, which makes for easier grammar rules. In Python this is relatively easy to do, as lines are single lines unless they end with `\` or are nested in parens. But it's extremely complicated for CoffeeScript where e.g. `+` at end of line is a continuation, and some indentation is ignored — I believe the rewriter gets involved too — so I'm not sure its approach is better.

To me the main downside of the current approach is that we can't use caching. I think it would be possible to cache using not just the range of characters but also the current indent state. But it's a lot more complicated; the cache would also need to encode the changes to the indent state.
