### ISSUE TITLE
with statement not supported

### ISSUE THREAD

**Issue by esthedebeste** [DanielXMoore/Civet#881]
While I agree the with statement is bad practice and should be avoided, there should be a way to use it within civet, for JS compatibility at least. _Or_ it should be documented as unsupported on the [comparison page](https://civet.dev/comparison)

**Comment by edemaine** [comment]
I think we've been generally assuming strict mode. I've added a [section](https://civet.dev/comparison#sloppy-mode-features) about this in the comparison page.

I didn't realize that TypeScript allowed `with`. Given this, I could see supporting it, for compatibility sake...

A related question is whether we should emit `"use strict"` in our JS output. Perhaps we should by default, but there's a way to request omitting it? Of course, it's implicit in ESM, so it's less important these days, but it's probably safer to include it unless the user needs e.g. implicit globals. Related to [TypeScript's alwaysStrict setting](https://www.typescriptlang.org/tsconfig#alwaysStrict).

**Comment by esthedebeste** [comment]
Emitting "use strict" could be default. A `notStrict` or `sloppy` parse option would be great then. If `export` or `import` are used anywhere the `"use strict"` should be omitted either way I think.

**Comment by esthedebeste** [comment]
> I didn't realize that TypeScript allowed with. Given this, I could see supporting it, for compatibility sake...

It does not support it, oops! Either way it would be a JS compat feature.

**Comment by edemaine** [comment]
Given that lack of `with` is now documented, I think this can be viewed as completed. But feel free to comment further if there's actual demand for `with`.
