### ISSUE TITLE
Strange input allowed in single-argument function shorthand

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#885]
After looking at [the fun uses of `await` and `delete`](https://civet.dev/reference#single-argument-function-shorthand) that we get after #883, I found that civet accepts this kind of input
```js
x.filter not.condition
x.forEach delete.old

↓↓↓

x.filter(($) => !$.condition);
x.forEach(($1) => delete$1.old);
```
In my opinion either this should be invalid syntax or there should be a space after delete

This trick doesn't work with `await`:
```js
x.map await.json()
                 ^ ParseError
```

**Comment by edemaine** [comment]
Thanks for spotting this so quickly! Should be fixed by #886.
