### ISSUE TITLE
& function shorthand with template strings

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#887]
Could be handy to be able to write

```coffee
[0,1,1,2,3,5].map `some template string ${&}` 
```

**Comment by edemaine** [comment]
This seems like a natural extension of #480 ("go up a level from a bare `&`"). Based on the discussion there, we could plausibly even allow for `` `template ${&}`.toUpperCase() `` and other trailing content like `` `template ${&}` + tail `` (as it seems unlikely you'd want to do these operations on a function).

But where it starts to get ambiguous is if you wanted to write `` `template ${&.toUpperCase()}` ``. In the special case of template strings, it seems *unlikely* that you'd want to pass a function in... but with tag functions it might actually be quite useful. So perhaps this should continue to be processed as-is. (`` `template ${($) => $.toUpperCase()}` ``)

**Comment by edemaine** [comment]
This is [now possible](https://civet.dev/playground?code=WzAsMSwxLDIsMyw1XS5tYXAgYHNvbWUgdGVtcGxhdGUgc3RyaW5nICR7Jn1gIA%3D%3D), as part of #1070. So is [the `toUpperCase` example](https://civet.dev/playground?code=WzAsMSwxLDIsMyw1XS5tYXAgYHNvbWUgdGVtcGxhdGUgc3RyaW5nICR7Ji50b1VwcGVyQ2FzZSgpfWAg).
