### ISSUE TITLE
yield in do

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#888]
What should `yield` mean inside a `do` expression/block? The [TC39 proposal](https://github.com/tc39/proposal-do-expressions?tab=readme-ov-file#awaityield) says that it should `yield` in the containing function. We [already support this with `await`](https://civet.dev/playground?code=ZiA9ICh4KSAtPgogIHkgOj0gZG8KICAgIGF3YWl0IHg%3D) but [don't for `yield`](https://civet.dev/playground?code=ZiA9ICh4KSAtPgogIHkgOj0gZG8KICAgIHlpZWxkIHg%3D).

2024 update: [`await` example that forces expression](https://civet.dev/playground?code=ZiA9ICh4KSAtPgogIHkgOj0gMSArIGRvCiAgICBhd2FpdCB4); [`yield` example crashes](https://civet.dev/playground?code=ZiA9ICh4KSAtPgogIHkgOj0gMSArIGRvCiAgICB5aWVsZCB4)

For comparison, the [Babel plugin for this proposal](https://babeljs.io/docs/babel-plugin-proposal-do-expressions) ([main source code](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/replacement.ts#L234)) [supports this feature](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mAVAAmACgJTIN4ChnIQIDOUyAHsgLzIAmcO-BhJZAntcgIwAMTBbGAFMANrWQBWJgF9c0oA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.23.3&assumptions=%7B%7D), and suggests a transpilation: just add `yield*` before the IIFE.

**Comment by STRd6** [comment]
We should match TC39 on this.

```
f = (x) ->
  y := do
    await x
```

A better transpilation for us would be something like:

```
f = async function (x) {
  let ref;
  {
    ref = await x
  }
  const y = ref;
  return y;
};
```

This ties in with removing IIFEs as much as possible as mentioned in some other issues.

**Comment by edemaine** [comment]
I agree that we should that long term. (#202 and #381 are two of the relevant issues. I've added `yield` to the title of #202.) But in the short term we can fix this case easily via `yield*`, so we should do that.
