### ISSUE TITLE
Type declarations are not emitted

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#893]
Type declarations do not currently appear when using unplugin with the emitDeclaration option enabled. So I did some investigation and came up with a fix.

When [this](https://github.com/DanielXMoore/Civet/blob/bfa20986113ec0bba19134626af3b62b581c4f94/integration/unplugin/src/index.ts#L204) callback became asynchronous, `this.emitFile` stopped working.

Either a synchronous version of mkdir is needed, or the first two lines of callback code should be removed, since, in my opinion, they only lead to an attempt to create an already existing directory (perhaps I did not understand the intent).

I got files of type declarations with this code in the example for Rollup:
```js
if (options.emitDeclaration) {
  for (const file of fsMap.keys()) {
    const sourceFile = program.getSourceFile(file)!
    program.emit(
      sourceFile,
      (filePath, source) => {
        const fileName = path.relative(
          compilerOptions.outDir ?? process.cwd(),
          filePath
        )

        this.emitFile({source, fileName, type: 'asset'})
      },
      undefined,
      true
    )
  }
}
```

I could make a PR, but I didn't understand the idea with mkdir, since directories are created inside `./dist` by `emitFile`. And it seems to me that this is not enough, since in the example for ESBuild type declarations are still not generated (maybe I overlooked something).

**Comment by edemaine** [comment]
Thanks for the detailed analysis! This was very clear. Should be implemented in v0.6.61, along with fixed watch mode in esbuild and fixes for Windows.
