### ISSUE TITLE
Allow classes to be parametric in other parametric classes (because TypeScript won't)

### ISSUE THREAD

**Issue by PatrickJS** [DanielXMoore/Civet#894]
since TypeScript won't add features for better TypeScript (because it needs to be a JavaScript pattern) maybe we can add features to provide better type DX devs who use Civet
https://github.com/microsoft/TypeScript/issues/1213
^ issue to make this code easier
https://github.com/TanStack/router/blob/beta/packages/react-router/src/link.tsx#L27...L69

**Comment by edemaine** [comment]
@PatrickJS I don't quite follow the suggestion. Is this something that can be handled by transpilation (as opposed to changing TypeScript's type checker)? (I'm hoping so, given your link to actual TS code doing something similar.) If so, could you give an example of what you have in mind for Civet source and TS output?

**Comment by PatrickJS** [comment]
yeah, basically compile to the workaround types but is probably a lot of work

**Comment by edemaine** [comment]
Could you show one example of what you'd like to write and what it would transpile to? Currently I see examples of each, but they don't match, so it's difficult to understand the goal.

**Comment by PatrickJS** [comment]
yeah I guess the proposed syntax in the ts thread in wasn't exactly finalized and looking it over and the code I guess it was more of if we had this then the code can be refactored. So nothing actionable, my bad. I'll close the issue 👍
