### ISSUE TITLE
Cannot declare multiline function

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#9]
I'm not sure what I'm missing from the readme, but I cannot seem to able to define multiline functions.

Given:
```
let bla = (one, two) ->
    console.log one
    console.log two
```

It compiles to:
```
let bla = function(one, two) {}
    console.log(one)
    console.log(two)
```

There is just a single line break after `->` and the indentation is the same on the 2nd and 3rd line.
I'm using the VSC extensions, so the language server is already displaying me an error before compilation, saying
`Cannot find name 'one'`

Changing it to an arrow function:
```
let bla = (one, two) =>
    console.log one
    console.log two
```

Results in:
```
let bla = (one, two) =>
    console.log(one)
    console.log(two)
```

Here's the same with types:
```
let bla = (one: string, two: string) =>
    console.log one
    console.log two
```

It turns to:
```
let bla = (one: string, two: string) =>
    console.log(one)
    console.log(two)
```

**Comment by zolomatok** [comment]
Hmmm, I have VSC set to `4 spaces` for indentation.
**If I use `2 spaces`, it works.**

`3 spaces` creates this weird code:

```
let bla = (one: string, two: string) => {
  return  console.log(one)  
  (console.log(two))
}
```

**Comment by STRd6** [comment]
@zolomatok Currently the indentation in Civet is hard coded at two spaces and most things will work correctly with that.

I'm currently working on an update to allow for arbitrary/deeper nesting. I'll let you know when it's out.

**Comment by zolomatok** [comment]
Ah, great, thanks Daniel!
Is there an official or unofficial roadmap for Civet?
I'm very curious to get a glimpse of what state the language is in at the moment.
Seems like there's a ton of work that already been done, I mean barring a few hiccups, the language already seems to have feature parity with coffee.

**Comment by STRd6** [comment]
@zolomatok The short term goal is to get to 97%-99% compatibility with Coffee2 using the `"civet coffeeCompat"` directive prologue. I'm running tests on the CoffeeScript codebase and fixing issues as I find them.

Then it's making sure there is a clear incremental migration path from some unfortunate Coffee inconsistencies (`for in/of/from` names are swapped, `not` precedence). Adding some extra features `&blocks`, increasing TypeScript support... and the big one of having a really nice VSCode LSP.

This section of the Readme is a pretty good place to check: https://github.com/DanielXMoore/Civet#things-removed-from-coffeescript especially the TODOs near the bottom.

**Comment by zolomatok** [comment]
Thanks Daniel, really helpful! Read the readme like 5 times but I missed that :D

+1 for optional assignment, I never understood why it's not a thing in typescript and it's always a big bummer
conditional assignment is also very nice!

Civet has a really, really bright future 🌈

**Comment by edemaine** [comment]
Also possibly of interest is a [Discord server](https://discord.gg/xkrW9GebBc) which originally had the goal of adding TypeScript features to CoffeeScript but it has a `#civet` channel where Daniel announces new releases and features and such, and we discuss direction.

**Comment by STRd6** [comment]
@zolomatok This should be fixed now (at least your specific example). Let me know if you find other cases that don't work.

**Comment by zolomatok** [comment]
Works great, thank you!

<img src="https://user-images.githubusercontent.com/11703903/203994644-1e368614-ca3f-4757-b763-27e581da39db.jpg" width=40% height=40%>
