### ISSUE TITLE
losing type information when declaring variables directly in conditionals

### ISSUE THREAD

**Issue by unlessgames** [DanielXMoore/Civet#901]
when writing 

```coffee
element := document.querySelector "#something"
if element
  element.appendChild x
```
the `element` inside the if block is known to be of type `Element` thanks to the existing information about the return type of `document.querySelector`.

But when using the shorthand, `element` is set to `any` and so all of the type information is lost in the block inside the if.

```coffee
if element := document.querySelector "#something"
  element.appendChild x
```

**Comment by STRd6** [comment]
TS is able to keep track of the type information: https://www.typescriptlang.org/play?experimentalDecorators=true#code/DYUwLgBATiBmDcAoRBLWEAUiKZugvBACYD2AxgK4C2IAdmAHQCOFIUAngMoihlglQMAIgDEAZxI0wACxS0A5kICUSxEogBvbBDIlaYyDxA16EQniQ4jJxgEMADvbpEAwrOBEMADyVIAvkA

Do you have a more specific example?

**Comment by unlessgames** [comment]
It seems that what I wrote only happens when [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny) isn't set in tsconfig.

**Comment by edemaine** [comment]
[Indeed](https://www.typescriptlang.org/play?noImplicitAny=false&experimentalDecorators=true#code/DYUwLgBATiBmDcAoRBLWEAUiKZugvBACYD2AxgK4C2IAdmAHQCOFIUAngMoihlglQMAIgDEAZxI0wACxS0A5kICUSxEogBvbBDIlaYyDxA16EQniQ4rVgPQ2AegH5tRk4wCGAB090iAYVlgIgwADyUkAF8gA). That is an unexpected side-effect of `noImplicitAny: false`!

I've added a recommendation about `noImplicitAny: true` (implied by `strict: true`) to the end of https://civet.dev/getting-started#installation

I don't think we know how to transpile this in another way that avoids this issue, so perhaps this is the best we can do?
