### ISSUE TITLE
Declarations within `if`/`for` expressions

### ISSUE THREAD

**Issue by imm** [DanielXMoore/Civet#906]
We can't do this ([playground](https://civet.dev/playground?code=YSA6PSBpZiBjb25kCiAgdG1wIDo9IHgKICBmKHRtcCkKZWxzZQogIHk%3D)):
```coffee
a := if cond
  tmp := x
  f(tmp)
else
  y
```

But we can do this ([playground](https://civet.dev/playground?code=YSA6PSBkbyBpZiBjb25kCiAgdG1wIDo9IHgKICBmKHRtcCkKZWxzZQogIHk%3D)):
```coffee
a := do if cond
  tmp := x
  f(tmp)
else
  y
```

We can also do this ([playground](https://civet.dev/playground?code=bGV0IHRtcAphIDo9IGlmIGNvbmQKICB0bXAgPSB4CiAgZih0bXApCmVsc2UKICB5Cg%3D%3D))
```coffee
let tmp
a := if cond
  tmp = x
  f(tmp)
else
  y
```
but this is lame and `let` ≠ `const`.

Is it possible to make the first example work like the second one somehow? If the `if` block contains `const` or `let`, then put the body into an anonymous function, and if not, then use the current pretty compact version with the ternary operator. I understand that it is easier said than done. Personally, I can always use `do` before `if`, in such cases, since I already figured out what the catch is. But from the user's point of view, such an `if` does not at all seem like a ternary operator, in which it is impossible to declare a local constant or variable, especially considering the experience of other languages where this is possible.

If it would be better to leave everything as is, then perhaps it is worth at least noting this case in the reference (to say that in such cases it is just a ternary operator and nothing more). The last thought, by the way, suggests that it’s a good idea to have not only a list of what you can do in Сivet, but also what you can’t do, even if you really really want to.

**Comment by STRd6** [comment]
This is something we want to support eventually. I think the overall fix will be to convert the expressions to actual blocks that execute before the assignment.

Wrapping in an IIFE as a stopgap is a good start.

Related Issues: #202 #381 #888

**Comment by edemaine** [comment]
I think this is resolved now. [The original example](https://civet.dev/playground?code=YSA6PSBpZiBjb25kCiAgdG1wIDo9IHgKICBmKHRtcCkKZWxzZQogIHk%3D) gets nicely unwrapped, and even when that's not possible because the expression is inner, [it gets wrapped in an IIFE](https://civet.dev/playground?code=YSA6PSAoaWYgY29uZAogIHRtcCA6PSB4CiAgZih0bXApCmVsc2UKICB5KQ%3D%3D).
