### ISSUE TITLE
vscode extension breaks error reporting when editing non-Civet TypeScript files

### ISSUE THREAD

**Issue by joshuahhh** [DanielXMoore/Civet#911]
Notice below how, as I press "space" before a squiggly red underline, an old copy of the error shifts around.

This is while editing a TypeScript file in a completely Civet-free project.

https://github.com/DanielXMoore/Civet/assets/643799/60ea9758-0c92-40fe-8ffb-8bd95a2e4fd7

The only way to get rid of the extra copy of the error is to restart VS Code. (Restarting the TS server doesn't help.)

Very surprising to me that the Civet extension messes up non-Civet files!

Thanks.

**Comment by STRd6** [comment]
This is definitely a bug in the Civet LSP and we should work to fix it.

The reason Civet extension affects non-Civet files is that the TypeScript Server doesn't provide a capable enough plugin system to resolve non-ts files (like `.civet`) so our LSP needs to be enable for all files that could import `.civet` files as well as `.civet` files.

A quicker fix than restarting VSCode would be to either restart the extension host or restart the Civet LSP.

Thanks for the report!

**Comment by STRd6** [comment]
I think this is fixed by https://github.com/DanielXMoore/Civet/pull/1044
