### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mixty1** [DanielXMoore/Civet#918]
I got this error on [playground](https://civet.dev/playground?code=Zm9udHMgOj0KICBzYW5zOiAiLWFwcGxlLXN5c3RlbSwgQmxpbmtNYWNTeXN0ZW1Gb250LCAnU2Vnb2UgVUknLCdSb2JvdG8nLCAnT3h5Z2VuJywgJ1VidW50dScsICdDYW50YXJlbGwnLCAnRmlyYSBTYW5zJywgJ0Ryb2lkIFNhbnMnLCdIZWx2ZXRpY2EgTmV1ZScsIHNhbnMtc2VyaWYiCiAgbW9ubzogIk1lbmxvLCBNb25hY28sICdMdWNpZGEgQ29uc29sZScsICdMaWJlcmF0aW9uIE1vbm8nLCAnRGVqYVZ1IFNhbnMgTW9ubycsICdCaXRzdHJlYW0gVmVyYSBTYW5zIE1vbm8nLCdDb3VyaWVyIE5ldycsIG1vbm9zcGFjZSIKCmRlZmF1bHRDb2xvcnMgOj0KICBzbGF0ZToKICAgIDUwOiAnI2Y4ZmFmYycKICAgIDEwMDogJyNmMWY1ZjknCiAgICAyMDA6ICcjZTJlOGYwJwogICAgMzAwOiAnI2NiZDVlMScKICAgIDQwMDogJyM5NGEzYjgnCiAgICA1MDA6ICcjNjQ3NDhiJwogICAgNjAwOiAnIzQ3NTU2OScKICAgIDcwMDogJyMzMzQxNTUnCiAgICA4MDA6ICcjMWUyOTNiJwogICAgOTAwOiAnIzBmMTcyYScKICAgIDk1MDogJyMwMjA2MTcnCiAgZ3JheToKICAgIDUwOiAnI2Y5ZmFmYicKICAgIDEwMDogJyNmM2Y0ZjYnCiAgICAyMDA6ICcjZTVlN2ViJwogICAgMzAwOiAnI2QxZDVkYicKICAgIDQwMDogJyM5Y2EzYWYnCiAgICA1MDA6ICcjNmI3MjgwJwogICAgNjAwOiAnIzRiNTU2MycKICAgIDcwMDogJyMzNzQxNTEnCiAgICA4MDA6ICcjMWYyOTM3JwogICAgOTAwOiAnIzExMTgyNycKICAgIDk1MDogJyMwMzA3MTInCiAgemluYzoKICAgIDUwOiAnI2ZhZmFmYScKICAgIDEwMDogJyNmNGY0ZjUnCiAgICAyMDA6ICcjZTRlNGU3JwogICAgMzAwOiAnI2Q0ZDRkOCcKICAgIDQwMDogJyNhMWExYWEnCiAgICA1MDA6ICcjNzE3MTdhJwogICAgNjAwOiAnIzUyNTI1YicKICAgIDcwMDogJyMzZjNmNDYnCiAgICA4MDA6ICcjMjcyNzJhJwogICAgOTAwOiAnIzE4MTgxYicKICAgIDk1MDogJyMwOTA5MGInCiAgbmV1dHJhbDoKICAgIDUwOiAnI2ZhZmFmYScKICAgIDEwMDogJyNmNWY1ZjUnCiAgICAyMDA6ICcjZTVlNWU1JwogICAgMzAwOiAnI2Q0ZDRkNCcKICAgIDQwMDogJyNhM2EzYTMnCiAgICA1MDA6ICcjNzM3MzczJwogICAgNjAwOiAnIzUyNTI1MicKICAgIDcwMDogJyM0MDQwNDAnCiAgICA4MDA6ICcjMjYyNjI2JwogICAgOTAwOiAnIzE3MTcxNycKICAgIDk1MDogJyMwYTBhMGEnCiAgc3RvbmU6CiAgICA1MDogJyNmYWZhZjknCiAgICAxMDA6ICcjZjVmNWY0JwogICAgMjAwOiAnI2U3ZTVlNCcKICAgIDMwMDogJyNkNmQzZDEnCiAgICA0MDA6ICcjYThhMjllJwogICAgNTAwOiAnIzc4NzE2YycKICAgIDYwMDogJyM1NzUzNGUnCiAgICA3MDA6ICcjNDQ0MDNjJwogICAgODAwOiAnIzI5MjUyNCcKICAgIDkwMDogJyMxYzE5MTcnCiAgICA5NTA6ICcjMGMwYTA5JwogIHJlZDoKICAgIDUwOiAnI2ZlZjJmMicKICAgIDEwMDogJyNmZWUyZTInCiAgICAyMDA6ICcjZmVjYWNhJwogICAgMzAwOiAnI2ZjYTVhNScKICAgIDQwMDogJyNmODcxNzEnCiAgICA1MDA6ICcjZWY0NDQ0JwogICAgNjAwOiAnI2RjMjYyNicKICAgIDcwMDogJyNiOTFjMWMnCiAgICA4MDA6ICcjOTkxYjFiJwogICAgOTAwOiAnIzdmMWQxZCcKICAgIDk1MDogJyM0NTBhMGEnCiAgb3JhbmdlOgogICAgNTA6ICcjZmZmN2VkJwogICAgMTAwOiAnI2ZmZWRkNScKICAgIDIwMDogJyNmZWQ3YWEnCiAgICAzMDA6ICcjZmRiYTc0JwogICAgNDAwOiAnI2ZiOTIzYycKICAgIDUwMDogJyNmOTczMTYnCiAgICA2MDA6ICcjZWE1ODBjJwogICAgNzAwOiAnI2MyNDEwYycKICAgIDgwMDogJyM5YTM0MTInCiAgICA5MDA6ICcjN2MyZDEyJwogICAgOTUwOiAnIzQzMTQwNycKICBhbWJlcjoKICAgIDUwOiAnI2ZmZmJlYicKICAgIDEwMDogJyNmZWYzYzcnCiAgICAyMDA6ICcjZmRlNjhhJwogICAgMzAwOiAnI2ZjZDM0ZCcKICAgIDQwMDogJyNmYmJmMjQnCiAgICA1MDA6ICcjZjU5ZTBiJwogICAgNjAwOiAnI2Q5NzcwNicKICAgIDcwMDogJyNiNDUzMDknCiAgICA4MDA6ICcjOTI0MDBlJwogICAgOTAwOiAnIzc4MzUwZicKICAgIDk1MDogJyM0NTFhMDMnCiAgeWVsbG93OgogICAgNTA6ICcjZmVmY2U4JwogICAgMTAwOiAnI2ZlZjljMycKICAgIDIwMDogJyNmZWYwOGEnCiAgICAzMDA6ICcjZmRlMDQ3JwogICAgNDAwOiAnI2ZhY2MxNScKICAgIDUwMDogJyNlYWIzMDgnCiAgICA2MDA6ICcjY2E4YTA0JwogICAgNzAwOiAnI2ExNjIwNycKICAgIDgwMDogJyM4NTRkMGUnCiAgICA5MDA6ICcjNzEzZjEyJwogICAgOTUwOiAnIzQyMjAwNicKICBsaW1lOgogICAgNTA6ICcjZjdmZWU3JwogICAgMTAwOiAnI2VjZmNjYicKICAgIDIwMDogJyNkOWY5OWQnCiAgICAzMDA6ICcjYmVmMjY0JwogICAgNDAwOiAnI2EzZTYzNScKICAgIDUwMDogJyM4NGNjMTYnCiAgICA2MDA6ICcjNjVhMzBkJwogICAgNzAwOiAnIzRkN2MwZicKICAgIDgwMDogJyMzZjYyMTInCiAgICA5MDA6ICcjMzY1MzE0JwogICAgOTUwOiAnIzFhMmUwNScKICBncmVlbjoKICAgIDUwOiAnI2YwZmRmNCcKICAgIDEwMDogJyNkY2ZjZTcnCiAgICAyMDA6ICcjYmJmN2QwJwogICAgMzAwOiAnIzg2ZWZhYycKICAgIDQwMDogJyM0YWRlODAnCiAgICA1MDA6ICcjMjJjNTVlJwogICAgNjAwOiAnIzE2YTM0YScKICAgIDcwMDogJyMxNTgwM2QnCiAgICA4MDA6ICcjMTY2NTM0JwogICAgOTAwOiAnIzE0NTMyZCcKICAgIDk1MDogJyMwNTJlMTYnCiAgZW1lcmFsZDoKICAgIDUwOiAnI2VjZmRmNScKICAgIDEwMDogJyNkMWZhZTUnCiAgICAyMDA6ICcjYTdmM2QwJwogICAgMzAwOiAnIzZlZTdiNycKICAgIDQwMDogJyMzNGQzOTknCiAgICA1MDA6ICcjMTBiOTgxJwogICAgNjAwOiAnIzA1OTY2OScKICAgIDcwMDogJyMwNDc4NTcnCiAgICA4MDA6ICcjMDY1ZjQ2JwogICAgOTAwOiAnIzA2NGUzYicKICAgIDk1MDogJyMwMjJjMjInCiAgdGVhbDoKICAgIDUwOiAnI2YwZmRmYScKICAgIDEwMDogJyNjY2ZiZjEnCiAgICAyMDA6ICcjOTlmNmU0JwogICAgMzAwOiAnIzVlZWFkNCcKICAgIDQwMDogJyMyZGQ0YmYnCiAgICA1MDA6ICcjMTRiOGE2JwogICAgNjAwOiAnIzBkOTQ4OCcKICAgIDcwMDogJyMwZjc2NmUnCiAgICA4MDA6ICcjMTE1ZTU5JwogICAgOTAwOiAnIzEzNGU0YScKICAgIDk1MDogJyMwNDJmMmUnCiAgY3lhbjoKICAgIDUwOiAnI2VjZmVmZicKICAgIDEwMDogJyNjZmZhZmUnCiAgICAyMDA6ICcjYTVmM2ZjJwogICAgMzAwOiAnIzY3ZThmOScKICAgIDQwMDogJyMyMmQzZWUnCiAgICA1MDA6ICcjMDZiNmQ0JwogICAgNjAwOiAnIzA4OTFiMicKICAgIDcwMDogJyMwZTc0OTAnCiAgICA4MDA6ICcjMTU1ZTc1JwogICAgOTAwOiAnIzE2NGU2MycKICAgIDk1MDogJyMwODMzNDQnCiAgc2t5OgogICAgNTA6ICcjZjBmOWZmJwogICAgMTAwOiAnI2UwZjJmZScKICAgIDIwMDogJyNiYWU2ZmQnCiAgICAzMDA6ICcjN2RkM2ZjJwogICAgNDAwOiAnIzM4YmRmOCcKICAgIDUwMDogJyMwZWE1ZTknCiAgICA2MDA6ICcjMDI4NGM3JwogICAgNzAwOiAnIzAzNjlhMScKICAgIDgwMDogJyMwNzU5ODUnCiAgICA5MDA6ICcjMGM0YTZlJwogICAgOTUwOiAnIzA4MmY0OScKICBibHVlOgogICAgNTA6ICcjZWZmNmZmJwogICAgMTAwOiAnI2RiZWFmZScKICAgIDIwMDogJyNiZmRiZmUnCiAgICAzMDA6ICcjOTNjNWZkJwogICAgNDAwOiAnIzYwYTVmYScKICAgIDUwMDogJyMzYjgyZjYnCiAgICA2MDA6ICcjMjU2M2ViJwogICAgNzAwOiAnIzFkNGVkOCcKICAgIDgwMDogJyMxZTQwYWYnCiAgICA5MDA6ICcjMWUzYThhJwogICAgOTUwOiAnIzE3MjU1NCcKICBpbmRpZ286CiAgICA1MDogJyNlZWYyZmYnCiAgICAxMDA6ICcjZTBlN2ZmJwogICAgMjAwOiAnI2M3ZDJmZScKICAgIDMwMDogJyNhNWI0ZmMnCiAgICA0MDA6ICcjODE4Y2Y4JwogICAgNTAwOiAnIzYzNjZmMScKICAgIDYwMDogJyM0ZjQ2ZTUnCiAgICA3MDA6ICcjNDMzOGNhJwogICAgODAwOiAnIzM3MzBhMycKICAgIDkwMDogJyMzMTJlODEnCiAgICA5NTA6ICcjMWUxYjRiJwogIHZpb2xldDoKICAgIDUwOiAnI2Y1ZjNmZicKICAgIDEwMDogJyNlZGU5ZmUnCiAgICAyMDA6ICcjZGRkNmZlJwogICAgMzAwOiAnI2M0YjVmZCcKICAgIDQwMDogJyNhNzhiZmEnCiAgICA1MDA6ICcjOGI1Y2Y2JwogICAgNjAwOiAnIzdjM2FlZCcKICAgIDcwMDogJyM2ZDI4ZDknCiAgICA4MDA6ICcjNWIyMWI2JwogICAgOTAwOiAnIzRjMWQ5NScKICAgIDk1MDogJyMyZTEwNjUnCiAgcHVycGxlOgogICAgNTA6ICcjZmFmNWZmJwogICAgMTAwOiAnI2YzZThmZicKICAgIDIwMDogJyNlOWQ1ZmYnCiAgICAzMDA6ICcjZDhiNGZlJwogICAgNDAwOiAnI2MwODRmYycKICAgIDUwMDogJyNhODU1ZjcnCiAgICA2MDA6ICcjOTMzM2VhJwogICAgNzAwOiAnIzdlMjJjZScKICAgIDgwMDogJyM2YjIxYTgnCiAgICA5MDA6ICcjNTgxYzg3JwogICAgOTUwOiAnIzNiMDc2NCcKICBmdWNoc2lhOgogICAgNTA6ICcjZmRmNGZmJwogICAgMTAwOiAnI2ZhZThmZicKICAgIDIwMDogJyNmNWQwZmUnCiAgICAzMDA6ICcjZjBhYmZjJwogICAgNDAwOiAnI2U4NzlmOScKICAgIDUwMDogJyNkOTQ2ZWYnCiAgICA2MDA6ICcjYzAyNmQzJwogICAgNzAwOiAnI2EyMWNhZicKICAgIDgwMDogJyM4NjE5OGYnCiAgICA5MDA6ICcjNzAxYTc1JwogICAgOTUwOiAnIzRhMDQ0ZScKICBwaW5rOgogICAgNTA6ICcjZmRmMmY4JwogICAgMTAwOiAnI2ZjZTdmMycKICAgIDIwMDogJyNmYmNmZTgnCiAgICAzMDA6ICcjZjlhOGQ0JwogICAgNDAwOiAnI2Y0NzJiNicKICAgIDUwMDogJyNlYzQ4OTknCiAgICA2MDA6ICcjZGIyNzc3JwogICAgNzAwOiAnI2JlMTg1ZCcKICAgIDgwMDogJyM5ZDE3NGQnCiAgICA5MDA6ICcjODMxODQzJwogICAgOTUwOiAnIzUwMDcyNCcKICByb3NlOgogICAgNTA6ICcjZmZmMWYyJwogICAgMTAwOiAnI2ZmZTRlNicKICAgIDIwMDogJyNmZWNkZDMnCiAgICAzMDA6ICcjZmRhNGFmJwogICAgNDAwOiAnI2ZiNzE4NScKICAgIDUwMDogJyNmNDNmNWUnCiAgICA2MDA6ICcjZTExZDQ4JwogICAgNzAwOiAnI2JlMTIzYycKICAgIDgwMDogJyM5ZjEyMzknCiAgICA5MDA6ICcjODgxMzM3JwogICAgOTUwOiAnIzRjMDUxOScKCmV4cG9ydCBjb2xvcnMgOj0KICAvLyBnZW5lcmljIGNvbG9ycwogIHdoaXRlOiAnI2ZmZmZmZicKICBibGFjazogJyMwMDAwMDAnCgogIC8vYnJhbmQgY29sb3JzCiAgcHJpbWFyeUxpZ2h0OgogICAgMTAwOiBkZWZhdWx0Q29sb3JzLmJsdWUuMTAwCiAgICAyMDA6IGRlZmF1bHRDb2xvcnMuYmx1ZS4yMDAKICAgIDMwMDogZGVmYXVsdENvbG9ycy5ibHVlLjMwMAogICAgNDAwOiBkZWZhdWx0Q29sb3JzLmJsdWUuNDAwCiAgICA1MDA6IGRlZmF1bHRDb2xvcnMuYmx1ZS41MDAKICAgIDYwMDogZGVmYXVsdENvbG9ycy5ibHVlLjYwMAo%3D) and locally, with the same code

**Comment by STRd6** [comment]
Thanks for the report, definitely a bug!

Looks like a combinatoric explosion in the parser from the way nested arguments and nested objects interact.

**Comment by STRd6** [comment]
Just hit this issue again today. Here's a more minimal reproduction:

```civet
defaultColors :=
    50: '#f8fafc'
    100: '#f1f5f9'
    200: '#e2e8f0'
    300: '#cbd5e1'
    400: '#94a3b8'
    500: '#64748b'
    600: '#475569'
    700: '#334155'
    800: '#1e293b'
    900: '#0f172a'
    950: '#020617'
    50: '#f9fafb'
    100: '#f3f4f6'
    200: '#e5e7eb'
    300: '#d1d5db'
    400: '#9ca3af'
    500: '#6b7280'
    600: '#4b5563'
    700: '#374151'
    800: '#1f2937'
    900: '#111827'
    950: '#030712'
    50: '#fafafa'
    100: '#f4f4f5'
    200: '#e4e4e7'
    300: '#d4d4d8'
    400: '#a1a1aa'
    500: '#71717a'
    600: '#52525b'
    700: '#3f3f46'
    800: '#27272a'
    900: '#18181b'
    950: '#09090b'
    50: '#fafafa'
    100: '#f5f5f5'
    200: '#e5e5e5'
    300: '#d4d4d4'
    400: '#a3a3a3'
    500: '#737373'
    600: '#525252'
    700: '#404040'
    800: '#262626'
    900: '#171717'
    950: '#0a0a0a'
    50: '#fafaf9'
    100: '#f5f5f4'
    200: '#e7e5e4'
    300: '#d6d3d1'
    400: '#a8a29e'
    500: '#78716c'
    600: '#57534e'
    700: '#44403c'
    800: '#292524'
    900: '#1c1917'
    950: '#0c0a09'
    50: '#fef2f2'
    100: '#fee2e2'
    200: '#fecaca'
    300: '#fca5a5'
    400: '#f87171'
    500: '#ef4444'
    600: '#dc2626'
    700: '#b91c1c'
    800: '#991b1b'
    900: '#7f1d1d'
    950: '#450a0a'
    50: '#fff7ed'
    100: '#ffedd5'
    200: '#fed7aa'
    500: '#f59e0b'
    600: '#d97706'
```

It doesn't need multiple levels of nesting, just a long object.

**Comment by edemaine** [comment]
I've been exploring traces for this, and I think I understand part of it:

* Each successive line is being considered as a possible implicit call from the previous line. (I'm not yet sure what causes these considerations to fail, but it happens late enough in the process that the consideration is recursive through all the lines.)
* In particular, `IndentedFurther` is matching on every line.
* In particular, this means we're not doing an initial `PushIndent`. I'm amazed that the object literal parses at all...
* We do successfully `PushIndent` for a while, but then `ExpressionizedStatementWithTrailingCallExpressions` fails to match the implicit object literal. It seems like `NestedNonAssignmentExtendedExpression` should check for more than just expressionized statements.
* Even ignoring this, I believe when we match `IndentedFurther` (as part of `ApplicationStart`) we should also `PushIndent` for the duration of the arguments. We don't seem to currently, so these n lines of equal indentation gets treated like its nested n levels. So this leads to a very deep parse stack.
