### ISSUE TITLE
Optional chaining with computed property access shorthand

### ISSUE THREAD

**Issue by tlgreg** [DanielXMoore/Civet#930]
Optional chaining if used together with shorthand computed property access has an invalid output.
Civet `0.6.64`:
```civet
foo?.1
foo?.`bar`
```
Result:
```ts
foo?[1]
foo?[`bar`]
```
Expected:
```ts
foo?.[1]
foo?.[`bar`]
```

**Comment by edemaine** [comment]
Should be fixed in 0.6.65. Thanks for the report!
