### ISSUE TITLE
Typescript Instantiation Expressions

### ISSUE THREAD

**Issue by tlgreg** [DanielXMoore/Civet#939]
Currently `0.6.66` typescript instantiation expressions do not work.
They either throw a parser error or are confused with a chained comparison.
Error:
```civet
bar := foo<number>
```
Unexpected output:
```civet
bar := foo<number>
baz
```
```ts
const bar = foo < number && number > baz;
```

**Comment by edemaine** [comment]
Should be fixed in 0.6.67. Thanks for the report!
