### ISSUE TITLE
Function transformation loses `const` semantics

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#947]
As discussed on the Discord this morning:

> ```civet
> // this will crash JS
> x := 5
> x := 10
> // this won't :-(
> y := -> 5
> y := -> 10
> ```

**Comment by STRd6** [comment]
TypeScript will mark errors for "Duplicate function implementation": https://www.typescriptlang.org/play?experimentalDecorators=true#code/PTAEBcAsEsGdQO7QDbNAYwE4ENaVAFIDKAUOgPYB2s4oAHqALygCsA3GVTfU6AIwAGDiAgx4CKgHJaALgC0AChIAzAK6V04aFVABPBQEpQAbxKhQmAKbhVmSqw4BfFes3b7+o6fNWbd-kIkjkA

**Comment by bbrk24** [comment]
Here's a case where there's no compile error, but the output is unexpected:

```civet
f := -> 5
if true
  f := -> 6
  console.log f()
console.log f()
```

If these compiled to `const` declarations, the second log would say "5". However:

```
$ cat test.js
function f() { return 5; }

if (true) {
  function f() { return 6; }
  console.log(f());
}

console.log(f());
$ node test.js
6
6
```

**Comment by STRd6** [comment]
Thanks, we should add a check in the parser.
