### ISSUE TITLE
`=>` vs. `|>` precedence

### ISSUE THREAD

**Issue by edemaine** [DanielXMoore/Civet#949]
While porting over `cli.civet` to more Civet notation, I noticed [the following](https://civet.dev/playground?code=dmVyc2lvbiA6PSA9PiBpbXBvcnQoIi4uL3BhY2thZ2UuanNvbiIpIHw%2BIGF3YWl0IHw%2BIC52ZXJzaW9u):

```js
version := => import("../package.json") |> await |> .version
↓↓↓
const version = (await () => import("../package.json")).version
```

I expected to instead get:

```js
const version = async () => (await import("../package.json")).version
```

Any opinions on which is correct? Should `=>` or `|>` have higher precedence?

**Comment by STRd6** [comment]
I'm not sure, maybe we could collect some more examples and see what other languages do in a similar situation.

**Comment by edemaine** [comment]
By the way, the workaround for now is to add an indentation:
```js
version := =>
  import("../package.json") |> await |> .version
```
(And this may be evidence for why it should be interpreted this way.)

**Comment by edemaine** [comment]
More evidence: `version := -> import("../package.json") |> await |> .version` parses like I expected, not how `=>` parses.

I think the current parse is a consequence of the `=> expr` rule (where we don't need a braced block), and is a bug; it should match `->`.
