### ISSUE TITLE
Displaced `ts-expect-error` prevents error suppression

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#959]
Let's say that `foo` and the return type of `bar` are nominally incompatible but I know what I'm doing is safe. So I write

```civet
// @ts-expect-error
foo ?=
  bar()
  ||> baz
  ||> qux
```

Civet inserts a statement between the `ts-expect-error` comment and the `foo ??= ...` statement, so the error suppression fails. In fact, it gives a second error, because I have an unused expect-error directive.

**Comment by bbrk24** [comment]
I also can't seem to add `|> & as any` to the end of the pipeline.

**Comment by STRd6** [comment]
I think the correct fix for us will be to make sure we don't insert newlines when transpiling so the TS comments don't get separated.

**Comment by STRd6** [comment]
It seems to work correctly for me:

```civet
// @ts-expect-error
foo ?=
  bar()
  ||> baz
  ||> qux
```

```typescript
// @ts-expect-error
let ref;foo ??=(baz((ref = 
  bar())),qux(ref),ref)
```

https://www.typescriptlang.org/play?experimentalDecorators=true#code/CYUwxgNghgTiAEA3W8BmB7dAueA7ArgLYBGIMAUKJLAsjPMbDgBQCU8AvAHzwDOALjACWuAOaVw0OEhQBHfAA8WUHFFwBPdt3j5cAa1zoA7rnLkA9OfgABfrwC0IBQAdw-RzBjoKEEP3hwqADcGOjwAPzhHMyMAF7MzIGc8OTwDLBsrKwANPIKiSCoOYGsQA

**Comment by bbrk24** [comment]
For some reason the LSP fails to recognize this, then. I reported this bug based on LSP error messages, not compiler output.

**Comment by STRd6** [comment]
Ok, I see the problem: https://civet.dev/playground?code=eAovL0B0cy1leHBlY3QtZXJyb3IKZm9vID89CiAgYmFyKCkKICB8fD4gYmF6CiAgfHw%2BIHF1eAo%3D

The comment is getting duplicated when we adjust the pipeline nodes.
