### ISSUE TITLE
`export default enum` fails to parse

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#965]
```civet
export default enum Foo
  A
```
gives a ParseError pointing at the space after the word "enum."

Workaround:
```civet
enum Foo
  A
export default Foo
```

**Comment by STRd6** [comment]
I think TypeScript requires this as well unless you have another example of what this should compile to:

https://www.typescriptlang.org/play?experimentalDecorators=true#code/KYDwDg9gTgLgBAE2AMwIYFcA29gDt0C2cAYhBHAN4BQccAglQL5A

**Comment by bbrk24** [comment]
If nothing else, you could do the `export default enum Foo { ... }` => `enum Foo { ... }; export default Foo` transformation at the Civet level, no? Though to be honest I'm surprised that isn't valid TS either.

**Comment by bbrk24** [comment]
Actually, on further thought I can see why this wouldn't work. In my head I had `enum Foo` as equivalent to `class Foo` -- and `export default class Foo` *is* allowed -- but TS treats it more similarly to `var Foo`, and I don't believe `export default var Foo` is legal.

**Comment by edemaine** [comment]
I started looking at this as well. Looks like TS allows `export default interface X { ... }`, something Civet is missing, but doesn't allow most other type declarations (e.g. `type`, `enum`).

I think Civet could support the ones TS doesn't, though, via @bbrk24's workaround. [Example](https://www.typescriptlang.org/play?#code/KYOwrgtgBAGlDeAoKKoEMA0UBGiC+iwAHgA4D2ATgC5QAmwAZmmADY0xA)

I think we could similarly support `export default x := 5` and similar declarations, via the same workaround. This is nice for being able to give something a name (and perhaps use it) while simultaneously `export default`ing it.
