### ISSUE TITLE
Enforced redundancy with automatic properties in constructors

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#970]
```civet
class C
  @(#foo: number) // Error: Property '#foo' does not exist on type 'C'.

class D
  #foo: number
  @(#foo) // Error: Parameter 'foo' implicitly has an 'any' type.

class E
  #foo: number
  @(#foo: number) // OK
```

**Comment by edemaine** [comment]
This isn't specific to private properties; it also affects constructors like `@(@foo: number)`.

See #549 for related discussion, though I prefer the focus of this issue which is "how can we remove the redundancy?". Similar to what I [wrote there](https://github.com/DanielXMoore/Civet/issues/549#issuecomment-1576894925), it probably makes sense to transpile:

```js
class C
  @(#foo: number)
↓↓↓
class C {
  #foo: number  // TS only
  @(#foo: number)
}
```

(when `#foo` isn't already declared at the class level)
