### ISSUE TITLE
Compiler does not respect `"module": "CommonJS"`

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#971]
Even if I set `"module": "CommonJS"` in my tsconfig and `"type": "commonjs"` in my package.json, Civet does not translate `import` and `export` statements.

**Comment by bbrk24** [comment]
TypeScript gets *very* mad if I transform all of my imports to requires in-source and then try to use a class from another file in a type annotation.

**Comment by edemaine** [comment]
Can you give an example of what you are trying with require? Perhaps mixing with `import type` could help? 

Translating import to require feels out of scope for Civet. This feels more of a build system issue. I think it makes more sense for your code to actually use the module system you're claiming to be using.

**Comment by bbrk24** [comment]
I was trying to use `require` to work around the issues with `import` I mentioned in the discord. `import` requires the JS filename verbatim, but `require` doesn't.

**Comment by bbrk24** [comment]
That all being said, TypeScript also allows you to write `import foo = require("./foo")`, which is a syntax Civet doesn't seem to support.

**Comment by esthedebeste** [comment]
You could compile your ESM civet code to ESM typescript code, which the typescript compiler can then compile to CJS.
